### ISSUE TITLE
Stuttering playback of streams using new widevine

### ISSUE THREAD

**Issue by DDuck007** [peak3d/inputstream.adaptive#305] opened 2019-08-17 09:27 UTC
Playback stutters if resolution is higher than 640p on Raspberry PI, NUC, ... using the most actual libwidevinecdm.so.
The processor load of one of the four cores (changes cyclically) sporadically goes to 100% => exactly then buffering starts (~2 seconds cycle).

Log:
2019-08-15 19:57:06.625 T:4088684560  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.skygo.de/?package_code=OSPS&parental_rating=0&infolabels=%7B%27plot%27%...
2019-08-15 19:57:06.627 T:3504255856  NOTICE: Creating InputStream
2019-08-15 19:57:06.679 T:3504255856   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2019-08-15 19:57:10.040 T:3504255856  NOTICE: Creating Demuxer
2019-08-15 19:57:10.041 T:3504255856  NOTICE: Opening stream: 1 source: 256
2019-08-15 19:57:10.041 T:3504255856  NOTICE: CVideoPlayerVideo::OpenStream - Creating codec: 27
2019-08-15 19:57:10.042 T:3504255856  NOTICE: Creating video thread
2019-08-15 19:57:10.042 T:3446956912  NOTICE: running thread: video_thread
2019-08-15 19:57:10.074 T:3504255856  NOTICE: Opening stream: 2 source: 256
2019-08-15 19:57:10.075 T:3504255856  NOTICE: Finding audio codec for: 86018
2019-08-15 19:57:10.076 T:3504255856  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2019-08-15 19:57:10.076 T:3504255856  NOTICE: Creating audio thread
2019-08-15 19:57:10.077 T:3645895536  NOTICE: running thread: CVideoPlayerAudio::Process()
2019-08-15 19:57:10.077 T:3504255856  NOTICE: Opening stream: 3 source: 256
2019-08-15 19:57:10.603 T:3446956912  NOTICE: CAMLCodec::OpenDecoder - using V4L2 pts format: 64Bit
2019-08-15 19:57:11.425 T:4088684560  NOTICE: Whitelist search for: width: 1920, height: 1080, fps: 50.000, 3D: false
2019-08-15 19:57:11.425 T:4088684560  NOTICE: Display resolution ADJUST : 1920x1080 @ 50.00 - Full Screen (29) (weight: 0.000)
2019-08-15 19:57:12.937 T:3645895536  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
2019-08-15 19:57:16.540 T:4088684560  NOTICE: Samba is idle. Closing the remaining connections
2019-08-15 19:57:18.517 T:3645895536  NOTICE: CVideoPlayerAudio::Process - stream stalled pts:22.400 clock:22.428
2019-08-15 19:57:25.411 T:3645895536  NOTICE: CVideoPlayerAudio::Process - stream stalled pts:28.053 clock:28.054
2019-08-15 19:57:30.352 T:3645895536  NOTICE: CVideoPlayerAudio::Process - stream stalled pts:31.979 clock:31.986
2019-08-15 19:57:35.454 T:3645895536  NOTICE: CVideoPlayerAudio::Process - stream stalled pts:36.011 clock:36.015
2019-08-15 19:57:39.650 T:3645895536  NOTICE: CVideoPlayerAudio::Process - stream stalled pts:39.296 clock:39.296
2019-08-15 19:57:48.205 T:3645895536  NOTICE: CVideoPlayerAudio::Process - stream stalled pts:46.485 clock:46.489
2019-08-15 19:57:54.847 T:3645895536  NOTICE: CVideoPlayerAudio::Process - stream stalled pts:52.117 clock:52.117
2019-08-15 19:57:58.360 T:4088684560  NOTICE: CVideoPlayer::CloseFile()
2019-08-15 19:57:58.360 T:4088684560  NOTICE: VideoPlayer: waiting for threads to exit
2019-08-15 19:57:58.378 T:3504255856  NOTICE: CVideoPlayer::OnExit()

**Comment by ManiacKill** [comment] 2019-08-23 02:50
http://pasted.co/681ec58a

**Comment by JinRonin** [comment] 2019-08-28 21:15
Well drm protected streams with 1080p and 50fps will not work with pi2/3. Might try max bw 5000000 or 4000000 instead of reducing resolution. There are lower bitrate 720p streams that probably use less cpu.

**Comment by JohnPlayerSpecial2018** [comment] 2019-08-29 20:30
> 
> 
> Well drm protected streams with 1080p and 50fps will not work with pi2/3. Might try max bw 5000000 or 4000000 instead of reducing resolution. There are lower bitrate 720p streams that probably use less cpu.

That's not the point: 1080p50 definitely ran smoothly on Odroid/905x both on SkyGo and DAZN, since new widevine you get stream stalling every few seconds.

On RPi2/3 I'm not sure about FullHD, but 720p50 ran smoothly too on both Addons. Since new widevine you have also stuttering when going higher than 640p.

FPS and bitrate haven't changed at these content providers and SkyGo is even used by HW decoding, so it's new widevine/inputstream related and hopefully solvable by an inputstream update.

**Comment by chstoll** [comment] 2019-09-01 15:49
Is there any workaround in the meantime?

**Comment by shteve99** [comment] 2019-09-06 14:47
Can confirm this behaviour. On a Windows 10 Haswell i3 NUC. Prior to the Widivine update could stream 1080p without issue, now CPU spikes to 100% and the stream jerks. For now I've set the max protected stream resolution to 720p and that plays ok.

**Comment by dagwieers** [comment] 2019-09-06 14:55
FWIW we would like to add support for selecting Widevine version or downgrading Widevine version to InputStream Helper for cases like this. See our [list of ideas](https://github.com/emilsvennesson/script.module.inputstreamhelper/wiki/Ideas#settings).

This would make it easier to troubleshoot issues related to specific Widevine CDM releases, but also offers relieve when known issues exist.

Currently you can pin to a specific Widevine CDM by disabling InputStream Helper in the settings. (Do not disable the module itself, but disable it from updating Widevine)

**Comment by dagwieers** [comment] 2019-09-06 15:04
I opened a specific feature requests for this at emilsvennesson/script.module.inputstreamhelper#165
Feel free to add your ideas or support for this feature. Or help with the implementation.

**Comment by dagwieers** [comment] 2020-02-15 18:02
Is this issue still relevant? Are people still seeing performance regressions with newer Widevine CDM libraries? If not, let's close this issue. cc @peak3d 

*There is no version information in this thread anyway, so not very useful 6 months later.*

**Comment by peak3d** [comment] 2020-02-15 18:18
closed because of inactivity

**Closed by peak3d** 2020-02-15 18:18 UTC
