### ISSUE TITLE
Please give as an option to disable the parsing of frame rates from the manifest/playlist files

### ISSUE THREAD

**Issue by kyl416** [peak3d/inputstream.adaptive#843] opened 2021-11-30 20:46 UTC
Please give us an option to disable the parsing of frame rates from the manifest/playlist files so we can instead only rely on what the player detects for the underlying video segments.

In a perfect world these companies would make sure that the frame rate in the manifest file matches the frame rate of the video segments, but in the real world most of these companies just slap a default value like 24, 30 or 60 even though the underlying streams can be anything like 23.97, 24, 25, 29.97, 30, 50, 59.94 or 60 fps.

Here's one example with the live news stream for WXYZ in Detroit:
https://content.uplynk.com/channel/9c9e4e410b5a471391c116166d8c010e.m3u8

The HLS manifest reports "FRAME-RATE=30.000" for all of the variants, so when I start the stream, my screen swtiches to 60 fps, but the underlying stream is 29.97 fps, so a few seconds later Kodi switches the screen to 59.94 fps:
```
021-11-30 14:46:23.131 T:7084     INFO <general>: [WHITELIST] Searching the whitelist for: width: 1280, height: 720, fps: 30.000, 3D: false
2021-11-30 14:46:23.131 T:7084     INFO <general>: Display resolution ADJUST : AOC 2279WH #1: 1920x1080 @ 60.00Hz (16) (weight: 0.000)
...
2021-11-30 14:46:29.162 T:7084     INFO <general>: [WHITELIST] Searching the whitelist for: width: 1280, height: 720, fps: 29.970, 3D: false
2021-11-30 14:46:29.162 T:7084     INFO <general>: Display resolution ADJUST : AOC 2279WH #1: 1920x1080 @ 59.94Hz (54) (weight: 0.000)
```

For streams that have dynamic ads like the ESPN streams, this can also cause rapid back to back frame rate changes because the manifest reports a new frame rate for each dynamic ad, and 9 out of 10 times the rate in the manifest doesn't match the video of the ad. I know for cases like that it will still trigger a frame rate change for some ads, but at least it would no longer be rapid back to back switches.

**Comment by glennguy** [comment] 2021-11-30 21:34
I've seen the same issue personally, thanks for bringing this up and providing all the details.

I think your solution would help only in certain configurations with the interface resolution and 'Adjust display refresh rate' settings. 

What about the option to pass in a property that forces a certain frame rate i.e overrides whats in the manifest? That way add-on authors could apply to problematic streams.

**Comment by kyl416** [comment] 2021-11-30 22:02
The problem is not all framerates are the same across the board within the same add-on. Like the frame rate for the live event streams used by ESPN, NBC Sports, Fox Sports, Paramount+ and other apps can vary depending on the channel producing the telecast. Apps with Live TV like Hulu, YouTubeTV, Xumo and Pluto can also vary from channel to channel. YouTube also sometimes has the 24 vs 23.97, 30 vs 29.97 and 60 vs 59.94 issue for some videos. Sometimes it can also vary within the same manifest where the lower bitrates have a different frame rate.

Also, limiting it to something that the add-on developer sets wouldn't help users who directly access streams via .strm files. (i.e. many local stations in the USA offer live streams of their newscasts with dynamic ads that you can access via .m3u8 or .mpd URLs).

That's why providing an option to ignore the manifest frame rate is a better solution. Like a global option in the inputstream.adaptive settings that users can set, along with a per stream inputstream.adaptive. flag that can either be set by the add-on developer or the end user as a KODIPROP in a .strm file.

**Comment by matthuisman** [comment] 2021-12-06 01:40
@kyl416 
do you think removing the framerate from the manifest would fix your ESPN issues?
I actually have had a user open an issue about that here: https://github.com/matthuisman/slyguy.addons/issues/46
All my add-ons manifests go via a proxy so I can easily remove the framerate in that before it gets to Kodi / inputstream.

Which leads us to the question - why even parse and set the framerate?
Why not always have IA ignore it and let Kodi deal with it?
@glennguy  i feel we may have discussed this before - getting a bit of deja vu.

**Comment by kyl416** [comment] 2021-12-06 20:23
Yeah, it would be a quick fix for the ESPN issue and possibly some of your other addons that involve live streams with dynamically inserted content during commercial breaks like Fox Sports and some of the Australian Networks like Network 10, but like I mentioned, this issue of conflicting manifest bitrates isn't isolated to specific add-ons. i.e. the WXYZ news stream where the manifest reports 30 fps when in reality those variants are 29.97 fps.

Weather Nation's live stream is another example:
https://content.uplynk.com/channel/c77b777dad7148cb9cf82e8ac99c8e4f.m3u8

In this case, it reports a mix of 30 fps and 15 fps for the lowest variant. When live programming is on this is actually correct, but the commercial breaks are replaced by a 23.98 fps dynamic slate that loops until live programming resumes, so the refresh rate constantly changes to 30 fps and then back to 23.98 fps each time the slate restarts. If it didn't parse the manifest's refresh rate, it would just change once shortly after the start commercial break and change back once live programming resumes.

I think the idea behind parsing the manifest was to instantly change the refresh rate at the start of playback instead of the few seconds it takes Kodi's player to detect the frame rate. If everything matched this wouldn't be an issue, but in reality there are many major networks and streaming providers who slap a default rounded value in their manifests instead of the true value.

**Comment by matthuisman** [comment] 2021-12-06 20:26
yeh, plus IA doesnt know if it's starting to play on an advert or on the main content.

To me it makes sense to just let Kodi always do it?
No different to playing local content etc.
Keeps the same behaviour.
Much better to have it take an extra second to detect and change vs changing twice?

Want me to build you a test IA version not parsing frame-rate at all and see if it works?

**Comment by glennguy** [comment] 2021-12-10 12:04
@kyl416 @matthuisman 
Has anyone tested to see that removing all frame rate references from the playlists will give the behaviour you're looking for?
My suspicion is that in the absence of frame rate indicators it will use the current refresh rate to start playback and adjust afterwards. What I also think will happen is that on a new period, it will revert back to the interface refresh rate once again for start of playback.

**Comment by matthuisman** [comment] 2021-12-10 17:37
I had a user try and it didn't help. As you suspect, i think the issue is
Kodi reverting to it's initial frame rate at ad breaks and then switching
again to real rate

**Comment by glennguy** [comment] 2022-01-31 11:05
@kyl416 I think we should close this issue - it's been established that the behaviour that causes the undesirable experience comes from Kodi's side of things and not this add-on, and that forcing a particular frame rate won't stop Kodi from reverting to the default frame rate after each discontinuity. Not saying that Kodi is doing the wrong thing either, really playlists with changing framerates should a) include them and b) include them correctly and not be rounding them.

**Closed as completed** 2022-02-18 10:29 UTC
Labels: Issue Type: New feature, Component: Video
