### ISSUE TITLE
Dailymotion stream segments fail with 404 error

### ISSUE THREAD

**Issue by Twilight0** [peak3d/inputstream.adaptive#496] opened 2020-08-12 12:37 UTC
- Platform: **Linux Mint 20**
- Kodi: **18.8**
- Inputstream: **2.4.5**

This stream: https://www.dailymotion.com/cdn/manifest/video/xre19f.m3u8?sec=ddx1_nOXv44NIqpNLB5WgoTW9tTsx8H7QiN6iQaWku5ZOg37Op16yQlzuA3rEPTY

From the debug log: 

    2020-08-12 14:31:01.602 T:140541903546112   DEBUG: AddOnLog: InputStream Adaptive: Effective URL https://www.dailymotion.com/cdn/manifest/video/xre19f.m3u8?sec=ddx1_nOXv44NIqpNLB5WgoTW9tTsx8H7QiN6iQaWku5ZOg37Op16yQlzuA3rEPTY
    2020-08-12 14:31:01.602 T:140541903546112   DEBUG: AddOnLog: InputStream Adaptive: Download https://www.dailymotion.com/cdn/manifest/video/xre19f.m3u8?sec=ddx1_nOXv44NIqpNLB5WgoTW9tTsx8H7QiN6iQaWku5ZOg37Op16yQlzuA3rEPTY finished
    2020-08-12 14:31:01.602 T:140541903546112    INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Periods: 1, #Streams in first period: 2, Type: live, Download speed: 0.0000 Bytes/s
    2020-08-12 14:31:01.602 T:140541903546112   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
    2020-08-12 14:31:01.603 T:140541903546112   DEBUG: Previous line repeats 2 times.
    2020-08-12 14:31:01.603 T:140541903546112   DEBUG: AddOnLog: InputStream Adaptive: GetCapabilities()
    2020-08-12 14:31:01.603 T:140541903546112  NOTICE: Creating Demuxer
    2020-08-12 14:31:01.603 T:140541903546112   DEBUG: AddOnLog: InputStream Adaptive: GetStreamIds()
    2020-08-12 14:31:01.603 T:140541903546112   DEBUG: AddOnLog: InputStream Adaptive: GetStream(1001)
    2020-08-12 14:31:01.603 T:140541903546112   DEBUG: AddOnLog: InputStream Adaptive: GetStream(1002)
    2020-08-12 14:31:01.603 T:140541903546112   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 1001 with codec_id 27
    2020-08-12 14:31:01.603 T:140541903546112   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 1002 with codec_id 86018
    2020-08-12 14:31:01.603 T:140541903546112  NOTICE: Opening stream: 1001 source: 256
    2020-08-12 14:31:01.603 T:140541903546112   DEBUG: AddOnLog: InputStream Adaptive: OpenStream(1001)
    2020-08-12 14:31:01.604 T:140541903546112   DEBUG: AddOnLog: InputStream Adaptive: Selecting stream with conditions: w: 1309, h: 735, bw: 3600000
    2020-08-12 14:31:01.604 T:140541903546112   DEBUG: CurlFile::Open(0x7fd23c6f4c10) https://proxy-002.ix7.dailymotion.com/sec(kQ-xm7K7XuJL2OOBtgtlOJH7DIuVl67zjGYasf089kAcNdcS6AzyCP912IlsGrPvYcsQx6qQ0NFwFwKG8jeiz-xyyzCrzw_faYj4GpCWLNs)/video/154/400/46004451_mp4_h264_aac_hq.m3u8#cell=core&qos_ugc=1
    2020-08-12 14:31:01.604 T:140541903546112    INFO: easy_acquire - Created session to https://proxy-002.ix7.dailymotion.com
    2020-08-12 14:31:02.436 T:140541903546112   DEBUG: AddOnLog: InputStream Adaptive: Download https://proxy-002.ix7.dailymotion.com/sec(kQ-xm7K7XuJL2OOBtgtlOJH7DIuVl67zjGYasf089kAcNdcS6AzyCP912IlsGrPvYcsQx6qQ0NFwFwKG8jeiz-xyyzCrzw_faYj4GpCWLNs)/video/154/400/46004451_mp4_h264_aac_hq.m3u8#cell=core&qos_ugc=1 finished
    2020-08-12 14:31:02.437 T:140541895153408   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
    2020-08-12 14:31:02.437 T:140541895153408   DEBUG: CurlFile::Open(0x7fd2385db240) https://www.dailymotion.com/sec(kQ-xm7K7XuJL2OOBtgtlOJH7DIuVl67zjGYasf089kAcNdcS6AzyCP912IlsGrPvYcsQx6qQ0NFwFwKG8jeiz-xyyzCrzw_faYj4GpCWLNs)/frag(1)/video/154/400/46004451_mp4_h264_aac_hq.ts
    2020-08-12 14:31:02.581 T:140541895153408   ERROR: AddOnLog: InputStream Adaptive: Download https://www.dailymotion.com/sec(kQ-xm7K7XuJL2OOBtgtlOJH7DIuVl67zjGYasf089kAcNdcS6AzyCP912IlsGrPvYcsQx6qQ0NFwFwKG8jeiz-xyyzCrzw_faYj4GpCWLNs)/frag(1)/video/154/400/46004451_mp4_h264_aac_hq.ts failed with error: 404
    2020-08-12 14:31:02.582 T:140541903546112   DEBUG: AddOnLog: InputStream Adaptive: GetStream(1001)
    2020-08-12 14:31:02.582 T:140541903546112 WARNING: OpenStream - Unsupported stream 1001. Stream disabled.

Kodi also fails to play this without calling inputstream addon.

**Comment by glennguy** [comment] 2021-06-09 05:09
@Twilight0 Is this still an issue for you? There's been a lot of work done around segment url calculation for recent Matrix versions. Can we close it?

**Comment by Twilight0** [comment] 2021-06-09 06:09
> @Twilight0 Is this still an issue for you? There's been a lot of work done around segment url calculation for recent Matrix versions. Can we close it?

Give me a few hours to have it tested and report back.

**Comment by Twilight0** [comment] 2021-06-09 16:58
Nope, still getting errors like this:

    2021-06-09 19:56:05.104 T:149261   DEBUG <general>: AddOnLog: inputstream.adaptive: AdaptiveStream: trying to reload segment ...
	2021-06-09 19:56:05.104 T:149261   DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'Origin: https://www.dailymotion.com'
	2021-06-09 19:56:05.104 T:149261   DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
	2021-06-09 19:56:05.104 T:149261   DEBUG <general>: CurlFile::Open(0x7f145000fa50) https://www.dailymotion.com/sec(QnwGbYX9Ck4JBJsmoqLQiFooU-ND2ytAMRYF98qz49T9jeTk6vil4S0ilS3Kui9rvXHcRHV9rxDppIQG3EIGDjTTqyNWhqEjcCMZ7ALq7GY)/frag(1)/video/741/671/389176147_mp4_h264_aac_3.ts
	2021-06-09 19:56:05.486 T:149261   ERROR <general>: AddOnLog: inputstream.adaptive: Download failed with error 404: https://www.dailymotion.com/sec(QnwGbYX9Ck4JBJsmoqLQiFooU-ND2ytAMRYF98qz49T9jeTk6vil4S0ilS3Kui9rvXHcRHV9rxDppIQG3EIGDjTTqyNWhqEjcCMZ7ALq7GY)/frag(1)/video/741/671/389176147_mp4_h264_aac_3.ts

This happens only in VOD streams

Platform: Linux Mint 20
Kodi 19.1 stable
inputstream adaptive 2.6.16-1~focal

**Comment by Arias800** [comment] 2022-02-10 08:20
Hello,
I have found where the problem came from.
The url use by InputStream Adaptive is this :
`https://www.dailymotion.com/sec(kQ-xm7K7XuJL2OOBtgtlOJH7DIuVl67zjGYasf089kAcNdcS6AzyCP912IlsGrPvYcsQx6qQ0NFwFwKG8jeiz-xyyzCrzw_faYj4GpCWLNs)/frag(1)/video/154/400/46004451_mp4_h264_aac_hq.ts`

But on the website, the real url is this one :
`https://proxy-002.ix7.dailymotion.com/sec(kQ-xm7K7XuJL2OOBtgtlOJH7DIuVl67zjGYasf089kAcNdcS6AzyCP912IlsGrPvYcsQx6qQ0NFwFwKG8jeizyN0dPJ1_WBMsV0NukMr-Fk)/frag(1)/video/154/400/46004451_mp4_h264_aac_hq.ts`

The domain use by inpustream is not the correct one.
I hope that help you for fixing this bug.

**Comment by CastagnaIT** [comment] 2022-02-25 13:22
@Arias800 can you provide the manifest?

**Comment by Arias800** [comment] 2022-02-25 14:10
Yeah, this happens for this one :
https://www.dailymotion.com/cdn/live/video/x5gv5rr.m3u8?sec=-_fFygb_d6ykHowRuKbxN3w2kt8cV5Y_DjM3xevSK7v2Mqo_Ytq0JkxHaA0aK-MIDsS7iMB8pc9DsjQFr0m9Pg&dmTs=931453&dmV1st=92F5A987DB5806BDC141F39AF7ED3874

The first link is correctly get (because the domain is already in the link), but the .key and the .ts isn't.
If the link above has expired, he came from here (it's a French channel, so the stream is active 24/7) : https://www.dailymotion.com/video/x5gv5rr

Note : Just for information, I'm using Kodi 20.

**Comment by CastagnaIT** [comment] 2022-02-26 15:56
i have found a way to fix but i am not sure that it is correct
https://github.com/CastagnaIT/inputstream.adaptive/commit/ffca5ba6c5af23eb1692e61d8dc076ca6b23a834

The problem is that now kodi say unsupported stream, usually this is for unsupported video codec
log: https://paste.kodi.tv/cusovatefi.kodi
then also in this case the playback not works

**Comment by Arias800** [comment] 2022-03-03 13:39
According to VLC, the audio codec that use by the livestream is ADTS.

**Comment by matthuisman** [comment] 2022-03-03 21:37
**Inputstream: 2.4.5 is very old.**

I suspect this is a redirect issue that was fixed by one my PRs in a later version

we shouldn't really even look at bugs for old versions of IA as they are probably fixed in later versions
Should always need to be at least latest stable.

@[Arias800](https://github.com/Arias800)
Please test same stream in Kodi 19 with latest Inputstream Adaptive and report back

**Comment by matthuisman** [comment] 2022-03-03 21:48
(ignore my last comment) 

the below has everything I need to investigate
https://www.dailymotion.com/video/x5gv5rr

**Comment by joaopa00** [comment] 2022-03-25 05:49
Looks like the same occurs with videos from digiteka (for instance video from weo site (https://www.weo.fr/direct/)

**Closed as completed** 2023-02-14 11:22 UTC
Labels: Issue Type: Bug
