### ISSUE TITLE
Disney+ - no subtitles on resume

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#1419] opened 2023-11-15 07:15 UTC
not working on both kodi 20 and 21
as per https://github.com/matthuisman/slyguy.addons/issues/500

i have confirmed the same. 
if i start normally - subtitles are ok
if I resume - subtitles dont work. They are selectable just dont show anything

Log
First play is no resume.
turn on subs and they display ok
2nd play resume
subs are turned on but nothing shown

[kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/13361398/kodi.log.txt)
[master.m3u8.txt](https://github.com/xbmc/inputstream.adaptive/files/13361410/master.m3u8.txt)
[subs.m3u8.txt](https://github.com/xbmc/inputstream.adaptive/files/13361409/subs.m3u8.txt)
[video.m3u8.txt](https://github.com/xbmc/inputstream.adaptive/files/13715440/video.m3u8.txt)
[audio.m3u8.txt](https://github.com/xbmc/inputstream.adaptive/files/13715443/audio.m3u8.txt)

maybe related to X-DISCONTINUITY ?

**Comment by matthuisman** [comment] 2023-11-15 07:15
we did have https://github.com/xbmc/inputstream.adaptive/issues/836 but i thought that got fixed?
or just a new issue

**Comment by matthuisman** [comment] 2023-11-15 07:27
Kodi 19 works. 

Kodi 19 + IA 19.0.7
Remember subs enabled = no
Resume + subs = **YES**

Kodi 20 + IA 20.3.14
Remember sub enabled = no
Resume + subs = no

Kodi 21 + IA 21.3.1
Remember sub enabled = yes
Resume + subs = no

**Comment by CastagnaIT** [comment] 2023-11-15 08:29
with issue https://github.com/xbmc/inputstream.adaptive/issues/836
there was more problems where one has been closed by linked fix PR
but at that time no one has tested with D+, my subscription was expired
and no one had a subscription to make tests
i was thinking that the sample stream was similar because of similar problems

one of the problems was with DEMUX_SPECIALID_STREAMCHANGE, has not been solved
(this in some situations kodi core could reset audio/subtitle settings without trying keep the used settings like language, on/off... while change chapter, or quality change ISA "Adaptive" stream selector, a very nonsense kodi behaviour...)

but here you affirm

> if I resume - subtitles dont work. They are selectable just dont show anything

the log show dropping packets 
`debug <general>: CVideoPlayer::CheckPlayerInit - dropping packet type:3 dts:604812537.000000 to get to start point at 612000000.000000`
look like something wrong with PTS

**Comment by matthuisman** [comment] 2023-11-15 08:32
Let me know what I can do to help :) 
I can probably share a settings.xml for the logged in account I use so you can debug / test if needed

**Comment by CastagnaIT** [comment] 2023-11-15 14:13
i just tested the fix pr sample again (this sample has French+Chinese subs):
https://playertest.longtailvideo.com/adaptive/elephants_dream_v4/index.m3u8

i can see that also with this sample there is a problem
that could be related also to the D+ problem
i can see two behaviours

case 1, subtitles are not displayed:
- set kodi subtitle language to Spanish (or another one not available in the sample stream)
- play the sample
you can see that subtitles are "off" by default,
if you turn "on" subtitles manually from GUI, the subs are not displayed

case 2, subtitles are displayed:
- set kodi subtitle language to Chinese
- play the sample
in this case the language is available, subs are turned "on" by default, and correctly displayed

each time you change from GUI settings is needed open kodi myvideo database
and delete the stream entry from "files" table otherwise sub settings are permanent stored and falsify all future tests

however for the bad case 1
i can see that when i enable subs manually ISA download file
`subtitlechunk_lzho_w2018715716_b160000_slen_t64RW5nbGlzaA==_50.webvtt`
where instead should download file
`subtitlechunk_lzho_w2018715716_b160000_slen_t64RW5nbGlzaA==_0.webvtt`
so this explain the reason why there are no subs displayed, the downloaded package is too far forward of the played time position
sure something wrong somewhere...
EDIT: tested second time i get different results, so i dont know this require more time and deeps investigations (kodi 19 dont help because its different and the old ISA versions have a lot of hacks)

**Comment by CastagnaIT** [comment] 2023-11-30 09:58
i debugged Kodi with my sample and for now i can confirm this:

ISA send subtitles packets to Kodi core and they are correctly parsed by Kodi from `COverlayCodecWebVTT`,
but looks like there is a problem somewhere on Kodi core, because in the method used before "query" libass to generate subtitles images `CRenderer::Render` in OverlayRenderer
https://github.com/xbmc/xbmc/blob/21.0b1-Omega/xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp#L146-L155
the buffer `m_buffers` is always empty therefore cannot "query" libass to generate subtitles images

i suspect that somewhere kodi start the video without subtitles enabled, and they are enabled some after time,
but for some reason dont call the `CRenderer::AddOverlay` method to enable the buffer loop, and this cause the problem

**Comment by CastagnaIT** [comment] 2023-12-19 14:14
im not full sure but by looking at log i think to understand this
the seek has been done at 612000000, i assume at ~ 10m20secs (?) hoping my calculated time its right
from the log is possible to see that ISA starts download subs from file/segments:
a532-MAIN/06/subtitles_1/seg_00000.vtt
a532-MAIN/06/subtitles_1/seg_00001.vtt

so seem that start downloads subs segments from the start of period (initial segment) and not from the right timeline segment that should be:
a532-MAIN/06/subtitles_1/seg_00002.vtt

so the problem could be that `current_segment_` (in representation) has not been set correctly or also not set,
the "current segment" should be set when `CSession::SeekTime` call `seek_time` here:
https://github.com/xbmc/inputstream.adaptive/blob/21.4.0-Omega/src/Session.cpp#L1208
(done when `seek_time` call `ResetCurrentSegment`)

after that the subtitle reader call `ensureSegment`:
https://github.com/xbmc/inputstream.adaptive/blob/21.4.0-Omega/src/samplereader/SubtitleSampleReader.cpp#L142
and that method should get the specified segment from here:
https://github.com/xbmc/inputstream.adaptive/blob/21.4.0-Omega/src/common/AdaptiveStream.cpp#L849
where, if not set, pick the first segment of period

imo the problem could be around here
but yes its needed a D+ account to understand better
or if if you are able do by yourself you can try investigate by adding some log prints on mentioned methods linked above

**Comment by matthuisman** [comment] 2024-01-02 08:49
@CastagnaIT have just emailed you :)

**Comment by CastagnaIT** [comment] 2024-01-02 16:17
thanks i will try

**Comment by CastagnaIT** [comment] 2024-01-15 10:03
i made a fix PR
always a nightmare these subtitles...

a confirmation test would be better that you known better D+ and other of your video addons to be sure that there are no regressions
~test builds https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1454/1/artifacts~ OLD see next comment

**Comment by CastagnaIT** [comment] 2024-01-15 15:34
new test build: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1454/3/artifacts

**Comment by matthuisman** [comment] 2024-04-07 03:53
@CastagnaIT getting people having issues with subs again. Suspect maybe something broke with latest big rework (expected).
Do you still have the Disney+ access so you can test?

**Comment by CastagnaIT** [comment] 2024-04-07 07:22
> Do you still have the Disney+ access so you can test?

theoretically yes i have to check because i no longer enabled D+ addon

**Comment by CastagnaIT** [comment] 2024-04-07 08:53
yes was already found the underlying problem
for now i restore the old workaround

**Closed as completed by CastagnaIT** 2024-04-07 08:53 UTC

**Comment by Badsheep** [comment] 2024-07-05 12:10
Hello CastagnalT and matthuisman,

I'm still having this issue...

My Kodi is 21.0-ALPHA 1 (20.90.101)
My Disney+ addon is 0.16.12
I'm on Mac OS.

Is it normal ?
Thanks for your excellent work,
Badsheep

**Comment by CastagnaIT** [comment] 2024-07-05 13:02
to me subs after video resume are shown correctly

**Comment by Badsheep** [comment] 2024-07-05 13:34
I upgraded my Kodi version, I think it was an old release... it's working now. Thanks and sorry for the waste of time
