### ISSUE TITLE
KODI crashes in ism file. (KODI 20)

### ISSUE THREAD

**Issue by mbebe** [peak3d/inputstream.adaptive#1072] opened 2022-11-29 20:07 UTC
It only appears on KODI 20 (prereleased and all nightly).
ism file: 
[ism.txt](https://github.com/xbmc/inputstream.adaptive/files/10116845/ism.txt)
url: https://ec04-szz1.waw5.cache.orange.pl/canal/v/canal/vod/store01/CAP_21042687/_/hd4-hssdrm02.ism/Manifest
 In KODI 19 base url is created correctly (without Manifest at the end) - 
`https://ec04-szz1.waw5.cache.orange.pl/canal/v/canal/vod/store01/CAP_21042687/_/hd4-hssdrm02.ism/QualityLevels(128000)/Fragments(Polski=0)` and it works perfectly.

but in KODI20 ```https://ec04-szz1.waw5.cache.orange.pl/canal/v/canal/vod/store01/CAP_21042687/_/hd4-hssdrm02.ism/Manifest/QualityLevels(128000)/Fragments(Polski=0)```
so it's cause errors.
After fix it via proxy KODI is crashed.

[lg.txt](https://github.com/xbmc/inputstream.adaptive/files/10116911/lg.txt)

**Comment by Paco8** [comment] 2022-12-16 14:27
I came here to report the same problem. I attach a sample plugin to reproduce the problem. In the settings you can turn on a proxy. Without the proxy the video won't play because of wrong urls. With proxy kodi crashes with a segmentation fault. The crash happens in all systems I tested (Windows, Android and Mac OS).

[plugin.video.ism-test-0.0.1.zip](https://github.com/xbmc/inputstream.adaptive/files/10246517/plugin.video.ism-test-0.0.1.zip)

**Comment by glennguy** [comment] 2022-12-17 14:26
Thanks very much @Paco8 for the easy reproduction!

I've solved the crashing I think in #1080, I'll look at the malformed url next.

**Comment by glennguy** [comment] 2022-12-18 10:21
#1081 should remove the need for a proxy

**Comment by CastagnaIT** [comment] 2023-02-17 16:21
we can close the issue?

**Closed as completed** 2023-03-01 12:52 UTC
Labels: Issue Cleanup: Ask Reporter
