### ISSUE TITLE
IA update causes playback issues until Kodi reboots

### ISSUE THREAD

**Issue by dagwieers** [peak3d/inputstream.adaptive#454] opened 2020-05-21 21:21 UTC
This is an issue I have seen since ever. Whenever we get a new InputStream Adaptive release from our distribution (LibreELEC) playback that requires InputStream Adaptive fails to work until Kodi is restarted.

So this impacts Netflix, VRT NU, VTM GO and may more add-ons.

The actual issue is that Kodi cannot load the new library after the update. IA was updated to v2.4.5 (in LibreELEC it is 2.4.5.1 actually) but the system is still looking for v2.4.4.

> **ERROR: ADDON: Could not locate inputstream.adaptive.so.2.4.4**

Below is a more detailed log:
```log
2020-05-21 22:42:15.767 T:806302592  NOTICE: [script.module.inputstreamhelper] Widevine update check was made on 2020-05-05T20:21:39
2020-05-21 22:42:15.880 T:1937267136  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/show/70264888/season/80104624/episode/80104627/?profile_guid=A7VPR5DWQFGWLKQWXOJGN5UXMM
2020-05-21 22:42:15.880 T:1188033408 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
2020-05-21 22:42:15.884 T:953152384  NOTICE: Creating InputStream
2020-05-21 22:42:15.885 T:953152384   ERROR: ADDON: Could not locate inputstream.adaptive.so.2.4.4
2020-05-21 22:42:15.886 T:953152384   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
2020-05-21 22:42:15.886 T:953152384   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/play/show/70264888/season/80104624/episode/80104627/?profile_guid=A7VPR5DWQFGWLKQWXOJGN5UXMM]
2020-05-21 22:42:15.886 T:953152384  NOTICE: CVideoPlayer::OnExit()
2020-05-21 22:42:16.097 T:1937267136  NOTICE: CVideoPlayer::CloseFile()
2020-05-21 22:42:16.098 T:1937267136  NOTICE: VideoPlayer: waiting for threads to exit
2020-05-21 22:42:16.098 T:1937267136  NOTICE: VideoPlayer: finished waiting
```

**Comment by glennguy** [comment] 2020-05-24 00:35
@dagwieers have seen this forever too! Turn the TV on, streams silently fail to play. Then you remember you have to restart... but most users would probably not know this and blame the addon they're trying to use.

I suspect the issue lies in Kodi itself, maybe some sort of vfs cache issue. Also it doesn't affect platforms where the filename is always the same eg. Windows - inputstream.adaptive.dll

**Comment by matthuisman** [comment] 2020-05-26 22:13
i wonder if this is caused by the same cache issue that would cause add-ons to fail to install via zip if done twice. That was fixed with this PR in master: https://github.com/xbmc/xbmc/pull/17701

Be interested to know if the issue still happens in a nightly build of Matrix?
I guess to simulate, I could install a Alpha build of Libreelec Matrix on a Pi.
Then update IA and see if content plays?

As a workaround until it's fixed - could you keep track of the IA version in IA Helper?
Then when IA Helper is called, if the IA version has changed - show a message
 "IA has been updated, if content does not play - please restart Kodi"
Then store the new version so the message isn't shown again.

Also, another PR that was merged that may be of interest is the issue with kodi ffmpeg not playing live streams from live is fixed (again, just in master): https://github.com/xbmc/xbmc/pull/17816
You can now use ResumeTime correctly with kodis ffmpeg to play from start or live.

**Comment by AlwinEsch** [comment] 2020-08-15 10:03
Not thought about this issue but seems to become fixed with https://github.com/xbmc/xbmc/pull/18291

**Comment by AlwinEsch** [comment] 2020-08-15 10:05
Forget there is VFS addon here is Inputstream but I'm look now think there it make the same as on VFS and make another request about.

**Comment by dagwieers** [comment] 2021-02-20 08:42
Related issues:
- https://discourse.coreelec.org/t/missing-inputstream-adaptive-so-version-symlink/5915
- https://forum.kodi.tv/showthread.php?tid=331136&page=6
- https://forum.libreelec.tv/thread/13438-inputstream-not-working-on-wetek-play-2-alpha-8-90-005/

**Comment by DjDiabolik** [comment] 2021-05-06 15:59
I have same exact issue on YOUTUBE Addons.......... portion of log:
https://paste.kodi.tv/ujunuyopuy.kodi

How i can fix this issue ???

**Comment by glennguy** [comment] 2021-05-17 12:19
This is an issue that can't be fixed in this repo - root cause would be in Kodi itself

**Comment by dagwieers** [comment] 2021-05-17 12:26
@glennguy I understand, but can we keep this ticket open as a tracking ticket (and maybe pin it at the top) as this is one of the issues affecting a lot of people.

**Comment by glennguy** [comment] 2021-05-18 10:03
Sure thing

**Closed as completed** 2024-10-28 07:31 UTC
Labels: Resolution: External
