### ISSUE TITLE
PeerTube HLS stream has no sound

### ISSUE THREAD

**Issue by mxraw** [peak3d/inputstream.adaptive#610] opened 2021-03-02 20:12 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
I have written a small addon for receiving [PeerTube HLS stream](https://docs.joinpeertube.org/admin-configuration) using HLS via IA.
Video works well however, no sound is playing. The Audio codec is displayed as [unknown] AAC channels 0.
Video and audio do work without IA, however performance is in the gutter, especially when seeking.

An example stream m3u8 can be found here:
https://framatube.org/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d

The relevant code from the plugin is here:
```python
        url="https://framatube.org/static/streaming-playlists/hls/9c9de5e8-0a1e-484a-b099-e80766180a6d/master.m3u8"
        manifest="hls"
        item = xbmcgui.ListItem(path=url)
        item.setProperty("inputstream", "inputstream.adaptive")
        item.setProperty("inputstream.adaptive.manifest_type", manifest)
        xbmcplugin.setResolvedUrl(self.handle, True, listitem=item)
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The HLS video stream plays fine and audio can be heard

## Actual Behavior

The HLS video stream plays fine but audio cannot be heard

## Possible Fix

Unknown

### To Reproduce

1. Write an addon that receives HLS streams from PeerTube
2. Hit play
3. Do not hear anything

### Debuglog

The debuglog can be found here:
https://paste.ubuntu.com/p/G2z3NJTQVT/

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: All Linux Distributions
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by matthuisman** [comment] 2021-03-02 20:37
master.m3u8
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=1190467,RESOLUTION=1920x1080,FRAME-RATE=24,CODECS="avc1.64001f,mp4a.40.2"
1080.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=268464,RESOLUTION=426x240,FRAME-RATE=24,CODECS="avc1.64001f,mp4a.40.2"
240.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=709176,RESOLUTION=1280x720,FRAME-RATE=24,CODECS="avc1.64001f,mp4a.40.2"
720.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=365746,RESOLUTION=640x360,FRAME-RATE=24,CODECS="avc1.64001f,mp4a.40.2"
360.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=464277,RESOLUTION=852x480,FRAME-RATE=24,CODECS="avc1.64001f,mp4a.40.2"
480.m3u8
```
360.m3u8
```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="9c9de5e8-0a1e-484a-b099-e80766180a6d-360-fragmented.mp4",BYTERANGE="1327@0"
#EXTINF:5.916667,
#EXT-X-BYTERANGE:241191@1327
9c9de5e8-0a1e-484a-b099-e80766180a6d-360-fragmented.mp4
#EXTINF:4.000000,
#EXT-X-BYTERANGE:198516@242518
9c9de5e8-0a1e-484a-b099-e80766180a6d-360-fragmented.mp4
#EXTINF:4.000000,
#EXT-X-BYTERANGE:205411@441034
9c9de5e8-0a1e-484a-b099-e80766180a6d-360-fragmented.mp4
#EXTINF:3.083333,
#EXT-X-BYTERANGE:145147@646445
9c9de5e8-0a1e-484a-b099-e80766180a6d-360-fragmented.mp4
..........
```
test .strm file: [no_audio.strm.txt](https://github.com/xbmc/inputstream.adaptive/files/6071672/no_audio.strm.txt)
(no audio on Leia or Matrix)

**Comment by glennguy** [comment] 2021-03-02 21:44
With byterange the handling is different, url is the same for all segments/init and range_begin / range_end is used for the range. It's sort of treated as a special case (lots of conditional checks for bool `byteRange`)
The real issue is that there is currently no support for fragmented MP4 streams that contain both video and audio in the same representation i.e like .ts streams do.
I opened an issue about this a while ago and started development on a fix but never completed it, I got stuck at some point

**Comment by mxraw** [comment] 2021-03-02 22:09
As an aside, PeerTube uses [hls.js](https://github.com/video-dev/hls.js/) client-side. Perhaps you can take a look how they do it.

**Comment by matthuisman** [comment] 2021-03-03 00:24
@cmF3 
Here is the issue Glenn was talking about: https://github.com/xbmc/inputstream.adaptive/issues/343
That needs to be implemented to get audio on these streams.

**Comment by glennguy** [comment] 2021-05-15 12:55
Closing as duplicate of #343
It's on a long to-do list, if I can figure out how to solve.

**Closed as completed by glennguy** 2021-05-15 12:55 UTC
