### ISSUE TITLE
Error using input stream adaptive with LineageOS

### ISSUE THREAD

**Issue by werimail** [peak3d/inputstream.adaptive#771] opened 2021-08-05 08:13 UTC
Hi guys, I'am using Kodi 19.1 (Matrix) with LineageOS running on Raspberry Pi 4 with Android 11.0.0 (API level 30). When I Start using Addons the widevine encryption the Inputstream Adaptive only plays the sound but no picture. Therefore I created a Kodi.log File: 

```
2021-08-05 09:58:43.134 T:9529     INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.joyn_app/live/eurosport1-de/Eurosport%201
2021-08-05 09:58:43.331 T:9924     INFO <general>: Creating InputStream
2021-08-05 09:58:43.338 T:9924     INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1024 x 600)
2021-08-05 09:58:43.352 T:9924    ERROR <general>: GetDirectory - Error getting /data/user/0/net.kodinerds.maven.kodi/cache/apk/assets/addons/inputstream.adaptive/
2021-08-05 09:58:43.365 T:9924    ERROR <general>: AddOnLog: inputstream.adaptive: Key system request: com.widevine.alpha
2021-08-05 09:58:43.527 T:9903     INFO <general>: Python interpreter stopped
2021-08-05 09:58:43.592 T:9924     INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 2, Type: live, Download speed: 3262603.7905 Bytes/s
2021-08-05 09:58:43.756 T:9924  WARNING <general>: AddOnLog: inputstream.adaptive: Initializing stream with unknown KID!
2021-08-05 09:58:44.044 T:9924     INFO <general>: AddOnLog: inputstream.adaptive: Empty Service Certificate
2021-08-05 09:58:44.386 T:9924     INFO <general>: Creating Demuxer
2021-08-05 09:58:44.387 T:9924     INFO <general>: Opening stream: 1001 source: 256
2021-08-05 09:58:44.431 T:9924     INFO <general>: Creating video codec with codec id: 27
2021-08-05 09:58:44.443 T:9924     INFO <general>: CDVDVideoCodecAndroidMediaCodec::Open: Secure decoder requested: false (stream flags: 0)
2021-08-05 09:58:44.445 T:9924    ERROR <general>: CDVDVideoCodecAndroidMediaCodec:: Failed to create Android MediaCodec
2021-08-05 09:58:44.446 T:9924    ERROR <general>: CDVDVideoCodecFFmpeg::Open() CryptoSessions unsupported!
2021-08-05 09:58:44.446 T:9924    ERROR <general>: CVideoPlayerVideo::OpenStream - could not open video codec
2021-08-05 09:58:44.446 T:9924  WARNING <general>: OpenStream - Unsupported stream 1001. Stream disabled.
2021-08-05 09:58:44.446 T:9924     INFO <general>: Opening stream: 1002 source: 256
2021-08-05 09:58:44.499 T:9924     INFO <general>: Finding audio codec for: 86018
2021-08-05 09:58:44.523 T:9924     INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2021-08-05 09:58:44.523 T:9924     INFO <general>: CDVDAudioCodecAndroidMediaCodec Use raw decoder and decode using ff-aac
2021-08-05 09:58:44.567 T:9924     INFO <general>: CDVDAudioCodecAndroidMediaCodec Open Android MediaCodec amc-aac
2021-08-05 09:58:44.568 T:9924     INFO <general>: Creating audio thread
2021-08-05 09:58:44.568 T:9945     INFO <general>: running thread: CVideoPlayerAudio::Process()
2021-08-05 09:58:45.109 T:9945     INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2021-08-05 09:58:45.109 T:9945     INFO <general>: CDVDAudioCodecAndroidMediaCodec Use raw decoder and decode using ff-aac
2021-08-05 09:58:45.127 T:9945     INFO <general>: CDVDAudioCodecAndroidMediaCodec Open Android MediaCodec amc-aac
2021-08-05 09:58:45.161 T:9945     INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2021-08-05 09:58:45.161 T:9945     INFO <general>: CDVDAudioCodecAndroidMediaCodec Use raw decoder and decode using ff-aac
2021-08-05 09:58:45.187 T:9945     INFO <general>: CDVDAudioCodecAndroidMediaCodec Open Android MediaCodec amc-aac
2021-08-05 09:58:45.194 T:9945     INFO <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
2021-08-05 09:58:45.222 T:9538     INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-08-05 09:58:45.228 T:9538     INFO <general>: Trying to open: samplerate: 48000, channelMask: 12, encoding: 4
2021-08-05 09:58:45.244 T:9538     INFO <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 48000 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 65664 m_frames: 2052 m_frameSize: 8 channels: 2
2021-08-05 09:58:45.370 T:9924  WARNING <general>: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
2021-08-05 09:58:53.073 T:9529     INFO <general>: CVideoPlayer::CloseFile()
2021-08-05 09:58:53.075 T:9529     INFO <general>: VideoPlayer: waiting for threads to exit
2021-08-05 09:58:53.076 T:9924     INFO <general>: CVideoPlayer::OnExit()
2021-08-05 09:58:53.076 T:9924     INFO <general>: Closing stream player 1
2021-08-05 09:58:53.077 T:9924     INFO <general>: Waiting for audio thread to exit
2021-08-05 09:58:53.078 T:9945     INFO <general>: thread end: CVideoPlayerAudio::OnExit()
2021-08-05 09:58:53.079 T:9924     INFO <general>: Closing audio device
2021-08-05 09:58:53.098 T:9538     INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-08-05 09:58:53.098 T:9924     INFO <general>: Deleting audio codec
2021-08-05 09:58:53.104 T:9538     INFO <general>: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2021-08-05 09:58:53.130 T:9924     INFO <general>: ADDON: Dll Destroyed - InputStream Adaptive
2021-08-05 09:58:53.132 T:9529     INFO <general>: VideoPlayer: finished waiting
2021-08-05 09:58:53.132 T:9529     INFO <general>: CVideoPlayer::CloseFile()
2021-08-05 09:58:53.132 T:9529     INFO <general>: VideoPlayer: waiting for threads to exit
2021-08-05 09:58:53.133 T:9529     INFO <general>: VideoPlayer: finished waiting
2021-08-05 09:58:53.134 T:9538     INFO <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 60416 m_frames: 1888 m_frameSize: 8 channels: 2
2021-08-05 09:58:53.413 T:9529    ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2021-08-05 09:58:53.486 T:10003    INFO <general>: initializing python engine.
2021-08-05 09:58:54.672 T:10003    INFO <general>: CPythonInvoker(17, /storage/emulated/0/Android/data/net.kodinerds.maven.kodi/files/.kodi/addons/plugin.video.joyn_app/main.py): script successfully run
2021-08-05 09:58:55.085 T:10003    INFO <general>: Python interpreter stopped
```

Has anyone an idea?
Thanks Weri

**Comment by CastagnaIT** [comment] 2021-11-28 15:00
please check if MediaCodec and MediaCodec surface on Kodi->Setting->Player->videos
are enabled, if not enable them

**Comment by werimail** [comment] 2021-11-30 07:51
Hi CastagnaIT
I have checked the settings for the MediaCodec and MediaCodec surface. Both settings are active. Unfortunately, the result is the same: no picture but sound? I have added a complete Kodi log file again.
[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/7623885/kodi.log)
Greetings Weri

**Comment by CastagnaIT** [comment] 2021-11-30 08:52
i suspect that your custom rom miss of a main feature so hardware video decoding,
i think without this it is not possible to play encrypted videos

You can provide more info such as a log by enabling Kodi debug, otherwise there are no details, and a screenshot of "DRM Info" app (from store) page infos, to get a more complete picture
but i do not think this can be solved from our part

**Comment by werimail** [comment] 2021-11-30 09:23
Ok CastagnaIT, thank you. I also think that it is related to the missing hardware decoding in the custom rom ... but I still created a Kodi debug log and the desired DRM info screenshot. Maybe there is still hope to solve the problem yourself.

![Screenshot_20211130-101828_DRM_Info](https://user-images.githubusercontent.com/88481706/144019995-7a03d1aa-2188-4a1a-88d6-cb2552147f74.png)

[kodi_debug.log](https://github.com/xbmc/inputstream.adaptive/files/7624502/kodi_debug.log)

**Comment by CastagnaIT** [comment] 2021-11-30 12:24
Your Widevine is set as L3 then in theory you can play SD content, but since your ROM is an unofficial custom rom other problems can happens beyond our control, like this:
From the log line `Failed to create Android MediaCodec` this can means that in your rom is missing some media type codec needed to the playback, then should to be fixed in rom side

the only thing that i can suggest to try is trying to play 480P content and see if works, if will works then at least you can play SD content (but suspect that same error will be raised due to codec)

to try this, if there is a setting in your video addon you should force the max video resolution to SD quality 480P,
and/or you can set it to InputStream Adaptive on:
settings->Max resolution secure decoder-> 480P

I don't think there are other solutions, you will have to wait until your rom will be improved in these areas

ref manifest: [manifest.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7625083/manifest.mpd.txt)

**Comment by werimail** [comment] 2021-11-30 12:47
I tried to play the content as you described with 480p in Kodi, unfortunately not with the desired success. So it is probably due to the missing media codec in the custom ROM. What amazes me is that playback (with max 480p) works with the native app. Apparently another codec is used for this which is supported by the custom ROM. Still thanks for the support. Greetings Weri

**Comment by werimail** [comment] 2021-12-06 09:11
Hi CastagnaIT, I tried the following: With the Media Codec Info tool from the App Store, I was able to display the codecs installed in the ROM. Accordingly, an MPEG-4 AVC (H.264) video codec is available. This is shown in the codec list as OMX.google.h264.decocder (see also the screenshots). Apparently there is a corresponding codec in the ROM ?!

![Screenshot_20211206-100524_Media_Codec_Info_video](https://user-images.githubusercontent.com/88481706/144818874-04addbd1-c1e7-41cc-9cf6-a942dd6d4349.png)
![Screenshot_20211206-100453_Media_Codec_Info](https://user-images.githubusercontent.com/88481706/144818894-6c864478-f634-4fd7-bded-4504b527cb2b.png)

Greetings Weri

**Comment by CastagnaIT** [comment] 2021-12-06 10:36
looking again at your last log comparing it with one of my own
i think the problem is somewhere in this part of code:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp#L664-L750

because after log line:
`CDVDVideoCodecAndroidMediaCodec::Open: Secure decoder requested: false (stream flags: 0)`
is missing the codec testing, in your case should appears like:
`CDVDVideoCodecAndroidMediaCodec::Open Testing codec: OMX.google.h264.decoder`
and then fails with:
`CDVDVideoCodecAndroidMediaCodec:: Failed to create Android MediaCodec`

one my theory of the cause is that `getCodecCount` not work anymore, because has been deprecated on API 21
i think it is more appropriate that you open an Issue on the Kodi repository adding a link on this page

**Comment by CastagnaIT** [comment] 2022-05-23 10:47
closed since the problem has been fixed on kodi core

**Closed as completed by CastagnaIT** 2022-05-23 10:47 UTC
Labels: Issue Type: Question, Resolution: External, Component: Video
