### ISSUE TITLE
ClearKey DRM support

### ISSUE THREAD

**Issue by fkoemep** [peak3d/inputstream.adaptive#1531] opened 2024-04-13 15:01 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

I have read comments since 2022 stating that ClearKey support is planned but it was never implemented, is there any more information about the development of this feature?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

ClearKey streams should be supported

## Actual Behavior

ClearKey streams are not supported

## Possible Fix

Implement compatibility with this DRM system

### To Reproduce

1. Try playing a ClearKey protected stream from a .m3u playlist file
2. The stream won't play
3. 

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
Extracted from https://reference.dashif.org/dash.js/v4.4.0/samples/drm/clearkey.html

https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p_ClearKey.mpd

"nrQFDeRLSAKTLifXUIPiZg": "FmY0xnWCPCNaSpRG-tUuTQ"

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] tvOS
 - [x] Linux
 - [x] OSX
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version:
 - inputstream.adaptive version:

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment] 2024-04-14 09:12
closed, there is no need to open a new Issue
duplicate of #811

**Closed as completed** 2024-04-14 09:12 UTC
Labels: Duplicate
