### ISSUE TITLE
Buffering/ Fast-Forwarding (re-syncing) with Marginal Internet Connection

### ISSUE THREAD

**Issue by kontell** [peak3d/inputstream.adaptive#973] opened 2022-05-10 14:54 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
The buffering behaviour is much improved with this release however it doesn't pause/ buffer gracefully when the network connection is inadequate. This isn't new behaviour for Kodi, I've seen it in V19. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Playback should pause with the buffer symbol on screen and playback should resume from previously paused location when the bufffer is created.

## Actual Behavior
When live streaming with a marginal internet connection the buffering behaviour is jittery. 

The video freezes - for a period of less than 1s to over a minute - and will then fast-forward to what seems to be live. Sometimes the audio will keep playing and the video will resync with the audio. The buffer circle symbol is not displayed when the video is frozen.

Other times the Kodi buffer symbol will show with a percentage and playback will alternate between playing/ buffering rapidly rather than a real buffer being created.

## Possible Fix

Choose a lower bitrate stream so the connection is no longer marginal and playback is fine.

### To Reproduce

1. Choose "Manual OSD" for stream selection type in Inputstream Adaptive settings.
2. Play live stream with a bitrate higher than the network connection can comfortably handle.

### Debuglog

The debuglog can be found here:
[kodi_2022-05-10.log](https://github.com/xbmc/inputstream.adaptive/files/8662291/kodi_2022-05-10.log)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
skysportnow.co.nz (subscription service, can provide login for testing).

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
Same/ similar problem:
https://forum.kodi.tv/showthread.php?tid=309627

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11 (Nvidia Shield 9.0.1)
 - Kodi version: 20.0-ALPHA1 (19.90.101) (2022-05-09)
 - inputstream.adaptive version: 20.2.0

**Comment by CastagnaIT** [comment] 2022-05-10 19:02
is a know problem and it's a much bigger problem this could could be improved for final Kodi 20
but part of the problem is also linked to Kodi core and in how buffering is managed in Kodi
that cause a kind of buffering concurrency
time is limited for a complete solution more likely we will have to wait future Kodi versions like 21

**Comment by CastagnaIT** [comment] 2022-05-10 19:05
i close the issue since we are already known of the problem

for reference the issue is already opened on xbmc repo
https://github.com/xbmc/xbmc/issues/20742

**Closed as completed by CastagnaIT** 2022-05-10 19:05 UTC

**Comment by glennguy** [comment] 2022-05-11 09:00
I have some thoughts on this, will leave a comment on the linked issue
