### ISSUE TITLE
HLS master playlist redirect edge case

### ISSUE THREAD

**Issue by glennguy** [peak3d/inputstream.adaptive#617] opened 2021-03-15 10:53 UTC
Problem scenario example:
A master m3u8 is requested from a url which 3xx redirects to another location. The resulting master m3u8 has an absolute uri within that is of the same domain as the master m3u8 before redirection. e.g:
* IA is given url `https://bit.ly/1234`
* This redirects to `https://baz.qux/master.m3u8`
* master.m3u8 contains a variant stream which is located at `https://bit.ly/abcd`
* IA incorrectly builds the download url for this stream as `https://baz.qux/abcd` when it should still be `https://bit.ly/abcd`
This is not an issue if the variant stream has a uri with a different domain name eg `https://link.to/abcd`

Thanks to @matthuisman for discovering this

**Comment by matthuisman** [comment] 2021-03-15 20:29
the issue is here:
https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/common/AdaptiveTree.cpp#L413

url = https://bit.ly/abcd
effective_url_ = https://baz.qux/
base_url_ =  https://bit.ly/

so, that check is returning true.
we do have effective url and bit.ly is in https://bit.ly/abcd
so it then replaces the length of base_url_ with that many characters from the start of effective_url_ 
which i think could also cause issues. if base_url is https://bit.ly/ and effective is https://baz.qux/ - then I think we would get https://bit.lyx/

A possible fix would be to make sure effective_url_ is cleared somewhere after doing all the master stuff
but then it may be needed later on?

**Comment by smf007** [comment] 2021-03-17 17:40
As it is an absolute URI, wouldn't that be a third condition, so a third conditional check should be used?

`url.compare(0, 7, "http://") != 0 && url.compare(0, 8, "https://") != 0`

**Comment by matthuisman** [comment] 2021-03-17 17:45
That was my first attempt. Ignore replacing with full ulrs. But that breaks some streams as IA earlier on generates full URLs that actually need replacing. There is no way to tell between an actual full URL from file or one that has been appended earlier on.

**Comment by smf007** [comment] 2021-03-17 17:56
Ah... that's the problem then.  Why was a full URL generated previously?  Perhaps that is either an error or structurally/process wise it should be occurring later, or alternatively this code is occurring too late.

**Comment by matthuisman** [comment] 2021-03-17 18:36
I think URLs without leading / are appended before this. 

That was my 2nd approach. Making sure all URLs are basically unaltered until this function. That way it could ignore full URLs. It worked and removed quite a bit of duplication, but broke something I think. Possibly just an oversight as I didn't spend too much time on it.

I may still have the initial work in my fork. Il check

**Comment by smf007** [comment] 2021-03-24 21:23
Running through the gtest case from pull #614, what I'm seeing is this:

url = https://bit.ly/abcd
effective_url_ = https://baz.qux/
base_url_ = https://bit.ly/

The issue is that for this case, effective_url_ should be blank.  So this issue is not https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/common/AdaptiveTree.cpp#L413 but occurring earlier when determining the effective_url.

**Comment by smf007** [comment] 2021-03-24 21:55
I see the gtest is actually setting effective_url_.

As to the note in the first post about variant streams and differing domains, this might be related to the seteffectiveurl routine checking effective_url against base_url.

**Comment by matthuisman** [comment] 2021-03-24 21:57
As per my earlier post

**"A possible fix would be to make sure effective_url_ is cleared somewhere after doing all the master stuff
but then it may be needed later on?"**

We need to either 
1) clear effective_url_ earlier if we know it's safe to do so
2) don't make any urls absolute urls before this function so then we can detect if an actual absolute url was used in the file and therefore not replace with the redirect url

Again, I go back to my original PR (for redirect fix) were I argued there is no point tracking the Original URL and the redirected url.
everything would be easier if we just updated the url / base domain etc to the redirected url straight away after the redirect.
Why do we need to know the original url??

If I remember, peak said we need to track both urls due to the MediaRenewal stuff
https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/main.cpp#L362

**Comment by smf007** [comment] 2021-03-24 22:10
Effective_URL is used in other cases.  My question is, should the gtest be setting the effective URL?
`effectiveUrl = "https://baz.qux/master.m3u8";`
I'm not sure the test matches the intended case.

**Comment by smf007** [comment] 2021-03-24 22:13
Is this case represented in one of the cases at the following?
https://github.com/matthuisman/ia_tests

**Comment by matthuisman** [comment] 2021-03-24 22:19
~~oh, maybe the test actually should be setting effectiveUrl  to "https://baz.qux/"~~
~~confusing name, as it's actually the effectiveBaseUrl~~

UPDATE:
Actually, in the test he's setting effectiveUrl (not effective_url_)
You will see this is used here: https://github.com/glennguy/inputstream.adaptive/blob/new-tests/src/test/TestHelper.cpp#L32
which will then be passed to SetEffectiveURL and then effective_url_ will become"https://baz.qux/"

So, the tests are correct, was just a bit confused by how they were working.
effectiveUrl is simulating the 302 Location url from a redirect that is then passed SetEffectiveURL 
Which is great - it's also testing SetEffectiveURL (not setting effective_url_ directly)

And yes, here is a test stream:
https://github.com/matthuisman/ia_tests/blob/master/hls_redirected_sub/hls_redirected.strm
(this issue is if the sub playlist urls use the same domain as the redirected master playlist)

**Comment by smf007** [comment] 2021-03-25 00:47
If the equivalent test stream for this case is:
https://github.com/matthuisman/ia_tests/blob/master/hls_redirected_sub/hls_redirected.strm
That plays for me.

**Comment by matthuisman** [comment] 2021-03-25 00:53
are you sure its playing using Inputstream Adapitve and not ffmpeg?
and using Kodi 19? Kodi 18 IA (2.4.6) doesn't have the big effective url changes (https://github.com/xbmc/inputstream.adaptive/commit/3b84fef7143a080e42f844b3631c61864f23438e)

**Comment by smf007** [comment] 2021-03-25 01:03
Well I feel stupid.  I had a Leia copy of addon.xml in the folder so IA was actually failing to load when using Kodi master.

**Comment by smf007** [comment] 2021-03-25 01:25
That case also fails in Leia, so 3b84fef doesn't impact it.

**Comment by matthuisman** [comment] 2021-03-25 01:33
that stream works for for me in Leia 2.4.6.

https://github.com/xbmc/inputstream.adaptive/commit/3b84fef7143a080e42f844b3631c61864f23438e is in Leia branch but was never released in a version..

https://github.com/xbmc/inputstream.adaptive/commits/Leia
Last 6x commits there were never released.

Maybe your using a Leia build from the head of that branch... which is why it wont work

**Comment by smf007** [comment] 2021-03-25 04:08
The following works but is a hack.  Change 
https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/common/AdaptiveTree.cpp#L413
to
`else if (!effective_url_.empty() && url.compare(0, base_url_.size(), base_url_) == 0 && url.find(".m3u8") != url.npos)`

Which leads me to believe that the ELSE at
https://github.com/xbmc/inputstream.adaptive/blob/Matrix/src/parser/HLSTree.cpp#L321
should include the following action:
`effective_url_.clear();`

**Comment by glennguy** [comment] 2021-03-25 04:44
Sorry just seeing all this now - yes Matt that's right I've allowed for the tests to simulate a redirect happening. From memory I don't think there was any other way to do it that would have allowed for meaningful tests around this issue.

**Comment by matthuisman** [comment] 2021-03-25 04:48
Its really good. I like it. Just mocking the download function. Good move!

**Comment by glennguy** [comment] 2021-03-25 05:02
Thanks, but credit for a lot of it still goes to peak3d, I just adapted that function to suit :)

**Closed as completed** 2021-05-17 10:01 UTC
