### ISSUE TITLE
Netflix not play vídeo retorpie/kodi (widevine replace works!)

### ISSUE THREAD

**Issue by Mikaele** [peak3d/inputstream.adaptive#682] opened 2021-05-12 22:06 UTC
Last week update my widevine on netflix-addon (only kodi on RPI), unfortunly netflix and simple-client stop working..  yesterday i installed retropie +Kodi-LEIA and netflix-addon, didn't work

Today replaced my  /.kodi/cdm/libwidevinecdm.so  for this [version](http://archive.raspberrypi.org/debian/pool/main/w/widevine/widevine_4.10.1679.0.orig.tar.xz) 

SOLUTION

(on Windows) Get the .tar unzip on  ./ of sd-card, folder struct  will look like:
 
```
|- ./
|--> overlays
|---> widevine
|---->opt
|----->WidevineCdm
|------>_platform_specific
|------->linux_arm
|--------> libwidevinecdm.so
```
Now  on RPI  console run

`cp /boot/widevine/opt/WidevineCdm/_platform_specific/linux_arm/libwidevinecdm.so ~/.kodi/cdm/
`
After  run
`sudo apt install libnss3`

Finaly work
Sorry my poor english

thanks [#1154](https://github.com/CastagnaIT/plugin.video.netflix/issues/1154)

**Comment by matthuisman** [comment] 2021-05-12 22:11
duplicate of https://github.com/xbmc/inputstream.adaptive/issues/678
please close

**Closed as completed** 2021-05-12 22:21 UTC
