### ISSUE TITLE
Inputstream Adaptive plays the first chapter instead of live in a live stream

### ISSUE THREAD

**Issue by joaopa00** [peak3d/inputstream.adaptive#1066] opened 2022-11-02 02:26 UTC
### Describe the bug
Trying to play the live of the french channel TF1,  stream lasts about 4 hours and has several chapters. Usually, the live is not the beginning of the file, but the end.
So, stream is 4 hours behind live.

## Expected Behavior
Inputstream plays the current live, not 4 hours behind.

## Actual Behavior

Stream is always about 4 hours behind live.

## Possible Fix
Sorry, I don't know how to fix that. As a workaround, one can move the cursor at the end of the stream to have the live actually.

### To Reproduce
1. Live is available here: https://www.tf1.fr/tf1/direct. Be careful, stream is France geoblocked. And you need a free subsciption to watch the live from the site.
2. Here is a python code to adapt to check by yourself what happens (still geoblocked, but no needed subscription)
```python
from __future__ import unicode_literals
from builtins import str
import json

import inputstreamhelper
from codequick import Route, Resolver, Listitem, Script

import inputstreamhelper
import inputstream
from kodi_six import xbmcgui, xbmcplugin
import urlquick

URL_VIDEO_STREAM = 'https://mediainfo.tf1.fr/mediainfocombo/L_TF1?context=MYTF1&pver=5000002&platform=web&device=desktop&os=linux&osVersion=unknown&topDomain=www.tf1.fr'

URL_LICENCE_KEY = 'https://drm-wide.tf1.fr/proxy?id=L_TF1|Content-Type=&User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3041.0 Safari/537.36&Host=drm-wide.tf1.fr|R{SSM}|'

json_parser = urlquick.get( URL_VIDEO_STREAM, GENERIC_HEADERS, max_age=-1).json()

item = Listitem()
item.path = json_parser['delivery']['url']
item.label = get_selected_item_label()
item.art.update(get_selected_item_art())
item.info.update(get_selected_item_info())
item.property[inputstream] = 'inputstream.adaptive'
item.property['inputstream.adaptive.manifest_type'] = 'mpd'
item.property['inputstream.adaptive.license_type'] = 'com.widevine.alpha'
item.property['inputstream.adaptive.license_key'] = URL_LICENCE_KEY

return item
```

### Debuglog
The debuglog can be found here:

[LOG.TXT](https://github.com/xbmc/inputstream.adaptive/files/9915410/LOG.TXT)

### MPD/M3U8s/ISM
An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
[index.mpd.zip](https://github.com/xbmc/inputstream.adaptive/files/9915386/index.mpd.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.alpha2
 - inputstream.adaptive version:20.2.0
 I tested with the 20.3.1 version with the same result.

**Comment by glennguy** [comment] 2022-11-02 12:48
Same as #574. @joaopa00 I suggest for now you do a workaround similar to how Matt Huisman does

**Comment by joaopa00** [comment] 2022-11-02 16:07
As added this in my code, but that doe not work.
Did I do anything wrong?
`item.property["inputstream.adaptive.ResumeTime"] = '43200'
 item.property["inputstream.adaptive.TotalTime"] = 1`

**Comment by joaopa00** [comment] 2022-11-02 23:20
OK, I found what it is:
`item.property["ResumeTime"] = '43200'
 item.property["TotalTime"] = '1'

Thank you for your support.

**Comment by matthuisman** [comment] 2023-02-27 22:54
@glennguy we should mark this as a duplicate of 574 and then close this
574 should also soon be fixed with tmm1 changes

**Comment by CastagnaIT** [comment] 2024-04-06 10:49
if you are still around here please do a test with this new test build for kodi 21:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1518/7/artifacts

note that ISA there is a timeshift limited to 2 hours (anyway can be configured by property)

PS: i tried test by myself with VPN but dont work, always return permission denied

**Closed as completed** 2024-04-09 08:28 UTC
Labels: Component: MPEG-DASH
