### ISSUE TITLE
No sound when playing AAC audio from MPEG-DASH stream

### ISSUE THREAD

**Issue by cfbaua** [peak3d/inputstream.adaptive#1355] opened 2023-08-04 02:14 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
When I try to play the following MPEG-DASH stream in Kodi, there is no sound: https://d3cglye48cl6m2.cloudfront.net/out/v1/563ec3e9487340528616d736e1202232/index.mpd. The stream plays fine in VLC and other media players, so I believe the issue is with Kodi's AAC audio support.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
You should see video and hear sound

## Actual Behavior
Only video is seen, there is no audio

## Possible Fix

I do not know how to fix this.

### To Reproduce

1. play the link: https://d3cglye48cl6m2.cloudfront.net/out/v1/563ec3e9487340528616d736e1202232/index.mpd
2.
3.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/biyuzamema

### Screenshots 
Here are some links or screenshots to help explain the problem:

I have no screenshots, the problem is with audio.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux (OSMC, the latest version for the Vero 4K+)
 - [ ] macOS
 - [x] Windows 10
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by cfbaua** [comment] 2023-08-08 12:41
I updated my submission, I hope this helps.

**Comment by CastagnaIT** [comment] 2023-08-12 14:24
i have transferred the issue to https://github.com/xbmc/inputstream.adaptive repo
since the problem seem to be due to unimplemented features on this component

at first sight seem the problem is due to unhandled `presentationTimeOffset` offset value
somewhat similar to #1317

[manifest_1691849714.txt](https://github.com/xbmc/inputstream.adaptive/files/12327536/manifest_1691849714.txt)

**Comment by CastagnaIT** [comment] 2024-05-27 15:34
fixed on Kodi 21

**Closed as completed by CastagnaIT** 2024-05-27 15:34 UTC
Labels: Resolution: Fixed, Triage: Confirmed
