### ISSUE TITLE
Dolby Vision streams no longer trigger Dolby Vision mode on TV

### ISSUE THREAD

**Issue by MauriceW67** [peak3d/inputstream.adaptive#968] opened 2022-05-08 10:44 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Since version 20.2.0 playing a Dolby Vision stream in an addon no longer triggers Dolby Vision mode on the TV.
This happens with all three addons I tried (Netflix, Disney+ and HBO Max).
With version 20.1.2 this was working as it should.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Dolby Vision mode triggered on the TV when playing a Dolby Vision stream.

## Actual Behavior

Dolby Vision mode is not triggered. You can tell the Dolby Vision stream is being played, because the colors have the famous purple and green tints.

### To Reproduce

1. Start Netflix addon from Kodi
2. Choose an episode of a show that has Dolby Vision (I used Altered Carbon Season 1)
3. Play the episode

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ucarucakon.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

Not sure how to get the manifest file from the Netflix addon?

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield Experience 9.0.2 (Android TV 11)
 - Kodi version: kodi-20220507-74574af3-master-22690-arm64-v8a
 - inputstream.adaptive version: Nexus-9b88f0c (https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Nexus/114/artifacts)

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Ronny-nerd** [comment] 2022-05-09 08:00
Hardware:
Nvidia Shield TV 2019 Pro
LG OLED55B7D

Can confirm it, have the same problems with Dolby Vision streams via the Netflix and Disney+ addon.

**Comment by Ronny-nerd** [comment] 2022-05-13 10:18
Hello @glennguy ...are there already new findings that go again in the direction of output Dolby Vision icon on the TV device...as it was the case before?

**Comment by glennguy** [comment] 2022-05-13 10:34
We don't really know what is causing this. It's hard to test because neither myself or @CastagnaIT have a DV capable device. I have a laptop with a HDR screen and HDR activates on a test stream.

Next step is to make some IA builds from a few different points in history over the last couple of months that are compatible with latest Kodi nightly.
Would you be happy to help test?

**Comment by glennguy** [comment] 2022-05-13 11:03
@Ronny-nerd @MauriceW67 some test builds here to try if you have time.

Nothing new in these, just rolling back changes since 20.1.2.
Test 1 is practically the same code as the old 20.1.2, I'm hoping this will play fine
Tests 2 and 3 have more incremental changes. If they all work then I'll produce more builds with further changes, if not then we can start to narrow down where the issue is.

For Nvidia shield you'll want the aarch64 zips.

Please turn off automatic updates for inputstream.adaptive while you're testing, just to make sure it doesn't auto update.

~~Test 1: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-977/1/artifacts~~

~~Test 2: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-978/1/artifacts~~

~~Test 3: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-979/1/artifacts~~

Test 1: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-977/4/artifacts

Test 2: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-978/4/artifacts

Test 3: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-979/4/artifacts

Test 4: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-982/1/artifacts

Test 5: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-983/1/artifacts


Thanks!

**Comment by Ronny-nerd** [comment] 2022-05-13 13:31
Downloaded the IA files ...no matter if test 1 - 3 ...if I start a stream via the Netflix or Disney+ addon ...then you fly out of Kodi.

**Comment by MauriceW67** [comment] 2022-05-13 14:31
@glennguy I didn't test yet, but could the crashes that @Ronny-nerd is experiencing be caused by the H.265 streams crash issue, which was fixed in https://github.com/xbmc/inputstream.adaptive/pull/970 ?

Not sure if that PR is present in the test builds?

EDIT: I just tried all three test builds, but they all make Kodi crash as Ronny already mentioned.

**Comment by glennguy** [comment] 2022-05-13 22:18
My apologies, I I forget how git works sometimes and also stuffed up the commit on top which was causing the crash!  I've redone each and updated the links in the post above, please try again. @MauriceW67 thanks for the tip, the hevc fix commit is on top of test 2 and 3 (not applicable for 1).

**Comment by MauriceW67** [comment] 2022-05-13 23:59
@glennguy Thanks for the new test builds.

The results are that Kodi longer crashes with any of these builds. I tested playing a DV movie from HBO Max and a DV episode from Netflix.

Test 1 and 2 make my TV switch to Dolby Vision mode, but test 3 does not (it shows the purple/green colors again).

One other thing I noticed is that Kodi crashes back to the home screen of my Shield when switching from the HBO Max addon to the Netflix addon without closing Kodi first. Not sure if that is caused by these test builds or something else though.

**Comment by glennguy** [comment] 2022-05-14 03:45
@MauriceW67 awesome, this is making our lives a lot easier

Could you also try test 4/5 in the post above, and reconfirm that test 2 works fine?

Thanks!

**Comment by CastagnaIT** [comment] 2022-05-14 07:19
> One other thing I noticed is that Kodi crashes back to the home screen of my Shield when switching from the HBO Max addon to the Netflix addon without closing Kodi first. Not sure if that is caused by these test builds or something else though.

this is a know python bug, there is an already opened issue in xbmc
EDIT: just heard that it will be fixed soon with next python 3.9.13

**Comment by MauriceW67** [comment] 2022-05-14 09:17
@glennguy New test results:

Test 2: Reconfirmed, working properly with Dolby Vision
Test 4: Does not work (purple & green colors)
Test 5: Does not work (purple & green colors)

**Comment by CastagnaIT** [comment] 2022-05-14 09:43
@glennguy on top of test 5 revert you should add the fixes:
ec32d47fb26611419ed6a1bcd4d3affd82ce8b51
d880344f438ed7fcf8f71a89afea28bf052d3020
to fix regressions already fixed

**Comment by Ronny-nerd** [comment] 2022-05-14 10:00
Test 1. Dolby Vision Icon = OK - Colours = OK

Amazon VOD Addon
Settings
General
If use H.265 video codec = activated = OK


Test 2. Dolby Vision Icon = OK - Colours = OK

Amazon VOD Addon
Settings
General
If Use H.265 Video Codec = Enabled = OK


Test 3. Dolby Vision Icon = Not OK - Colours = Not OK

Amazon VOD Addon
Settings
General
If Use H.265 Video Codec = Enabled = Not OK


Test 4. Dolby Vision Icon = Not OK - Colours = Not OK

Amazon VOD Addon
Settings
General
If Use H.265 Video Codec = Enabled = Not OK


Test 5. Dolby Vision Icon = Not OK - Colours = Not OK

Amazon VOD Addon
Settings
General
If Use H.265 Video Codec = Enabled = Not OK


Translated with www.DeepL.com/Translator (free version)

**Comment by Ronny-nerd** [comment] 2022-05-15 08:48
https://github.com/xbmc/inputstream.adaptive/pull/984

Thank you glennguy...the Dolby Vision problem has been fixed by you in the new IA version 20.2.0.

Vision icon = OK - colours = OK

Amazon VOD Addon
Settings
General
If use H.265 video codec = enabled = OK

**Closed as completed** 2022-05-15 08:57 UTC
