### ISSUE TITLE
Create 2.0.x release

### ISSUE THREAD

**Issue by candrews** [peak3d/inputstream.adaptive#121] opened 2018-02-13 03:58 UTC
Can you please create a tag / release of 2.0.x (so we have a more recent Krypton release)? It looks like the latest version is 2.0.19 https://github.com/peak3d/inputstream.adaptive/commit/9af21218a87572bd4ab8d8d660c11f6295144f97 but the release hasn't been made.

Thanks!

**Comment by X-dark** [comment] 2018-03-05 16:53
Duplicate of #54

**Comment by peak3d** [comment] 2018-03-09 16:08
Can you use the branch Krypton instead the Tag?
I created the Krypton branch because there was some backporting done.

**Closed** 2018-06-05 14:54 UTC
