### ISSUE TITLE
Frame dropping playing 1080p (Netflix, Disney)

### ISSUE THREAD

**Issue by facakente** [peak3d/inputstream.adaptive#460] opened 2020-06-05 21:39 UTC
Every time I play 1080p in kodi in my firestick 4K , I get regularly frames dropping / stuttering , image is not fluid at all.

It happens only with Netflix and Disney , tested other addons and play fine.

On the other hand when playing hdr10 or DV it does play fine , no frame dropping .(Disney or Netflix)

https://paste.kodi.tv/pucovakeko

Played 2 movies in hd , frames drop , then played one movie in DV , no problems .

I suppose problem isn’t the build but the new IA I have installed to fix other problems I had with Netflix or Disney .

**Comment by facakente** [comment] 2020-06-06 08:56
@peak3d maybe u can help here

**Comment by peak3d** [comment] 2020-06-06 09:19
From log you play a 4K stream:

> CDVDVideoCodecAndroidMediaCodec:: width(3840), height(2160), stride(0), slice-height(0), color-format(0)

With 4K streams on your device you are a little bit on the limit what the device can do.
Only tunneled playback can probably solve the issues, but this is not (yet) implemented in kodi

**Comment by peak3d** [comment] 2020-06-06 09:36
Ok, found your HD streams, but there is nothing obvious in log.
Because IA is not doing any timing (it just provides the data to kodi) it is very unlikely that IA is the reason.
Pls. file a github issue in the kodi github repo, after trying to playback with "Sync playback to display" in settings::player On.

**Comment by facakente** [comment] 2020-06-06 11:06
Ok will do , but I have already tested sync playback to display on , also the video only in IA settings but none of them resolve the issue , still having this problem. You mentioned the device is on limit when playing a 4K stream , though i had no problems with 4K streams.

**Comment by peak3d** [comment] 2020-06-06 13:01
I revised my first post from today.

1.) From where do you know that frames are dropped?
2.) Whats the title of the D+ stream?

**Comment by facakente** [comment] 2020-06-06 13:07
Dev mode in the firestick , though was just to confirm , as visually I can see that image is not fluid .

Tried inside out and toy story 4 , both hd, but happens with any tested until now . 

Just finished to try on matrix and old 18.6 leia stable and the same happens.

**Comment by peak3d** [comment] 2020-06-06 13:12
Dev mode == "O" overlay in kodi? Or do you mean AFTV dev tool ?

**Comment by facakente** [comment] 2020-06-06 13:28
I mean the firestick dev tool .

**Comment by Uukrull** [comment] 2020-06-06 15:48
This was already discussed here:

https://github.com/CastagnaIT/plugin.video.netflix/issues/197

**Comment by facakente** [comment] 2020-06-06 16:09
Yes and after checking that issue and disabling frame rate in Firestick settings resolved the frame dropping issue.

**Comment by facakente** [comment] 2020-06-06 16:42
However after this change just noticed now that I am unable to whitelist 24p resolutions , they disappeared once I have deactivated frame matching. 

Strange I am almost sure when I deactivated for first time to test hd streams it was played in 1080 /24 , currently I just can play in 60p.

**Comment by facakente** [comment] 2020-06-06 18:07
yes in order to get all whitelists modes I need to set frame rate on in the Firestick settings.

**Comment by peak3d** [comment] 2020-06-06 18:28
I tried with my AFTV 4K stick:

- Set frame rate on in amazon settings.
- Start kodi, set 4K@23.94 in settings::system
- Disable refresh rate switching in kodi (should not be necessary for this test)
- Play: https://drive.google.com/file/d/0BwxFVkl63-lERkJRU003ZTd2VEk/view?usp=sharing from our kodi samples page.
- have x-ray on and extendened information

It's a 1080p stream which plays at 23.94fps. There is no single frame drop for me.
Can you please play this stream, and avoid refreshrate switching by setting kodi as mentioned above to 23.94hz ?

**Comment by facakente** [comment] 2020-06-06 19:35
i have followed your steps and that way i do not have a single frame drop, though i do not have a single drop either with refresh rate on start/stop.

that's why i think problem is related specifically with IA that netflix and disney uses.


As only with these 2 addons i experience this kind of issue.

I will now try your steps playing one of those hd streams.

**Comment by facakente** [comment] 2020-06-06 19:44
so playing your video no frames dropping, playing any disney or netflix video, i have frames dropping.

Do you want a log where i can play your video and one hd stream?

**Comment by facakente** [comment] 2020-06-06 19:53
https://paste.kodi.tv/difuzucini

first played hd stream, inside out

later your video, just dropped 4 frames after i have move forwarded a couple of min

**Comment by peak3d** [comment] 2020-06-06 20:02
yes, can reproduce here

**Comment by peak3d** [comment] 2020-06-06 20:14
Ok, solution for Disney is to disable the secure avc decoder, seems that it doesn't work properly.
Currently IA has no sign if the stream needs a secure decoder, but it can be controlled in the addon.

@matthuisman can maybe tell more about the options in Disney+ addon, and @CastagnaIT for Netflix.

Edit: Seems that only HD plays without secure decoder, so 1080p requires it. For me it seems that the secure AVC decoder has some performance issues, the HEVC decoder not.

**Comment by matthuisman** [comment] 2020-06-06 20:33
Disney is limited to 720 without secure decoder. 

With secure decoder does enabling h265 in settings help? Most android devices should support h265?
Pretty sure I enable that by default.

And correct, looks like hls has no way to identify if secure decoder is needed.

**Comment by facakente** [comment] 2020-06-06 20:36
The only way to fix this for Disney is to disable l1 widevine, otherwise there is the issue.

For Netflix there isn’t any workaround so far.

**Comment by peak3d** [comment] 2020-06-06 21:24
Yes, sorry, nothing I can change - file a bug report on amazon, below the content of a test strm file where you comment out line 6 (##) to use the unsecure decoder, or leave it as it is to use the secure decoder.

There is nothing different in kodi, only the usage of the secure decoder or not.

```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://proxy.uat.widevine.com/proxy?video_id=d286538032258a1c&provider=widevine_test||R{SSM}|
#KODIPROP:inputstream.adaptive.license_flags=force_secure_decoder
https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd

```

**Comment by matthuisman** [comment] 2020-06-06 21:32
@CastagnaIT  could add a setting to Netflix to enable / disable secure decoder?

I think Netflix generates a MPD for playback.
So, if secure decoder is off, could remove robustness_level from mpd and drop the quality?

Here is where L1 secure decoder is enabled:
https://github.com/CastagnaIT/plugin.video.netflix/blob/fa481f08071308abcd1758dab4edaa83f8f4f002/resources/lib/services/msl/converter.py#L110

I suspect those resolutions won't play without that, so maybe you can just SKIP them if Secure Decoder is turned off in settings?

@facakente
does enabling H265 not make a difference?
I thought that would then use the HEVC decoder even for 1080

**Comment by facakente** [comment] 2020-06-06 22:02
No , only way to fix it is to disable L1. I played with all options but problems persists.

**Comment by matthuisman** [comment] 2020-06-06 22:11
And just a FireTV issue right?
Fine on Shield / other android?

**Comment by peak3d** [comment] 2020-06-06 22:14
At least on shield this issue does not exist

**Comment by fritsch** [comment] 2020-06-07 05:58
When I read multiple replies. Wasn't it working when you switch the refresh rate before kodi is starting the video?

Could it be that the secure decoder somehow does not know about the fps? If it got the above right?

**Comment by peak3d** [comment] 2020-06-07 07:11
Nope, I tried this @fritsch but no difference. Also opening gui overlay as some mentioned doesn't solve it

**Comment by matthuisman** [comment] 2020-06-07 07:18
Has anyone tried a build without the jni commit just out of interest? I know that commit is here to stay but would just be interested to see if it works. If so, we know its possible?

http://mirrors.kodi.tv/test-builds/android/arm/kodi-20200521-6e4c8210-revertjnileia-armeabi-v7a.apk

**Comment by peak3d** [comment] 2020-06-07 07:23
This issue was present already with 18.6 / ndk

**Comment by matthuisman** [comment] 2020-06-07 07:24
Oh OK. Sorry. I thought it was newer!

**Comment by CastagnaIT** [comment] 2020-06-07 07:33
hi,
i read all discussion now

@facakente can you say the name of settings you try to disable? (just for understand)
> Yes and after checking that issue and disabling frame rate in Firestick settings resolved the frame dropping issue.

@facakente 
have you tried to remove the "HW_SECURE_CODECS_REQUIRED" text to this line?
https://github.com/CastagnaIT/plugin.video.netflix/blob/fa481f08071308abcd1758dab4edaa83f8f4f002/resources/lib/services/msl/converter.py#L113
this disable securedecoder

start to become a bit too many options to add for devices that don't work well and this is confusing for me and also for users, first i want to understand the possible solutions if any

**Comment by facakente** [comment] 2020-06-07 08:33
@CastagnaIT in Netflix in UI I didn’t see any option that could impact hd streams , I have disabled hdr profiles , nothing else.

Regarding the code line you mentioned, no i did not test it , i am not familiar with it , so if someone can remove that line and send me the link to test it , I am happy to do it.

**Comment by CastagnaIT** [comment] 2020-06-07 08:38
There
[plugin.video.netflix_1.4.0_20200607_k18.zip](https://github.com/peak3d/inputstream.adaptive/files/4741593/plugin.video.netflix_1.4.0_20200607_k18.zip)

**Comment by peak3d** [comment] 2020-06-07 08:43
@CastagnaIT from what I can tell you don't have to do anything here. FHD streams need the secure decoder, and removing the flag lead to non-playback. Only SD (and for Disney HD) streams are working. Much easier workaround for @facakente is use the 3 refreshrates which are provided by default from his device (60 / 59.9 / 50) and be happy that a 30 EUR device works so nice.

Or - file an issue report on Amazon.

**Comment by CastagnaIT** [comment] 2020-06-07 08:51
well, so the problem is only on 24 fps?

I was thinking about buying this device
but if have this problem, i prefer to continue using my fat HTPC...

**Comment by facakente** [comment] 2020-06-07 08:54
if playing with this last change, stream does not even start, keeps loading but i can see that time is moving forward.

**Comment by CastagnaIT** [comment] 2020-06-07 08:55
yes as Peak3d explain this is not a solution usable with your L1 device then cause break of playback..

**Comment by facakente** [comment] 2020-06-07 08:58
ok i see, didnt see comment above.

Yep i see we need to deal with this limitation, not sure if amazon will do anything here.

Anyway thanks for the help guys.

At least hdr streams work fine.

Indeed for 30£ i must say this is a very good device.

**Comment by peak3d** [comment] 2020-06-07 09:07
@CastagnaIT the device plays the content nice on 59.9hz. You don't do anything wrong trying this device, really.

**Comment by mano3m** [comment] 2020-07-05 20:33
I can confirm using an overlay like CTRL+SHIFT+O completely fixes the stutters with 1080p streams on my fire TV 4k. What does Kod do differently with an overlay on screen?

**Comment by dagwieers** [comment] 2020-07-05 23:07
@mano3m What do you mean with overlay? 

I have a feeling this relates to a problem I reported a year ago: https://github.com/xbmc/xbmc/issues/16299

**Comment by CastagnaIT** [comment] 2020-07-06 06:24
he means "overlay" tha graphics over the video images (like Coded info, by press key O)

some year ago similar issue was on windows when playing videos in DXVA in hardware decoding,
and has been fixed by fernetmenta or afedchin i do not remember
perhaps was this PR: https://github.com/xbmc/xbmc/pull/11301
or some PR with refactor/rework

**Comment by peak3d** [comment] 2020-07-06 06:37
> I can confirm using an overlay like CTRL+SHIFT+O completely fixes the stutters with 1080p streams on my fire TV 4k. What does Kod do differently with an overlay on screen?

Beside the fact that I cannot confirm (stutter even with overlay), the question is more what surfaceflinger is doing different if it composes gui and video frame.

**Comment by mano3m** [comment] 2020-10-17 16:11
Any update on this one? I can confirm an overlay doesn't always help. It does always make it a lot better.

**Comment by wsnipex** [comment] 2020-10-25 09:11
Would it be possible to allow the addon to disable refresh rate switching in kodi? That could be a viable workaround for netflix.
Or some way to force hevc profiles?
btw, how can I verify that hevc profiles work without a 4k TV?

**Comment by mano3m** [comment] 2020-10-25 09:17
Obviously you can disable that in Kodi setting. It however defies the
purpose for me of using Kodi over the normal Netflix app, which lacks the
ability to do refresh rate switching... Watching a 24p video at 60hz
refresh rate on my 100ft projection screen is unbearable for me...

Op zo 25 okt. 2020 10:11 schreef Wolfgang Schupp <notifications@github.com>:

**Comment by CastagnaIT** [comment] 2020-10-25 10:22
> Would it be possible to allow the addon to disable refresh rate switching in kodi? 

this is not an appropriate option
not all videos are available in HEVC, some videos might have different refresh rate and not all devices support HEVC decoding

and would increase the complexity of configuring the addon that i want to avoid,
filling the add-on with dedicated options for individual devices only is not acceptable
already now in some cases users make a lot of confusion

> Or some way to force hevc profiles?
> btw, how can I verify that hevc profiles work without a 4k TV?

you can try in this way:
- in NF expert settings, enable HEVC
- in NF expert settings, enable Debug loggin level to Verbose
- after previous point, in NF expert settings, enable "Always show codec information..."
- Play a video that have a skin media-info flag set as: [ H.265 ] or [4K]

if your device not support hevc decoding the screen will be shown black or else kodi will stay in loading loop,
if a video works/played you have to check if the video codec is hevc, so in the codec info window shown, see "Video decoder" should say HEVC

**Comment by CastagnaIT** [comment] 2020-10-25 10:35
i forgot, if your android device/TV not support HDCP >= 2.2 the media-info flag [ H.265 ] or [4K] are not shown

I suggest you to install the add-on also on a personal computer (on a PC the 4K/HEVC flag are shown)
then find a video that have these flags, and play the title on your android device

**Comment by wsnipex** [comment] 2020-11-01 09:30
I tried, but couldn't find any hevc stream, so I just went with this workaround:
https://github.com/wsnipex/xbmc/commit/5a1c96fcaa466ffd729d39deec43f9101fae7758

build is available for anyone interested: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20201031-5a1c96fc-matrix-wsnipex-aftv4k-armeabi-v7a.apk

**Comment by hunterzero99** [comment] 2020-12-15 15:05
I'm hitting this bug, too.  I get dropped frames, and visible stuttering with the Netflix plugin on a Fire Stick 4k when using framerate matching.  I have the stutter with 1080p and 4K Dolby Vision files as well (not sure why some others don't seem to).  

It is resolved when I turn on Sync Playback to Display, but then I lose passthrough audio.
It is resolved when I disable framerate matching and manually set the frame rate to 60fps.
It is **not** resolved when I disable framerate matching and manually set the frame rate before starting playback.
It is **not** resolved when a menu is on the screen.

I'm currently testing on The Queens Gambit episode 3, starting at 23 minutes.  It is much more visible during high motion scenes, so either full motion/panning, or scenes with ton's of cuts (the opening sequence of Star vs. the Forces of Evil on Disney+ drops a ton of frames).

If there are any logs or additional information I can provide let me know.  I have root access on the device if it makes any difference.

**Comment by matthuisman** [comment] 2020-12-16 20:07
Someone posted on Disney+ thread that they solved 23.976 stutter by doing
> at the end i solved using matrix beta 2 and using 3:2 pulldown refresh rate instead of using 1:1

**Comment by hunterzero99** [comment] 2020-12-16 20:37
a 3:2 pulldown refresh rate effectively bypasses refresh rate switching.
The purpose of switching to a native rate is to bypass the 3:2 pulldown.

**Comment by matthuisman** [comment] 2020-12-16 22:22
Did notice a possible framerate issue with some MPDs
But this won't affect Disney as Disney uses HLS

I have a PR for what I think is a suitable fix here:
https://github.com/peak3d/inputstream.adaptive/pull/575

**Comment by MaccyGit** [comment] 2020-12-17 05:06
I have the new Firestick Lite with Fire OS 7.2.2.8 and Kodi 19 beta 2 (upgraded from latest Kodi 18 stable due to this issue) and stuttering is happening in Netflix with 1080p24hz streams but NOT in Disney+. Both switch to 24hz correctly (info from TV OSD). Firestick directly connected to TV.

In my case opening the OSD will fix the issue (or at least it will improve it by 99% because in the first 2 minutes of Stranger Things S3E1 I couldn't detect any visible stuttering).

Thanks in advance

**Comment by hunterzero99** [comment] 2020-12-17 13:09
> I have the new Firestick Lite with Fire OS 7.2.2.8 and Kodi 19 beta 2 (upgraded from latest Kodi 18 stable due to this issue) and stuttering is happening in Netflix with 1080p24hz streams but NOT in Disney+. Both switch to 24hz correctly (info from TV OSD). Firestick directly connected to TV.
> 
> In my case opening the OSD will fix the issue (or at least it will improve it by 99% because in the first 2 minutes of Stranger Things S3E1 I couldn't detect any visible stuttering).
> 
> Thanks in advance

This sounds like that might be fixed by the PR that matthuisman submitted.  Can you try manually selecting a playback framerate of 23.97 in Kodi?

**Comment by MaccyGit** [comment] 2020-12-17 18:18
> > I have the new Firestick Lite with Fire OS 7.2.2.8 and Kodi 19 beta 2 (upgraded from latest Kodi 18 stable due to this issue) and stuttering is happening in Netflix with 1080p24hz streams but NOT in Disney+. Both switch to 24hz correctly (info from TV OSD). Firestick directly connected to TV.
> > In my case opening the OSD will fix the issue (or at least it will improve it by 99% because in the first 2 minutes of Stranger Things S3E1 I couldn't detect any visible stuttering).
> > Thanks in advance
> 
> This sounds like that might be fixed by the PR that matthuisman submitted. Can you try manually selecting a playback framerate of 23.97 in Kodi?

I've set Kodi interface to @23.98, disabling auto change frame rate and it won't help. And it still improves dramatically enabling the OSD during playback

**Comment by matthuisman** [comment] 2020-12-17 22:45
anyone tried forcing it to 24fps and see if better?

advancedsettings.xml
```<advancedsettings>
    <video>
        <adjustrefreshrate>
            <override>
                <fpsmin>23.97</fpsmin>
                 <fpsmax>24</fpsmax>
                 <refresh>24</refresh>
            </override>
           <fallback>
               <refresh>60.0</refresh>
         </fallback>
        </adjustrefreshrate>
    </video>
</advancedsettings>
```

**Comment by hunterzero99** [comment] 2020-12-18 01:13
Forcing the frame rate did not help on my system.  I pulled some logs while it was dropping frames, and I also pulled a log of framerate switching off where it doesn't drop frames for comparison.  I played the same video, but did not run them for the same length of time during the tests.

[Log of not dropping frames](https://drive.google.com/file/d/1vG1SxiqZko79YBC7WEkYvqqqbKjNtC7s/view?usp=sharing)
[Log of dropping frames](https://drive.google.com/file/d/1rX0vvXh0tnoAN16fjmGPfP6I_GEZYJ6_/view?usp=sharing)

I'm trying to pick out differences between the two, so far this is something I've found that shows only on the one where frames aren't dropped:
```
DEBUG <general>: GL: Pixel Shader compilation log:
DEBUG <general>: Success.
DEBUG <general>: GL: Vertex Shader compilation log:
DEBUG <general>: Success.
```

ffmpeg also mentions the swscaler when using framerate matching (this one drops frames):
```
DEBUG <general>: ffmpeg[(nil)X]: [swscaler] Forcing full internal H chroma due to odd output size
DEBUG <general>: ffmpeg[(nil)X]: [swscaler] Forcing full internal H chroma due to input having non subsampled chroma
DEBUG <general>: ffmpeg[0x9d517680X]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
DEBUG <general>: ffmpeg[0x79962940X]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
```

I'll keep looking for differences between the two, might at least point in a particular direction.

**Comment by CastagnaIT** [comment] 2021-01-04 08:44
If someone want to test the matthuisman PR fix (Kodi 19):
[inputstream.adaptive-android-armv7-matrix-e64c045.zip](https://github.com/peak3d/inputstream.adaptive/files/5763714/inputstream.adaptive-android-armv7-matrix-e64c045.zip)
[inputstream.adaptive-android-aarch64-matrix-e64c045.zip](https://github.com/peak3d/inputstream.adaptive/files/5763755/inputstream.adaptive-android-aarch64-matrix-e64c045.zip)

**Comment by hunterzero99** [comment] 2021-01-04 17:36
This patch did not fix the problem for me.

**Comment by MaccyGit** [comment] 2021-01-04 20:06
Also NOT fixed here too

**Comment by Msel88** [comment] 2021-03-28 11:24
**Edit:**
Resolution is limited to 960x540p with widevine forced to level 3. I haven't noticed that at first.

Just in case anybody else is still looking for a solution to this, I'd like to share my findings here.
For me, setting the Widevine Security Level to 3 did the job for Netflix. The setting is located in Netflix addon settings / Expert (see screenshot).

![20210328_125847](https://user-images.githubusercontent.com/81513210/112750423-d386f380-8fc8-11eb-95b1-e6afbb1c40d7.jpg)

I now have smooth playback @540p24 on my FireTV Stick 4k.

Fire OS 6.2.7 6 (NS6276/2933)
Fire TV framerate switching = ON
Kodi 18.9.0
Kodi adjust framerate = on start/stop, sync to screen = OFF
Netflix Addon 1.12.3, HEVC Profile enabled

**Comment by hunterzero99** [comment] 2021-03-28 12:35
> Just in case anybody else is still looking for a solution to this, I'd like to share my findings here.
> For me, setting the Widevine Security Level to 3 did the job for Netflix. The setting is located in Netflix addon settings / Expert (see screenshot).
> 
> ![20210328_125847](https://user-images.githubusercontent.com/81513210/112750423-d386f380-8fc8-11eb-95b1-e6afbb1c40d7.jpg)
> 
> I now have smooth playback @1080p24 on my FireTV Stick 4k.
> 
> Fire OS 6.2.7 6 (NS6276/2933)
> Fire TV framerate switching = ON
> Kodi 18.9.0
> Kodi adjust framerate = on start/stop, sync to screen = OFF
> Netflix Addon 1.12.3, HEVC Profile enabled

When I turn this on I'm getting a 960x540p stream which does playback without dropping frames.

**Comment by Msel88** [comment] 2021-03-28 17:39
> When I turn this on I'm getting a 960x540p stream which does playback without dropping frames.

You're right, same for me. I missed that in the first place. My bad...

**Comment by jellejans** [comment] 2021-04-16 12:55
Any update on this?

**Comment by glennguy** [comment] 2021-04-17 09:42
@jellejans unless Amazon have fixed on their end (not likely) then no.

From what I can understand reading this thread the issue is with AVC/h264 content (most 1080p). 4K (HEVC/h265) content doesn't have the issue. And as others have pointed out, for $30 it's hard to complain.

**Comment by jellejans** [comment] 2021-04-18 15:57
> @jellejans unless Amazon have fixed on their end (not likely) then no.
> 
> From what I can understand reading this thread the issue is with AVC/h264 content (most 1080p). 4K (HEVC/h265) content doesn't have the issue. And as others have pointed out, for $30 it's hard to complain.

Yeah indeed hard to complain for a 30$ streaming device. Strange part is that i also have the stutter with 4k content on Disney+ and Netflix. When i change the refresh rate to 60hz it’s gone

**Comment by CastagnaIT** [comment] 2021-05-20 07:39
i report a note found on the old PR of HDR implementation on Kodi
https://github.com/xbmc/xbmc/pull/16557

> 1080p streams don't play smooth yet, but there are still ptions to optimize the render chain (e.g. YUV scanout instead our own YUV2RGB shader)

I don't know if these shader optimizations have already been done,
maybe they could help the problem?

Also specify that Kodi setting `Use display HDR capabilities` when enabled do the HDR calulation on GPU / display instead of internal calculation, now i do not have an HDR device to check but what happens if you turn off this setting?

**Comment by farlight1** [comment] 2021-08-28 09:31
I'm suffering this problem too. After change all individual settings and combinations, I landed here.

I'm using:
Fire TV stick 4K - FireOS 6.2.8.1
Kodi 19.1
24Hz 4K capable TV

I found in the comments some missinformation, I shall try to explain when the problem appears.

- The problem is that some frames are dropped when the addons Netfix and Disney+ streams video in AVC(h264)/1080p/24fps secured, and TV switched to 24Hz.

Doing some tests, I can confirm that:

- no matter the resolution, only appears if the TV is in 24Hz mode. (you can put TV in 720p/4K, 24Hz, if the stream is a native h264 it will also drop frames).
- Same stream 1080p/h264/24fps but with a different refresh TV mode (60Hz, 50Hz) works well, no dropping frames
- Changing any Kodi System/Video option (Sync to monitor, manual Hz switch, refresh rate, graphics buffer) makes no difference, will drop frames.
- Loading a local video file through Kodi internal player, 1080p/24fps AVC(h264) (unsecured) and TV in 24Hz mode, works flawless, no dropping frames.
- HEVC(h265) secured streams in all resolution/24fps works well in 24Hz mode, Netflix and Disney+, no dropping frames at all in any display mode
- Amazon prime video app, that came with Hz autoswitching too, a stream 1080p/h264/24fps (unsecured) and TV switched to 24Hz works well (I only found this stream in the commercials and adverticements, all films are streamed in HEVC(h265).

All the test confirmed with FireOs debug tools. I hope that if anyone is still checking, this will help.

**Comment by jchtt** [comment] 2021-12-16 04:20
Also just ran into this, any news?

Edit: Only testing this on Netflix. Disabling the secure decoder fixes it but forces all output to 1080p. For me a great workaround would be if the secure decoder could be conditionally disabled for h264 content and enabled for 4k/h265 content.

Edit 2: Actually, while it seems better without the secure decoder, it is actually still pretty choppy.

**Comment by CastagnaIT** [comment] 2022-03-12 09:07
someone know if this problem there is also on the new Amazon Fire TV Stick 4K Max?

**Comment by hunterzero99** [comment] 2022-10-11 09:13
I do not have the issue on the 4k stick!

**Closed as not planned** 2023-02-09 10:40 UTC
Labels: Issue Cleanup: Closed, Platform: Android, Component: Video
