### ISSUE TITLE
Part of some videos could not be decrypted

### ISSUE THREAD

**Issue by AlecJY** [peak3d/inputstream.adaptive#394] opened 2020-03-14 06:16 UTC
Part of some videos protected by widevine got errors when decrypt, and it seems cause the video look strange. Such as [Bitmovin's DRM demo video](https://bitmovin.com/demos/drm) from 360p to 720p. The video will look like this when the error occurs.

![image](https://user-images.githubusercontent.com/9132996/76676322-3cd5d780-65fd-11ea-9c6d-16a2b3d112d6.png)

And the error messages look like this.
```
2020-03-14 13:52:46.719 T:22668   DEBUG: AddOnLog: InputStream Adaptive: DecryptSampleData: Decrypt failed with error: 2 and key: EB676ABBCB345E96BBCF616630F1A3DA
2020-03-14 13:52:46.719 T:22668   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-03-14 13:52:46.722 T:22668   DEBUG: AddOnLog: InputStream Adaptive: DecryptSampleData: Decrypt failed with error: 2 and key: EB676ABBCB345E96BBCF616630F1A3DA
2020-03-14 13:52:46.722 T:22668   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-03-14 13:52:46.735 T:22668   DEBUG: AddOnLog: InputStream Adaptive: DecryptSampleData: Decrypt failed with error: 2 and key: EB676ABBCB345E96BBCF616630F1A3DA
2020-03-14 13:52:46.735 T:22668   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-03-14 13:52:46.735 T:22668   DEBUG: AddOnLog: InputStream Adaptive: DecryptSampleData: Decrypt failed with error: 2 and key: EB676ABBCB345E96BBCF616630F1A3DA
2020-03-14 13:52:46.735 T:22668   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
```

Only 1080p looks normal and didn't have "Decrypt Sample returns failure!" messages.

[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/4332339/kodi.log)

**Comment by dagwieers** [comment] 2020-03-14 09:26
This is a duplicate of #393

**Closed** 2020-03-19 03:51 UTC
