### ISSUE TITLE
IA is using a wrong initial segment the 2nd time a stream is played

### ISSUE THREAD

**Issue by michaelarnauts** [peak3d/inputstream.adaptive#543] opened 2020-10-29 09:03 UTC
I'm noticing an issue when playing a widevine protected stream. The first time the stream is played, it works as it should, but the 2nd time, I can see that IA is requesting wrong segments that don't exist.

Open PR: https://github.com/add-ons/plugin.video.viervijfzes/pull/47

**How to reproduce:**
Use above PR, enter credentials (you can register freely, or ask me on slack) and go to Channels > ZES > Catalog > NCIS: New Orleans > Season 3 > Episode 3x08 (for example, it happens with all episodes)

**Kodi debug log:**
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/5457174/kodi.log)

manifest: https://github.com/add-ons/plugin.video.viervijfzes/files/5443644/NCIS_NEW_ORLEANS_3_8_F0250070.mpd.txt

@mediaminister already debugged it a bit:
I already found out that the `range_begin_`  of the (next) segment has a completely wrong value the second time you start a stream. I guess there is something wrong in the initialization logic in AdaptiveStream.cpp but I didn't find a good way to debug this yet. 

Tagging some people who already looked at this.
@glennguy @mediaminister

**Comment by glennguy** [comment] 2020-10-30 12:52
@mediaminister @michaelarnauts 
I have some findings using the provided mpd hosted locally (can't access actual stream from where I am)

Removing the static keyword from 't' [here](https://github.com/peak3d/inputstream.adaptive/blob/Matrix/src/parser/DASHTree.cpp#L341) fixes the issue. I haven't tested with other mpd streams to see if anything breaks however.

I'm no expert in c++ but setting `t` as static causes `t` to only be set to 0 on first execution of that code block - it will not be reset back to 0 on the next loop iteration.
In this provided mpd the first entry in `SementTimline` has the `t` value omitted (other examples I've seen explicitly have `t="0"`). In my case IA parses the 1600 video representation first (has first segment correctly starting at 0), the other 3 video representations next and the audio representation last. The last entry in `SegmentTimeline` for all video reps has a total time of 64094 eg. t 64082 + d 12. For the other video reps and audio rep the `range_begin_` of `segment[0]` is 64094 instead of 0.

This 64094 number differs from the 59805 in the supplied log, it looks like the mpd belongs to a different NCIS episode of slightly longer length.

Looking at the '2nd time' log file in the issue linked above it looks like this static variable is living between instances of inputstream.adaptive too i.e `video/1600/segment-114830335.mp4`. This 114830335 certainly must come from the last audio segment time from the previous played stream.

**Comment by mediaminister** [comment] 2020-10-30 14:33
Many thanks, I can confirm this works.

> This 64094 number differs from the 59805 in the supplied log

I can't find 59805 in the above log.

Here is a new log and mpd:
[ok.log](https://github.com/peak3d/inputstream.adaptive/files/5465694/ok.log)
[NCIS_NEW_ORLEANS_3_8_F0250070.mpd.txt](https://github.com/peak3d/inputstream.adaptive/files/5465701/NCIS_NEW_ORLEANS_3_8_F0250070.mpd.txt)

**Comment by glennguy** [comment] 2020-10-31 00:39
> Many thanks, I can confirm this works.

Awesome, thanks for testing

> I can't find 59805 in the above log.

Sorry, was getting it confused with the log in the linked issue

**Comment by peak3d** [comment] 2020-10-31 12:47
This removes the static: 30f3a74595fb6e33d871c5aac0df703a2c9a240c

**Comment by michaelarnauts** [comment] 2020-10-31 13:26
I've applied that commit in the Leia branch, and verified it worked fine. According to @peak3d, some streams need this variable to be static, but it's been reset to 0 now segmenttemplate starts.

**Comment by glennguy** [comment] 2020-10-31 21:23
Thanks @peak3d for the proper solution, I'll close PR 👍

**Comment by matthuisman** [comment] 2021-04-12 02:09
@michaelarnauts 
could you please close this issue as been resolved

**Closed as completed** 2021-04-12 05:37 UTC
