### ISSUE TITLE
Image artefacts (pixel) when streaming video from Wakanim

### ISSUE THREAD

**Issue by vhvvx777** [peak3d/inputstream.adaptive#523] opened 2020-10-03 17:47 UTC
Good afternoon, when watching a video through the wakanim plugin, the picture crumbles into artifacts. I tried different versions but the problem persists. I managed to reduce the number of artifacts by turning off the hardware decoder, but the gap is still present. Is there a solution to this problem?

**Comment by glennguy** [comment] 2021-06-09 05:20
Duplicate of #394 and #393 - btw progress has been made there

**Closed as completed by glennguy** 2021-06-09 05:20 UTC
