### ISSUE TITLE
Effective_URL / Current issues

### ISSUE THREAD

**Issue by peak3d** [peak3d/inputstream.adaptive#531] opened 2020-10-15 19:09 UTC
There are several PR's adressing issues with effective URL. Effective URL is not qute simple because of parameters and HEADERS which should / shouldn't passed in the the download chain.

Please let us collect the known issues here and figure out a soulution which works for all.

Thx!

**Comment by smf007** [comment] 2020-10-15 22:38
@matthuisman had opened Issue #473 that has two redirect problems.  It's actually 1 problem, but occurs for both HLS and MPD.  The problem is the resulting URL used is incorrect IF there is a redirect where the new domain is actually a bit.ly.

In #473 I had run through his test cases and posted some results from tracing the code.

**Comment by matthuisman** [comment] 2020-10-15 23:15
@peak3d 
actually, it's just 3x PRs

https://github.com/peak3d/inputstream.adaptive/pull/508 vs https://github.com/peak3d/inputstream.adaptive/pull/491 & https://github.com/peak3d/inputstream.adaptive/pull/490

My PR tries to address the root issue of IA keeping track of the original url and the final url (after redirect)
I see no need for that so I just change it to always use the final url for manifest.
This makes the code a lot simpler and removes a lot of yucky url joining / replacing.
After getting the manifest, it grabs the final url (effective url) and just works with that from then on.

But maybe you know a reason the original (bit.ly in the examples) url needs to be kept track of?

**Comment by peak3d** [comment] 2020-10-16 07:31
@matthuisman the initial concept is that the URLs are expanded already during parsing of the manifests, which leads to have always full qualified URL's in the AdaptiveTree. Going the simple way by replacing initial base-url with redirected url (simplify code) will not work for all situations, because there is then no way to replace the URL properly.

To change this, a concept change has to be done (store the URL's in AdaptiveTree as they are provided in manifest) and add the base-url just before the file is downloaded.

Simplifying the code as your PR implements will not work for some streams, about this I'm sure

Do you have a sample stream or at least a debug log showing the issue you arrived?
@smf007 I'll look at the issue you linked, if there is no test stream or debug log, I'll come back here....

And yes, you are right, "only" 3 PR's, not 4 :-)

**Comment by matthuisman** [comment] 2020-10-16 07:43
So your saying when bit.ly redirects to manifest.mpd - you need the bit.ly for calculating further urls?
That is what is causing all the issues in the 1st place. That initial bit.ly url should not be used again.

The change above has been in testing for a long time without issues.
I've put it through every stream I've come across without issue.
It even works with multiple levels of redirects.

Be interested in seeing a stream where it doesn't work.

The issue is here (with samples)
https://github.com/peak3d/inputstream.adaptive/issues/473

It's been around a long time.

**Comment by peak3d** [comment] 2020-10-16 08:03
> That is what is causing all the issues in the 1st place. That initial bit.ly url should not be used again.

Especially if URL's in HLS / MPD were passed relative, the current AdaptiveTree reader logic has prefixed them with bit.ly.
To revert this prefixing, we still need the baseURL for finding it.

**Comment by matthuisman** [comment] 2020-10-16 08:08
the tree never knows about bit.ly with my PR

https://github.com/peak3d/inputstream.adaptive/blob/d3a4fa6e6664494acd6dd601283bc58011fe11d0/src/parser/DASHTree.cpp#L1541-L1551

url = bit.ly
effective_url_ will be the actual final url (manifest)
PreparePaths is done with effective_url_ 
So all base domains, etc use the final url before the manifest is parsed

same with the other trees

https://github.com/peak3d/inputstream.adaptive/blob/d3a4fa6e6664494acd6dd601283bc58011fe11d0/src/parser/HLSTree.cpp#L165-L174

All the code knows about is the final url. all relative paths will be based off that (correctly)

**Comment by peak3d** [comment] 2020-10-16 08:12
> the tree never knows about bit.ly with my PR

This is only true for HLS
Your PR changes the behaviour for all stream types, which is not correct.

**Comment by matthuisman** [comment] 2020-10-16 08:13
please see the code

**Comment by peak3d** [comment] 2020-10-16 08:16
https://github.com/peak3d/inputstream.adaptive/blob/Matrix/src/parser/DASHTree.cpp#L979
This is what is used for creating the full URL, and it is bit.ly. This is then exposed to all places where an URL is build up (adaptationset / representations / segments)

Edit: HLS is a different procedure, because subs (Representations) are not known at this early stage.
My proposed solution: we extract and replace basedomain instead baseurl when handling redirects.

Not sure if this works for all situations, but it would at least solve your issue.

**Comment by matthuisman** [comment] 2020-10-16 08:21
there is no need for all that if you just update the manifest url, base url etc to the final url before any parsing.
which my PR does

1) bit.ly called. Curl grabs it and sets effective_url to the actual final url
2) We use that effective_url instead of the original url to PreparePaths so all the paths are correct.

**Comment by peak3d** [comment] 2020-10-16 08:23
This would mean running through the complete tree and replace it once.
This is what I tried to say in the initial post: Current implementation builds full paths, this is something which makes it hard now, but it is as it is....

**Comment by matthuisman** [comment] 2020-10-16 08:23
no it doesnt. the path is changed before parsing the tree....


I think we ate stalemate.
Probably best to go with other 2 PRs and keep all the path adjusting edge cases

**Comment by peak3d** [comment] 2020-10-16 08:29
I see the bug here, I'll come back later....

**Comment by matthuisman** [comment] 2020-10-16 08:34
Dash (my PR)
https://github.com/peak3d/inputstream.adaptive/blob/d3a4fa6e6664494acd6dd601283bc58011fe11d0/src/parser/DASHTree.cpp#L1541-L1550

URL coming in would be bitl.y
Download just loads up the data into manifest_stream (does not do any parsing)
It also sets the effective_url to the final url.
Now we come back and use that effective_url in PreparePaths instead of the original url.
Then we do the parsing.

So you see - "bit.ly" is only known at the very start of that function.
After that, all the code is using the final url.
Prepare paths would correctly set the base url, base domain etc from that final url.

Here is the modified download code (also a lot simpler)
https://github.com/peak3d/inputstream.adaptive/blob/d3a4fa6e6664494acd6dd601283bc58011fe11d0/src/main.cpp#L262

**Comment by peak3d** [comment] 2020-10-16 09:04
Issue is: your solution helps for redirections caused by downloading, but it doesn't solve the situation, when we callback into an addon to get a new URL after 403: https://github.com/peak3d/inputstream.adaptive/blob/Matrix/src/main.cpp#L375-L382

Root issue is that we don't handle the situation correctly, if the paths in manifest files are given absolute (starting with a /) what is true in your case. In this situation we have to replace domain and not URL, but this is not yet implemented.

IMO your PR is much, too much (reading into memory, then changing path, then parsing). Wouldn't it be much simpler to simply call PreparePath() here: https://github.com/peak3d/inputstream.adaptive/blob/Matrix/src/main.cpp#L291-L305 instead setting the effective URL?

Sure this doesn't fix the addon-redirect either, but it should have the same effect your PR has -> I'm testing....

Edit: Yes, this works for your stream.....

**Comment by matthuisman** [comment] 2020-10-16 09:18
I wasn't sure if you could call prepare paths from in that function (different file). But yes, that would work nicer.  I'll redo this using that. And keep the mpd parsing how it was (as it come ins) 
It still allows for most of this PR to remove a lot of the checking effective etc

**Comment by matthuisman** [comment] 2020-10-16 09:32
oh, I remember the issue with that
manifestUpdateParam isn't available in bool adaptive::AdaptiveTree::download ?

**Comment by peak3d** [comment] 2020-10-16 09:36
you can use manifest_parameter_ member instead

**Comment by peak3d** [comment] 2020-10-16 09:49
```
diff --git a/src/main.cpp b/src/main.cpp
index cbaadfd..8503bed 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -269,6 +269,8 @@ bool adaptive::AdaptiveTree::download(const char* url,
   if (!file.CURLCreate(url))
     return false;

+  std::string log_url = url;
+
   file.CURLAddOption(ADDON_CURL_OPTION_PROTOCOL, "seekable", "0");
   file.CURLAddOption(ADDON_CURL_OPTION_PROTOCOL, "acceptencoding", "gzip");

@@ -285,24 +287,12 @@ bool adaptive::AdaptiveTree::download(const char* url,

   if (scanEffectiveURL)
   {
-    effective_url_ = file.GetPropertyValue(ADDON_FILE_PROPERTY_EFFECTIVE_URL, "");
-    kodi::Log(ADDON_LOG_DEBUG, "Effective URL %s", effective_url_.c_str());
-
-    std::string::size_type paramPos = effective_url_.find_first_of('?');
-    if (paramPos != std::string::npos)
-      effective_url_.resize(paramPos);
-
-    paramPos = effective_url_.find_last_of('/');
-    if (paramPos != std::string::npos)
-    {
-      effective_filename_ = effective_url_.substr(paramPos + 1);
-      effective_url_.resize(paramPos + 1);
-    }
-    else
-      effective_url_.clear();
+    std::string effective_url = file.GetPropertyValue(ADDON_FILE_PROPERTY_EFFECTIVE_URL, "");
+    kodi::Log(ADDON_LOG_DEBUG, "Effective URL %s", effective_url.c_str());

-    if (effective_url_ == base_url_)
-      effective_url_.clear();
+    std::string::size_type paramPos = effective_url.find_last_of('/');
+    if (paramPos != std::string::npos && base_url_.compare(0, paramPos, effective_url) != 0)
+      PreparePaths(effective_url, manifest_parameter_);
   }

   // read the file
@@ -320,7 +310,7 @@ bool adaptive::AdaptiveTree::download(const char* url,

   file.Close();

-  kodi::Log(ADDON_LOG_DEBUG, "Download %s finished", url);
+  kodi::Log(ADDON_LOG_DEBUG, "Download %s finished", log_url.c_str());

   return nbRead == 0;
 }
```

Edit: This should also solve the issue @smf007 is adressing.

**Comment by matthuisman** [comment] 2020-10-16 09:58
manifest_parameter_ is set in PreparePaths... so will always be empty in the above
manifestUpdateParam is passed in from main to open()
So, it will need to be passed to download so it can be used in PreparePaths

Also, pretty sure you can remove all that scanEffectiveURL and baseurl stuff and just have

std::string effective_url = file.GetPropertyValue(ADDON_FILE_PROPERTY_EFFECTIVE_URL, "");
PreparePaths(effective_url, manifestUpdateParam);

ADDON_FILE_PROPERTY_EFFECTIVE_URL is always the last url or the 1st url if no redirect.

then remove all the member effective_url_ stuff completely as not needed.
which then lets you remove all the other checks for it scattered across the code.
much cleaner and none of the searching for / stuff (prone to breaking / logic issues)

**Comment by peak3d** [comment] 2020-10-16 10:05
huh? manifest_updatepatameter is initially passed here:
https://github.com/peak3d/inputstream.adaptive/blob/Matrix/src/main.cpp#L2234

and then

https://github.com/peak3d/inputstream.adaptive/blob/Matrix/src/parser/DASHTree.cpp#L1545

After this download() is called, so it is NOT always "" !

**Comment by matthuisman** [comment] 2020-10-16 10:11
so now your calling preparepaths twice?
why call it on the initial url that may very well be not the final url?

**Comment by peak3d** [comment] 2020-10-16 10:13
I call it twice if a redirection url is different to the curent URL, I think this is fine, no ?

**Comment by matthuisman** [comment] 2020-10-16 10:14
why not just something like this (havnt checked for typos etc yet)
https://github.com/matthuisman/inputstream.adaptive/commit/e9de6b329c8ede3ad06d7277f9e8238892e03cc5
(updated the wrong header file there - should be adapativetree.h updated)

**Comment by matthuisman** [comment] 2020-10-16 10:15
then after that, we can remove all the effective_url_ stuff other places in code. 
as all the base urls will be correct before parsing.

**Comment by peak3d** [comment] 2020-10-16 10:17
Sure, could work either, unfortunately I cannot recap why the scaneffectiveurl was introduced, but I bet there was a reason for it.

**Comment by peak3d** [comment] 2020-10-16 10:18
> then after that, we can remove all the effective_url_ stuff other places in code.
> as all the base urls will be correct before parsing.

Nope, remember the addon - url - replacing

**Comment by matthuisman** [comment] 2020-10-16 10:19
So, it's an add-on path that gets called if a 404 on manifest correct?
And the add-on returns a new manifest url? which would be a full url.
It won't return partial..

Why can't we just do

```
url = items[0].Path().c_str();
PreparePaths(url, manifest_parameter_);
kodi::Log(ADDON_LOG_DEBUG, "Renewed URL: %s", url);
```
that should update everything we need to the new url.
Just as we would calling a new mpd with that new url

thats that the callback is doing? switching the url of the manifest?

oh, PreparePaths is in adaptivetree and I think this code is in adaptestream

**Comment by matthuisman** [comment] 2020-10-16 10:48
OH, download is used multiple times in HLS (to get pssh, representations)
We wouldn't want those using the PreparePaths().
That will be the reason why you had the flag for scanforeffective

So, the changes would look like this:
https://github.com/matthuisman/inputstream.adaptive/commit/0d763436ecccf3dbc08b5a32c493e92ee3ceeb32

or, we can do PreparePaths in the adapativetree::open as my current PR does,
Only downside is that the mpd goes into memory before parsing instead of parsing as it goes.
The HLS goes into memory, and I can imagine some of them being larger than mpd - so not an issue?

Last issue is getting the addon callback working once I know what it should do

**Comment by peak3d** [comment] 2020-10-16 11:16
This is for what the scanEffectiveUrl is for IIRC

**Comment by matthuisman** [comment] 2020-10-16 11:18
yeh, i just figured it out in my previous comment, and updated the code to show what would then be needed.

I still think my original PR is nicer than this now has become. 
doing PreparePaths in the open() and keep download() for downloading
less function variables, less if statements, less "" variables so better.
Downside is loading mpd and smooth into memory, but as we do that for HLS anyway - is it a big deal?

**Comment by peak3d** [comment] 2020-10-16 11:22
> hats that the callback is doing? switching the url of the manifest?

It's also used for fetching AES keys and media files, must not be imperative reset before manifest actions.

That the current implementation uses "redirect_url" for this was a hack, it is mainly used to replace parameters (changed session key for example)

I suggest that we use the simple approach for now. It's minimal risk and ppl. are already waitung for an release to get nightlies working again.....

**Comment by peak3d** [comment] 2020-10-16 11:27
> I still think my original PR is nicer than this now has become.

Serious? You mentioned that 2 x PreparePath is waste (even it is only called if redirection applies and then only once)
But using a StreamBuf which is not needed from concept you are good with?

Assume huge mpd files, there are so many (re)-allocations / memory copies (depends of implementation of std) until the memory buffer is filled. No, this is IMO the biggest waste of all.

**Comment by matthuisman** [comment] 2020-10-16 11:36
have you seen how big HLS can be? Disney+ for example has so many streams.
can we parse that without loading into memory (line by line?) if so - maybe a good idea?

**Comment by peak3d** [comment] 2020-10-16 12:27
It's not line-by-line: https://github.com/peak3d/inputstream.adaptive/blob/Matrix/src/main.cpp#L309
If performance is because of the size an issue, this buffer can easiy enlarged, but from what i remember from early days there was no big benefit to enlarge it...

**Comment by peak3d** [comment] 2020-10-16 12:30
So, final question: are there any objections for the diff I provided?
IMO it's unrisky, solves your 2 issues, keeps addon update working. Only "issue" is that PreparePath() is called 2 times on startup for some few streams.
If you look into PreparePath(), you see that there is not really much done - IMO nothing performance critical.

**Comment by peak3d** [comment] 2020-10-16 18:54
I have committed the Diff I send before, your issues should be solved now @matthuisman and @smf007 .
If we arrive any issues in this area again in the future, we'll have to rework.

Hope nobody is upset now..., time is currently not my friend

**Comment by smf007** [comment] 2020-10-16 20:40
@peak3d, your fix works good.  I've thrown a couple tests at it and I don't notice any regressions.

**Comment by peak3d** [comment] 2020-10-26 09:49
Unfortunatly we have to revert the fix, if absolute URL's are in master playlist, redirecting does not work.

**Comment by peak3d** [comment] 2020-10-27 09:16
@smf007 I had to change the previous solution, changes are pushed in Matrix branch.
@matthuisman the HLS streams from #473 work fine, the MPD is still not working, IA doesn't receive any akamei URL.

Edit: Fixed MPD redirect issue.

**Comment by matthuisman** [comment] 2020-11-20 06:24
@peak3d 
with current head, both the redirected mpd and hls work.

However, now the direct HLS stream (without redirect) are broken:
https://raw.githubusercontent.com/matthuisman/ia_tests/master/hls_redirected/hls_direct.strm
(above is quite a biggy. think IA is not liking a / path in a substream)

Also, a redirect on a HLS substream doesn't work either.
https://raw.githubusercontent.com/matthuisman/ia_tests/master/hls_redirected_sub/hls_direct.strm

Ultimate test is:
https://raw.githubusercontent.com/matthuisman/ia_tests/master/hls_redirected_sub/hls_redirected.strm
(this has redirect to master playlist, which then has redirect to substream)

All above work with this PR: https://github.com/peak3d/inputstream.adaptive/pull/508

**Comment by kyl416** [comment] 2020-12-12 02:55
One of the commits you made for Leia since the initial 2.4.6 release broke parsing the AES key when the URI isn't an absolute path. It's a live stream for a paid streaming service that's behind a paywall, so I can't give the exact URL out. But this is an example of what it looks like with the identifying parts of the URL hidden:
The url is something like:
```
https://xxxx.cloudfront.net/hls/video/xxx/xxx_namexx_x/playlist.m3u8
```
It opens up a m3u8 playlist that looks like this:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2119734,CODECS="avc1.77.31, mp4a.40.2",RESOLUTION=960x540
chunklist.m3u8
```
And that chunklist.m3u8 playlist looks like this:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:12
#EXT-X-MEDIA-SEQUENCE:80
#EXT-X-KEY:METHOD=AES-128,URI="/hls/key/xxx/key.php?stream=xxx_namexx_x"
#EXTINF:9.966,
media-u1de9s8q5_80.ts
#EXTINF:9.967,
media-u1de9s8q5_81.ts
#EXTINF:9.567,
media-u1de9s8q5_82.ts
#EXTINF:10.8,
media-u1de9s8q5_83.ts
#EXTINF:9.033,
media-u1de9s8q5_84.ts
#EXTINF:10.0,
media-u1de9s8q5_85.ts
```
The key should be resolved with the base URL appended like this:
```
https://xxxx.cloudfront.net/hls/key/xxx/key.php?stream=xxx_namexx_x
```

This is the error message I get in the log:
```
2020-12-11 21:34:38.758 T:4816   ERROR: AddOnLog: InputStream Adaptive: Cannot download /hls/key/xxx/key.php?stream=xxx_namexx_x
```

**Comment by smf007** [comment] 2020-12-13 16:03
@kyl416 to confirm:
- with Leia and IA 2.4.6 you have no problems?

As you are using an IA newer than 2.4.6, are you able to compile it yourself and narrow down the commit?

Have you tested with the latest on the Leia branch? (latest being 2020 Oct 31, 09ec268)

**Comment by kyl416** [comment] 2020-12-13 20:19
The problem started with commit 34c218540b6278b5d7fd7d4bf5cac01b28998183 and is still there with the latest commit.

**Comment by smf007** [comment] 2020-12-15 21:05
@kyl416 
I don't have a test case to replicate the issue, but reading the code I believe it is the change to routine SetEffectiveURL.  If you comment out the added line
`effective_domain_.clear();`
I think this should resolve your issue.

**Comment by kyl416** [comment] 2020-12-15 23:51
Nope, the issue is still there with that line commented out.

**Comment by smf007** [comment] 2020-12-16 03:19
Was that change made on top of  09ec268 or 34c2185 ?

**Comment by kyl416** [comment] 2020-12-16 23:32
It still happens if I comment the line out on both of those commits.

**Comment by smf007** [comment] 2021-01-01 16:49
@kyl416
Give this a try https://github.com/smf007/inputstream.adaptive/commit/b0b3d244a45f489b25a6654ec51ddad51bbbe0ba

**Comment by kyl416** [comment] 2021-01-04 04:12
Nope, it still doesn't work with that commit on your fork.

**Comment by Testato** [comment] 2021-03-13 17:22
Hi peak3d,
also on my plugin LA7-LA7d there is a 404 on the url. 
IA always return the same address https://d15umi5iaezxgx.cloudfront.net/OUT/DASH/Live_960x540_-00000001.mp4

You can found the LA7 plugin on the official Kodi19 repo, the brocken channel is the first, LA7 Live

**Comment by matthuisman** [comment] 2021-04-12 02:12
@phunkyfish  this can be closed.
any bugs introduced have been fixed and new discussion is in my latest PR: https://github.com/xbmc/inputstream.adaptive/pull/620

**Closed as completed** 2021-04-12 12:58 UTC
