### ISSUE TITLE
Call out to all stakeholders for testing v2.4.3 (Leia)

### ISSUE THREAD

**Issue by dagwieers** [peak3d/inputstream.adaptive#387] opened 2020-02-15 16:36 UTC
@peak3d made clear he is unable to do Leia releases as he is using Matrix himself.

So this is a call out to all users and stakeholders to test **inputstream.adaptive** v2.4.3 with your add-on(s) and report back.

You can find various v2.4.3 builds at:
- [Most platforms](https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/Leia_backport/3/artifacts) (Android, iOS, macOS and Windows)
- [LibreELEC v9.2.0 on RPi](http://users.telenet.be/peno/kodi/addons/inputstream.adaptive/)

If you want to do extensive testing with your add-on(s), you can find a list of tasks to complete to test the behaviour: https://github.com/peak3d/inputstream.adaptive/wiki/Test-plan

And you can report back success or failure at the Wiki at: https://github.com/peak3d/inputstream.adaptive/wiki/Test-results

*This relates to https://github.com/peak3d/inputstream.adaptive/issues/330 and https://github.com/michaelarnauts/plugin.video.vtm.go/issues/101*

**Comment by dagwieers** [comment] 2020-02-15 16:39
cc @Sandmann79 @micahg @emilsvennesson @herrnst @arvvoid @FraserChapman @CastagnaIT @Lunatixz @basrieter @skipmodea1 @enen92 @MrKrabat @phate89 @mediaminister @michaelarnauts @shycoderX

*(You are listed on the Wiki as Stakeholders: https://github.com/peak3d/inputstream.adaptive/wiki/Stakeholders)*

**Comment by enen92** [comment] 2020-02-15 17:07
@dagwieers first of all thanks for the heads up. In RTP play inputstream was used as a fallback but it looks like they just use hls streams now and ditched mpd/widevine. Either way, gave it a test on osx after installing from the zip provided above. I'm getting this error:

```
│2020-02-15 17:05:36.674 T:123145436524544   ERROR: Unable to load /Users/enen/Library/Application Support/Kodi/addons/inputstream.adaptive/inputstream.adaptive.2.4.3.dylib, reason: dlop│
en(/Users/enen/Library/Application Support/Kodi/addons/inputstream.adaptive/inputstream.adaptive.2.4.3.dylib, 1): no suitable image found.  Did find:                                     │
│                                               /Users/enen/Library/Application Support/Kodi/addons/inputstream.adaptive/inputstream.adaptive.2.4.3.dylib: code signature in (/Users/enen/Library/Application Support/Kodi/addons/inputstream.adaptive/inputstream.adaptive.2.4.3.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completel│
y unsigned? Code has to be at least ad-hoc signed.                                                                                                                                                         │
│                                               /Users/enen/Library/Application Support/Kodi/addons/inputstream.adaptive/inputstream.adaptive.2.4.3.dylib: stat() failed with errno=3
```

**Comment by dagwieers** [comment] 2020-02-15 17:31
@enen92 If `stat()` fails, it cannot be related to signing. Does the file exist in that location?
Can you try to restart Kodi? I have seen issues before when replacing libraries and Kodi not picking it up.

**Comment by enen92** [comment] 2020-02-15 17:44
File is there, rebooting Kodi doesn't help. It looks like it attempts to load the dynlib but refuses to do so because the code is not signed. This looks like it is not related to kodi or the addon code but jenkins itself.

**Comment by peno64** [comment] 2020-02-15 18:02
@enen92 
In windows this is called dll hell. Unix/Linux (and osx is also a unix variant) has similar issues. Probably this is a binary incompatibility between versions... Are you on an older osx version or quite new?

**Comment by enen92** [comment] 2020-02-15 18:10
Last version of osx. Iirc there were changes in matrix regarding code signing for binary add-ons for osx, iOS and tvos but I might be wrong. Maybe the tvOS guys can help clarify if there is something missing (@fuzzard, @phunkyfish) or maybe also @alwinus.

**Comment by peno64** [comment] 2020-02-15 18:21
@jenkinsci what do you think about the @enen92 problem?

**Comment by enen92** [comment] 2020-02-15 18:22
@peno64 problem (if confirmed) is in the job configuration and not in Jenkins, no need to ping the official project.

**Comment by phunkyfish** [comment] 2020-02-15 18:39
@kambala-decapitator

**Comment by michaelarnauts** [comment] 2020-02-15 19:21
I first need to compile the whole kodi package again for OSMC (if I only compile inputstream, I have strange issues, they both have to be compiled together, don't know why), this takes a few hours, so I can only test tomorrow I think.

Thanks @dagwieers for setting this in motion!

**Comment by samnazarko** [comment] 2020-02-15 19:46
You might have some playback issues with the latest Kodi package in OSMC Git which is currently targeting top of tree Leia.

This will be fixed shortly

On 15 Feb 2020, at 20:21, Michaël Arnauts <notifications@github.com> wrote:

﻿

I first need to compile the whole kodi package again for OSMC (if I only compile inputstream, I have strange issues, they both have to be compiled together, don't know why), this takes a few hours, so I can only test tomorrow I think.

Thanks @dagwieers<https://github.com/dagwieers> for setting this in motion!

**Comment by michaelarnauts** [comment] 2020-02-15 19:55
@samnazarko the way I did the build previously was to use my forked [repo-binary-addons](https://github.com/michaelarnauts/repo-binary-addons) where I've modified [inputstream.adaptive.txt](https://github.com/michaelarnauts/repo-binary-addons/blob/Leia/inputstream.adaptive/inputstream.adaptive.txt) in the `Leia` branch to use the `master` branch of this repo. I'm now building against the `Leia_backport` branch of this repo.

After the long compile (since it also compiles Kodi), I could just extract the `inputstream.adaptive.so.2.4.2` and replace it on my Vero4K. There was no need to install the whole debian package and also replace Kodi and other binary addons.

I assume that this won't give me the issues that a new build of Kodi gives like you indicate, since I'm only using the inputstream.adaptive library of my compile. I'll let you know.

**Comment by samnazarko** [comment] 2020-02-15 20:12
That should be just fine

Sam

On 15 Feb 2020, at 20:55, Michaël Arnauts <notifications@github.com> wrote:

﻿

@samnazarko<https://github.com/samnazarko> the way I did the build previously was to use my forked repo-binary-addons<https://github.com/michaelarnauts/repo-binary-addons> where I've modified inputstream.adaptive.txt<https://github.com/michaelarnauts/repo-binary-addons/blob/Leia/inputstream.adaptive/inputstream.adaptive.txt> in the Leia branch to use the master branch of this repo. I'm now building against the Leia_backport branch of this repo.

After the long compile (since it also compiles Kodi), I could just extract the inputstream.adaptive.so.2.4.2 and replace it on my Vero4K. There was no need to install the whole debian package and also replace Kodi and other binary addons.

I assume that this won't give me the issues that a new build of Kodi gives like you indicate, since I'm only using the inputstream.adaptive library of my compile. I'll let you know.

**Comment by kambala-decapitator** [comment] 2020-02-15 20:57
> Last version of osx. Iirc there were changes in matrix regarding code signing for binary add-ons for osx, iOS and tvos but I might be wrong.

all Leia macOS releases were signed, so they can't load any downloaded binary addons yet. Matrix/v19 version doesn't have this issue.

**Comment by arvvoid** [comment] 2020-02-17 12:17
Tested on macOS Catalina 10.15 Kodi 18.5:
At first, had no issues because my Kodi was not signed, so it could load an unsigned dylib. 
Re-downloaded 18.5 from kodi.tv and is signed and then can confirm it fails to load inputstream.adaptive because it's not signed.
It's possible to check if  Kodi binary is signed with this command from the terminal:
`codesign -dv --verbose=4 /Applications/Kodi.app/Contents/MacOS/Kodi`
It's possible to remove the signing from Kodi so it can load unsigned dylib to be able to test now with this:
`codesign --remove-signature /Applications/Kodi.app/Contents/MacOS/Kodi`

Ofc the only proper solution is to sign the inputstream.adaptive dylib.

With unsigned Kodi 18.5 on MacOS Catalina, hGo add-on (plugin.video.hbogoeu) all tests in test plan ok (1080p HW decoding, Widevine DRM)

Tested on OSMC on **Rpi 3B+** (used the provided LibreELEC v9.2.0 on RPi test build)  hGo add-on (plugin.video.hbogoeu) all tests in test plan ok (1080p HW decoding, Widevine DRM)

Will test on Window 10 64bit later or tomorrow.

**Comment by dagwieers** [comment] 2020-02-18 00:52
@peak3d If everything pans out, when (preferably next week) would you have the time to release v2.4.3 for Leia? It may help to ensure this testing happens in a timely fashion if we have a clear deadline for testing.

**Comment by Uukrull** [comment] 2020-02-19 12:48
Tested on the Shield TV with Youtube, Netflix and DAZN and all seems ok.

**Comment by dagwieers** [comment] 2020-02-19 21:48
@Uukrull Can you please update https://github.com/peak3d/inputstream.adaptive/wiki/Test-results ?

**Comment by Anan5a** [comment] 2020-02-22 06:43
Out of curiosity, the latest version in release section is 2.5.4. Then why still  2.4.3 on Leia?

**Comment by peno64** [comment] 2020-02-22 09:35
@dagwieers 
The youtube addon also uses inputstream.adaptive (it was default disabled on my setup).
Since *alot* of users use youtube on kodi (to watch trailers I know it is used alot) it is important that this is also checked.
Youtube changed something recently such that you must create your own developers keys for it to work. You can find the procedure here: https://koditips.com/setup-use-youtube-kodi-addon/?fbclid=IwAR1gWBb1CDm1Yqm21vqa6CXBKLTqKGqKIm7ZWZ1_WvcfEb4qNkUFhYp9UP4 in section How to Setup Personal Youtube API Key. Note that I already had such a key before but this didn't work. I had to create a new project and do the whole procedure before it worked. In kodi.log I had constantly the message that the api was not correctly configured or enabled while it was with that old key. See https://stackoverflow.com/questions/40355794/access-not-configured-youtube-data-api-has-not-been-used-in-project-60894180825

**Comment by dagwieers** [comment] 2020-02-22 12:43
@peno64 I agree, but testing is a shared responsibility. All known related add-on developers have been notified, and they can forward it to their development community for broader testing.

If people have tested YouTube, please add it to the [Test results wiki page](https://github.com/peak3d/inputstream.adaptive/wiki/Test-results). But we are not going to wait for results for every add-on as this may never happen.

@peak3d Can you provide a timeline for releasing v2.4.3, hopefully this weekend, or the coming week? We have had no reports of new issues or regressions, so all is looking good!

**Comment by peno64** [comment] 2020-02-22 17:30
To create a good debug log and upload it, do the following:

- Go into kodi settings (icon in the middle between shutdown and search icon)
- Goto system and make sure the setting below is at least on Standard
- Goto logging and right enable debug logging. On the left top you will now see extra information
- Restart kodi
- Go into fen, search and play the RD link. 
- You can now disable debug logging again
- Edit the kodi.log file with any text editor and copy all the text to your clipboard
- Goto https://paste.kodi.tv/
- Paste the text from the clipboard
- In the right top, choose save (or press Ctrl S)
- The url will now change.
- Copy the url and paste it in your message
- Now the developer can see the whole contents of your kodi.log file

**Comment by peno64** [comment] 2020-02-22 17:36
Maybe an easier alternative is this: https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

**Comment by dagwieers** [comment] 2020-02-22 21:03
@peno64 Who is this for? I think this is off-topic in this thread :disappointed:

**Comment by peno64** [comment] 2020-02-22 21:34
oops. Sorry

**Comment by dagwieers** [comment] 2020-02-25 20:08
@peak3d Are you around to do a Leia release ?

**Comment by peak3d** [comment] 2020-02-25 20:12
Yes

**Comment by dagwieers** [comment] 2020-02-27 19:30
So **inputstream.adaptive** v2.4.3 has been released and is available for some platforms. We may need a release process to get some of the platforms updated with this new release.

I started to collect platform information at: https://github.com/peak3d/inputstream.adaptive/wiki/Stakeholders#Platforms

cc @marillat @samnazarko @dcrdev

*PS It could be useful to make proper releases (rather than just tags) in GitHub so people can subscribe to new releases in GitHub.*

**Comment by mooninite** [comment] 2020-02-28 00:54
Thanks. The update works OK for me with Leia. A Fedora update is now being pushed.

**Comment by dagwieers** [comment] 2020-02-28 00:55
@mooninite Thanks for the quick response! We will update the Wiki page accordingly.

**Comment by dagwieers** [comment] 2020-02-28 21:29
All platforms (except OSMC?) are now on v2.4.3. Well done everybody!

**Comment by samnazarko** [comment] 2020-02-28 21:37
We’ll update this with Kodi v18.6 shortly.

Sam

**Comment by dagwieers** [comment] 2020-02-28 23:21
@samnazarko Is a Kodi v18.6 release imminent? I had hoped some Kodi bugfixes would get backported (and urged for them to be backported) but got no real response for any of them.

**Closed** 2020-02-29 00:40 UTC

**Comment by kengithub9** [comment] 2020-03-07 09:22
Can anyone help? Which version should I download for LibreElec?
I always receive an error message during the installation.

**Comment by peno64** [comment] 2020-03-07 10:58
The one in the kodi repo is now the latest version (2.4.3.1). What error do you get? kodi.log should also give you more information.

**Comment by dagwieers** [comment] 2020-03-07 13:15
@kengithub9 If your **inputstream.adaptive** was updated, you need to restart Kodi or your device, otherwise it might fail to work.

**Comment by kengithub9** [comment] 2020-03-07 15:08
@peno64 Where can i find it my last version is 2.4.2.1 (LibreElec18.4)

**Comment by dagwieers** [comment] 2020-03-07 15:13
@kengithub9 If you have a LibreELEC version with Kodi v18.4, then you need to update your LibreELEC to v9.2. You are still running v9.0 which is currently unmaintained.

**Comment by kengithub9** [comment] 2020-03-07 15:21
Well, that's why it doesn't work, hopefully Eminent will come up with an update again because I can't update LibreElec myself.

**Comment by dagwieers** [comment] 2020-03-07 15:24
@kengithub9 I would contact their support, because I doubt they are on top of this if there is no demand for it.

**Comment by kengithub9** [comment] 2020-03-07 15:31
I'm going to do but kodi 18.0 more expensive for a very long time, then CoreElec had tried but that worked a little less so they went back to LibreElec. I can install CoreElec on the media player.

**Comment by dagwieers** [comment] 2020-03-07 18:43
Beware that CoreELEC v9.2.1 does not include **inputstream.adaptive** v2.4.3, it will  probably ship with CoreELEC v9.2.2 which is based on Kodi v18.6 and is expected to be released at any time (but probably not before LibreELEC releases a new version).

**Comment by kengithub9** [comment] 2020-04-19 12:50
Eindelijk heb ik Retrospect weer kunnen testen op het afspelen van RTLXL.
Doordat nu CoreELEC 9.2.2. Kodi18.6 uit is gekomen. LibreElec niet actief bijgewerkt door Eminent dus moest ik CoreElec installeren.

Retrospect 5.21. Inputstream 2.4.4..1 inputhelper 0.4.4.

Helaas lukt het niet om de video's correct af te spelen.
Via de instelling van Retro zelf inputstream aan werkt niet en ook uit niet. Ook via menu recent of A t'/m z lijst werkt het niet.
Ook heb ik zelf bij RTLxl de instelling van retrospect verzet naar enabled of disabled maar dat helpt niet. Telkens loopt het beeld en geluid te snel. Bij disabled krijg ik alleen het laatste stuk van de aflevering.
Bij Kijk of NPO start werkt alles gewoon goed met inputstream aan in het menu van retrospect.

Wie kan dit oplossen?
