### ISSUE TITLE
[Feature request] Allow specifying stream to be VOD or Live

### ISSUE THREAD

**Issue by lavish440** [peak3d/inputstream.adaptive#1715] opened 2024-10-31 08:26 UTC
### Describe the feature

Can we have a `KODIPROP` for ISA where we can override the default stream type of a video from VOD to Live and vice versa?

### Motivation

I have some 'Live' VOD streams from my provider. 
They are some VODs stitched together to be viewed as a Live Stream. 
When played through ISA and SIPTV, they play but I can't use the progress bar to seek forward. If I try, they reset to 0. 
The only way I can seek them is through arrow keys but the progress bar doesn't update. 

I have talked about this on SIPTV also, here's the comment:
https://github.com/kodi-pvr/pvr.iptvsimple/issues/915#issuecomment-2435999796

### Are you willing to contribute in development?

No

### Should a possible backport be considered?

No

**Comment by CastagnaIT** [comment] 2024-10-31 08:41
> I have some 'Live' VOD streams from my provider.

the only thing that exists is a "Live to VOD" manifest transition, that is currently not fully supported by ISA,
it depends on the data provided by the video service and cannot be user controlled

if instead you are playing a real live streaming
the GUI "seek bar" is available only when the provider allow a timeshift buffer,
if not, you cannot use video "seek" and if you try seek it will be forced to stay at "current" timeline playback

is not so clear to me the use case,
i need to see all the manifest files to understand the situation

> override the default stream type of a video from VOD to Live and vice versa?

this request is not clear, more details needed, such a thing is not applicable

**Comment by lavish440** [comment] 2024-11-02 08:16
> > I have some 'Live' VOD streams from my provider.
> 
> the only thing that exists is a "Live to VOD" manifest transition, that is currently not fully supported by ISA, it depends on the data provided by the video service and cannot be user controlled

The manifests say it's of VOD type

> if instead you are playing a real live streaming the GUI "seek bar" is available only when the provider allow a timeshift buffer, if not, you cannot use video "seek" and if you try seek it will be forced to stay at "current" timeline playback

I see a seek bar and can seek anywhere from the start of the program to the end. 

> is not so clear to me the use case, i need to see all the manifest files to understand the situation

I have emailed you all the manifest files. 

> > override the default stream type of a video from VOD to Live and vice versa?
> 
> this request is not clear, more details needed, such a thing is not applicable

Like allow seeking through the progress bar when something like `inpuststream.adaptive.stream_type` is set to `vod` or something.

**Comment by CastagnaIT** [comment] 2024-11-02 08:31
> Here are the manifest files. These might contain some data about my account. 

manifest have no account data,
however at least these are normal VOD HLS nothing special

please try play the video, without use iptvsimple
so e.g. by creating a .strm file
an try to see if seek bar works

**Comment by lavish440** [comment] 2024-11-02 08:52
Sure I will try after having lunch.

**Comment by lavish440** [comment] 2024-11-03 16:56
I think you misunderstood my feature request. I can play them fine as a VOD using SIPTV as well. 
The provider gives the timestamp to skip to in the response that I use to skip using Kodi's JSONRPC so that the VOD looks like a Live Stream. 
I want to play them like live channels but have the feature to seek using the progress bar.

**Comment by CastagnaIT** [comment] 2024-11-03 21:25
this last answer of yours confused me even more
i have zero idea of what you want you think to do

if you have a timestamp where you want to perform a video seek
its better that you convert the timestamp in to time format hh:mm:ss then use rpc Player.Seek

**Comment by lavish440** [comment] 2024-11-04 13:58
I get a stream from my provider which is actually a VOD, but is played as Live in their app and platform. 
The stream starts from the beginning in Kodi when played. The provider also gives some epoch timestamps that can be used to skip and play like their app. I use them to skip forward using Kodi's JSON RPC.

But when the ad-break comes, I like to skip forward. If I try to skip forward using the progress bar, the stream restarts from 0. 
I can skip forward using the arrow keys, but the progress bar doesn't update.

**Comment by CastagnaIT** [comment] 2024-11-05 12:51
> But when the ad-break comes, I like to skip forward. If I try to skip forward using the progress bar, the stream restarts from 0.

maybe you are trying to seek wrongly beyond the length of the video and maybe could be the cause that restart to 0

on HLS usually ADS are managed with DISCONTINUITY tags but at least on the manifest you sent to me there are no tags,
i could theorize that the ADS are merged with the main movie, so i exclude a possible problem due to multiple chapters

i dont have ideas... i still dont understand your request and how / what should be implemented,
you cant force manage a VOD as live, your video seek problem sound like a different nature problem

**Comment by lavish440** [comment] 2024-11-05 12:55
> > But when the ad-break comes, I like to skip forward. If I try to skip forward using the progress bar, the stream restarts from 0.
> 
> maybe you are trying to seek wrongly beyond the length of the video and maybe could be the cause that restart to 0

It works when I seek using the arrow keys. 
When I seek beyond the length of video, the stream stops. 

> on HLS usually ADS are managed with DISCONTINUITY tags but at least on the manifest you sent to me there are no tags,
> i could theorize that the ADS are merged with the main movie, so i exclude a possible problem due to multiple chapters

Yes, the ads are not any different from the normal video in the manifests. Not any chapters or Discontinuity tags. 

> i dont have ideas... i still dont understand your request and how / what should be implemented,
> you cant force manage a VOD as live, your video seek problem sound like a different nature problem

I only need the progress bar to be fixed.

**Comment by CastagnaIT** [comment] 2024-11-05 14:09
you need to provide me a way to replicate this thing locally
or i will close the issue since i have no ideas

**Comment by lavish440** [comment] 2024-11-05 15:04
Can I mail you a video demonstration?

**Comment by CastagnaIT** [comment] 2024-11-05 15:16
you can try to send me a video or better a shared link,
but idk if it can help because i have no way to know what happens internally in kodi and ISA

**Comment by lavish440** [comment] 2024-11-05 15:23
I will send you a video demonstration then. 
I can't share a link as the streams are geo locked and won't work without a residential IP from my country. 
Also, the SIPTV maintainer mentioned something about the `itimes` interface in the comment that I linked above.

**Comment by CastagnaIT** [comment] 2024-11-16 12:43
i took a look to manifest and video recording you sent to me
so your its a normal HLS VOD, that you are playing by using pvr.iptvsimple

im pretty sure that if you play it directly (without pvr.iptvsimple) its will be played correctly with also video seek working

now i currently know little about how should works itimes interface
this will require some investigation to learn how to better implement it and also a proper setup to test it
i don't really have time to do this atm

now that i see itimes interface was already a feature request from old #154 issue
that seem to have similar problem despite i was not aware about video seek problem

i am therefore closing this issue because it is duplicated
follow the old issue #154

**Closed as completed by CastagnaIT** 2024-11-16 12:43 UTC
Labels: Duplicate
