### ISSUE TITLE
[Android7] No audio in videwine content

### ISSUE THREAD

**Issue by michael112** [peak3d/inputstream.adaptive#775] opened 2021-08-16 11:27 UTC
Hi,
since several months I have severe problem with playing DRM-encrypted materials - the video is playing properly, but there is no sound.
Usually I use Kodi 18.9 with latest InputStream Adaptive and InputStream Helper, but I tested this also with Kodi 19 - same problem.
The problem occur on two devices both operating Android 7 (system updates installed, which does not help).
I also tested this on another device with Android 5 - works fine, also on PC with Windows 10 works fine as well.
An excerpt of Kodi log which shows an error:
https://pastebin.com/MRumft7L (especially look at 3 last lines!)
May anyone help?

**Comment by matthuisman** [comment] 2021-08-17 19:19
Please upload a copy of the manifest and a full debug log.

I suspect this is a duplicate of my issue here
https://github.com/xbmc/inputstream.adaptive/issues/686

Oh wait, you say audio does work on Android 5 and windows 10 so maybe not the same issue

**Comment by michael112** [comment] 2021-08-19 09:44
@matthuisman Please give me a little bit of time, I need to make a test with an example material on my various devices.

**Comment by mtr81** [comment] 2021-10-03 19:13
The same problem:
Manifest -> [manifest.txt](https://github.com/xbmc/inputstream.adaptive/files/7274394/manifest.txt)
Full debug log ->[kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/7274382/kodi.log.txt)

**Comment by glennguy** [comment] 2021-10-04 02:18
@mtr81 thanks for the logs! Looks to be the same issue as reported in OP.

Don't have time just right now to dive in but this is what the concern is:
```
2021-10-03 19:34:19.212 T:10008   DEBUG <general>: AddOnLog: inputstream.adaptive: GetStream(1006)
2021-10-03 19:34:19.212 T:10008   DEBUG <general>: AddOnLog: inputstream.adaptive: GetStream(1006): initalizing crypto session
```

1006 being the audio stream, audio streams aren't meant to use a secure path.... will have to find out why this is getting set this way.

Something to note (for me) is that all streams (audio and video) are using the same PSSH/KID

**Comment by matthuisman** [comment] 2021-10-04 02:32
@glennguy 
another thing to note - that manifest above your last comment only has a single adaptation set which has contentType="video"

**Comment by glennguy** [comment] 2021-10-04 02:51
Check again, the formatting is really messed up but there looks like one adp per representation

**Comment by matthuisman** [comment] 2021-10-04 03:20
oops! my text editor just highlighted the top and bottom and not the rest so looked like just 1. i should have done a search.

**Comment by mtr81** [comment] 2021-10-04 22:27
Same device and other manifest - same result:
manifest: https://npobvn-prd.cdn.eurovisioncdn.net/live/npo/u/npo/drm/dash_cenc/bvn/0/0/0/bvn.isml/stream.mpd
kodi log ->[kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/7281633/kodi.log.txt)

**Comment by michael112** [comment] 2022-02-19 21:06
Hey,
very sorry for my big delay,

Manifest: [manifest.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/8102993/manifest.mpd.txt)
Log: [log.txt](https://github.com/xbmc/inputstream.adaptive/files/8102994/log.txt)

By the way, I got a bit new knowledge. I suspect this:
```2022-02-19 20:19:50.238 T:7143   ERROR: CDVDAudioCodecAndroidMediaCodec::ExceptionCheck: configure```
which probably come from: https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecFFmpeg.cpp#L44
which describes a Java exception as I read on the internet.
However, this gives me absolutely no information, what is this exception, no possible cause.
If I'd like to edit this code in order to print more info about this exception, I would have to recompile all the Kodi (!).

Also, I would like to mention, this very stream plays well on the official provider application on the same device (so, the phone CAN decode DRM from audio stream) - but I prefer Kodi because it's one application combining all the streaming platforms I subscribe (consuming less space on the phone), also in Kodi I can combine TV channels from various streaming providers on one list in the IPTV manager.

Maybe together we could find out more about that?

**Comment by glennguy** [comment] 2022-02-19 23:27
The exception is being printed - to Android log: https://github.com/xbmc/xbmc/blob/6586a6c535b72896e00733f25fde93980d5f0cca/xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecAndroidMediaCodec.cpp#L536-L538

You should be able to see in logcat what the exception is, if you could get that and post back here it would be great, hopefully is easy enough to do on your TV.

Thankfully this stream isn't geolocked, I've tested on my pixel3/android 12 and it plays fine with sound.

**Comment by michael112** [comment] 2022-02-20 08:20
How to get the Android log?

**Comment by glennguy** [comment] 2022-02-20 11:16
You need to do similar to this. Also will need adb installed on whatever device you're using to remote into the tv. Like with this link I found below, just search 'how to install adb on x'

https://stackoverflow.com/questions/39834242/sony-bravia-android-tv-how-to-enable-retrieve-adb-logcat-logs

**Comment by michael112** [comment] 2022-02-20 11:54
My device is just a phone, not a smart tv.

Wait a few minutes (maybe little more than few). Probably I've found a solution (to get Android log).
I've downloaded Android Studio (portable) and the wizard after first opening tutored me to download Android SDK.
Also, i've found a tutorial - even in my native language(!) ;) which has guided me step-by-step to set the connection between my computer and phone. ADB was included in Android SDK.

According to what I've read all I need to get the log is to type **adb logcat** in the console when it is set in the folder {sdk-directory}/platform-tools.

**Comment by michael112** [comment] 2022-02-20 12:20
That may probably be this: [android-log.txt](https://github.com/xbmc/inputstream.adaptive/files/8103948/android-log.txt)
(I need to be careful not to publish something private in the log.)
```
02-20 13:01:57.951 14193 15090 W System.err: android.media.MediaCodec$CodecException: Error 0x80000002
02-20 13:01:57.957 14193 15090 W System.err: 	at android.media.MediaCodec.native_configure(Native Method)
02-20 13:01:57.957 14193 15090 W System.err: 	at android.media.MediaCodec.configure(MediaCodec.java:1895)
```

**Comment by glennguy** [comment] 2022-02-22 09:54
I'd say the problem is lack of support in your OS, can't be sure but I'm nearly 100% sure that it isn't to do with this add-on sorry

**Comment by kszaq** [comment] 2022-02-22 18:52
@michael112 You can try to enable "Don't use secure decoder if possible" in Inputstream Adaptive settings to see if it helps.

**Comment by CastagnaIT** [comment] 2023-02-07 19:40
from the logcat seem we are providing an audio stream of 0 channels in the configuration

```
02-20 13:01:57.914   251  1015 D MtkOmxRawDec: RAW mRawParamForInput.nChannels is 0
02-20 13:01:57.914   251  1015 E MtkOmxRawDec: input parameters is invailed !
02-20 13:01:57.920 14193 15119 E ACodec  : unsupported PCM port: 0 channels interleaved, 16-bit
02-20 13:01:57.920 14193 15119 E ACodec  : [OMX.MTK.AUDIO.DECODER.RAW] configureCodec returning error 80000002
```

perhaps in the android versions > 7 are able to ignore the wrong value and the problem is hidden
maybe we should try before check if audio parameters are correctly parsed from the mpd

@michael112 are you still around here? can you try also with kodi v20, just to be sure that the problem still exists?

**Comment by michael112** [comment] 2023-02-15 01:50
> @michael112 are you still around here? can you try also with kodi v20, just to be sure that the problem still exists?

Hey. I've just tried with K20 on that tablet and audio is still not working.

(Also, because of tablet touch interface, I've wrongly closed the issue and then reopened. The problem still occurs.)

If you need a debug log, please wait a bit. It's 3 at night in my time zone.

**Comment by CastagnaIT** [comment] 2023-02-17 15:58
@joseluismarti can you give some hints or (maybe) a kind of solution to this android problem?

looks like we are sending 0 channels to android audio configuration from kodi core (see comments above), is possible?
@michael112 affirm that this problem happens only to android v7 (android 5 works good)

i have no idea what we could try to do

**Comment by CastagnaIT** [comment] 2023-02-17 17:24
@michael112 i found something but im not sure if can help for your case

try install this InputStream test build to kodi 20:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1145/1/artifacts
and let me know

**Comment by joseluismarti** [comment] 2023-02-19 16:33
Is it possible to build inputstream.adaptive for x86 ABI to test on an Android 7 x86 image?
I've tried to reproduce the issue with an arm image but it's too slow

**Comment by CastagnaIT** [comment] 2023-02-19 17:30
maybe this old script could give you some hint https://github.com/CastagnaIT/inputstream.adaptive/blob/Matrix/build_scripts/build-isa.sh

**Comment by CastagnaIT** [comment] 2023-03-18 08:53
hi @michael112 i dont know if you have time
but if so please do a last test with the test build for Kodi 20
see my comment above where there is the link for download it https://github.com/xbmc/inputstream.adaptive/issues/775#issuecomment-1434976010 might be enough to fix the problem

**Closed as not planned** 2023-06-05 18:35 UTC
Labels: Issue Cleanup: Ask Reporter, Resolution: External, Component: Audio, Component: MPEG-DASH

**Comment by CastagnaIT** [comment] 2023-06-28 16:01
just to inform that in the next Kodi 20 Nexus and 21 Omega releases has been add a fix
that potentially can fix also your audio problems

**Comment by mtr81** [comment] 2023-07-15 19:15
I confirm - works fine on K20.2 + IS 20.3.9. Thanks!

**Comment by michael112** [comment] 2023-08-03 22:48
Thanks, working also for me!
