### ISSUE TITLE
Streaming Widevine CDM content with Kodi on Fire TV Stick is no longer working

### ISSUE THREAD

**Issue by AntonelloA** [peak3d/inputstream.adaptive#1473] opened 2024-02-10 17:51 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

Hi all, 
lately I'm having troubles in streaming FREE content (specifically italian channel **La7**) with Kodi installed on a Fire TV Stick, and the excellent WLTV Helper add-on.
I think the problem is somehow related to the FireOS implementation of Widevine CDM.
Content is garbled, and after few seconds even other channels on Kodi stop working, and I need to restart the OS to be able to watch them again. Until a few days ago everything was working fine.
NOTE: Kodi on a Sony Android Smart TV, and Kodi on Windows are working fine.
The problem is only on FireOS, which I think is based on Android 9.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect to correctly view and hear the content of the free italian channel "La7", as I was able to do until a few days ago. 

## Actual Behavior

Video content is garbled, and after few seconds even other channels on Kodi stop working, and I need to restart the OS to be able to watch them again.

### To Reproduce

1. Install WLTV Helper (World Live TV Helper) [as described here (in italian)](https://www.howtechismade.com/guide/come-vedere-i-canali-tv-italiani-su-kodi/)
2. When configuring WLTV Helper, select "DTT" as the list of channels
3. Try selecting one of the channels, to be sure it is working, then select "**LA7**"
4. NOTE: Kodi on a Sony Android Smart TV, and Kodi on Windows are working fine. The problem seems to be only on FireOS, which I think is based on Android 9.

### Debuglog

The debuglog can be found here:
[DEBUGLOG](https://paste.kodi.tv/ihodexafuy)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
I think this is the relevant manifest:
[https://d15umi5iaezxgx.cloudfront.net/LA7/DRM/DASH/Live.mpd](https://d15umi5iaezxgx.cloudfront.net/LA7/DRM/DASH/Live.mpd)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![2024-02-09-17-40-48-698](https://github.com/xbmc/inputstream.adaptive/assets/20526070/6f596ebe-0826-4676-af78-9c755ab67bb6)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fire OS 7.6.6.4
 - Kodi version: 20.3
 - inputstream.adaptive version: 20.3.17

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by AntonelloA** [comment] 2024-02-10 17:59
I think this is the requested manifest:
[https://d15umi5iaezxgx.cloudfront.net/LA7/DRM/DASH/Live.mpd](https://d15umi5iaezxgx.cloudfront.net/LA7/DRM/DASH/Live.mpd)

**Comment by CastagnaIT** [comment] 2024-02-11 10:22
before try restore the previous ISA version 20.3.16
downloads https://mirrors.kodi.tv/addons/nexus/inputstream.adaptive+android-armv7/

**Comment by AntonelloA** [comment] 2024-02-11 16:15
> before try restore the previous ISA version 20.3.16 downloads https://mirrors.kodi.tv/addons/nexus/inputstream.adaptive+android-armv7/

Yes, with Inputstream.adaptive 20.3.16 everything is working fine.
Thanks

**Comment by CastagnaIT** [comment] 2024-02-12 14:33
look like the problem is the same of #1468
and so its needed investigate on the variable fixed with https://github.com/xbmc/inputstream.adaptive/commit/0566e1267c93b85efd09881645983cd913d48e2d

**Comment by AntonelloA** [comment] 2024-02-12 15:00
Contrary to what I wrote before, the garbled screen were also on a Sony Smart TV with Android TV 9, but not as bad as that on the Fire Stick (also based on Android TV 9). No problem on Windows, instead.  Reverting to ISA 20.3.16 fixed all Android problems.

**Comment by CrAcK75** [comment] 2024-02-13 21:24
> Contrary to what I wrote before, the garbled screen were also on a Sony Smart TV with Android TV 9, but not as bad as that on the Fire Stick (also based on Android TV 9). No problem on Windows, instead. Reverting to ISA 20.3.16 fixed all Android problems.

Thank you so mutch for your help friend, you are the only one

**Comment by CastagnaIT** [comment] 2024-02-14 16:02
i made a test fix, please give feedback, choose the preferred build:
test build for Kodi 20: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1476/1/artifacts
test build for Kodi 21: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1475/2/artifacts

**Comment by AntonelloA** [comment] 2024-02-14 17:04
> i made a test fix, please give feedback, choose the preferred build: test build for Kodi 20:

Kodi 20 on arm, the problem is gone.
Thank you

**Closed as completed** 2024-02-19 11:54 UTC

**Comment by kine90** [comment] 2025-04-02 11:39
La7 stopped working also for me with the last update. I am using Kodi 20 for Linux (Ubuntu) running on an intel NUC. Starting La7 live makes Kodi crash and close, leaving any trace of critical errors in Kodi logs. Replay content works.

**Comment by AntonelloA** [comment] 2025-04-02 12:05
> La7 stopped working also for me with the last update. I am using Kodi 20 for Linux (Ubuntu) running on an intel NUC. Starting La7 live makes Kodi crash and close, leaving any trace of critical errors in Kodi logs. Replay content works.

The same happened to me, right now after Widevine CDM update.
