### ISSUE TITLE
[Disney+] Subtitles appear 6 seconds early

### ISSUE THREAD

**Issue by MauriceW67** [peak3d/inputstream.adaptive#1212] opened 2023-04-07 17:35 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing some titles with @matthuisman 's Disney+ addon, the subtitles appear exactly 6 seconds early.

Shows that have the issue: Loki, Marvel Studios LEGENDS, The Book of Boba Fett, National Treasure Edge of History

NOTE: The issue seems similar to https://github.com/xbmc/inputstream.adaptive/issues/993 but this was supposed to be fixed. Also, subtitle fixes from https://github.com/xbmc/inputstream.adaptive/issues/1090 were supposed to be part of the fix, but unfortunately there still is an issue and the time difference is now 6 seconds instead of 3.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The subtitles should appear at the correct time and not 6 seconds early.

## Actual Behavior

Subtitles appear 6 seconds early on some shows.

### To Reproduce

1. Start Kodi v21
2. Open the Disney+ addon
3. Browse a show that has the issue (I used National Treasure Edge of History)
4. Play the episode

### Debuglog

The debuglog can be found here:
Kodi 21 log: https://paste.kodi.tv/amogagefef.kodi
Kodi 20.1 log: https://paste.kodi.tv/hivojowoco.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield Experience 9.1.0 (Android TV 11)
 - Kodi version: Kodi 21 Omega (kodi-20230406-42f35c38-master-arm64-v8a)
 - inputstream.adaptive version: 21.1.0

NOTE: Issue also occurs with Kodi 20.1 Nexus and IS:A 20.3.6

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by tsioukas** [comment] 2023-04-08 15:30
I can confirm it for other TV Shows also on Kodi 20.1 for Sony Google TV. All shows that I tried to play have subtitles out of sync. Movies doesn’t have this problem.

**Comment by glennguy** [comment] 2023-04-09 01:33
Thanks for opening this issue @MauriceW67 and for confirmation @tsioukas 

I can see the same behaviour here.

@CastagnaIT I think a change like this is what's needed, we need to reverse the polarity of the offset:
```
diff --git a/xbmc/cores/VideoPlayer/DVDCodecs/Overlay/OverlayCodecWebVTT.cpp b/xbmc/cores/VideoPlayer/DVDCodecs/Overlay/OverlayCodecWebVTT.cpp
index 1e3bab67df..a9210a4496 100644
--- a/xbmc/cores/VideoPlayer/DVDCodecs/Overlay/OverlayCodecWebVTT.cpp
+++ b/xbmc/cores/VideoPlayer/DVDCodecs/Overlay/OverlayCodecWebVTT.cpp
@@ -66,7 +66,7 @@ OverlayMessage COverlayCodecWebVTT::Decode(DemuxPacket* pPacket)

   m_webvttHandler.Reset();

-  m_webvttHandler.SetPeriodStart(pPacket->m_ptsOffsetCorrection);
+  m_webvttHandler.SetPeriodStart(pPacket->m_ptsOffsetCorrection * -1);

   if (m_isISOFormat)
   {
```

**Comment by CastagnaIT** [comment] 2023-04-09 07:43
non ending story... i hope its the last fix
i will do the PR and attach test builds

**Comment by CastagnaIT** [comment] 2023-04-09 08:07
@glennguy i dont know if its due to this proposed change or due to the new rework
but DASH_WebVTT_ISO-MP4 sample now have subtitle broken
so its needed investigate

**Comment by CastagnaIT** [comment] 2023-04-09 17:27
Test build (kodi 21) with the fix:
http://mirrors.kodi.tv/test-builds/android/arm/kodi-20230409-f27a061d-fix_webvtt_pts-armeabi-v7a.apk
http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20230409-f27a061d-fix_webvtt_pts-arm64-v8a.apk
http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20230409-f27a061d--x64.exe

please test with ISA test builds (kodi 21) from here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1219/1/artifacts

PS: DASH_WebVTT_ISO-MP4 is not affected by this change, there was a regression from recent rework

**Comment by MauriceW67** [comment] 2023-04-09 18:50
@CastagnaIT I tested with the Kodi 21 fixed build and the IS:A build above, but then all kinds of weird things start to happen. If I play an episode on Disney+, it only loops the initial 3 second bumper as if it's on repeat or something.

If I skip the video forward, it starts to play, but without sound and also skipping forward automatically for like 5 seconds all the time.

I then went back to the official IS:A 21.1.0 and that seems to work just fine, with subtitles in sync.

**Comment by glennguy** [comment] 2023-04-10 02:17
@MauriceW67 the included parser rework has an issue with setting the correct audio codec...

@CastagnaIT previously there was HLS specific handling of the information in `CODECS`: https://github.com/xbmc/inputstream.adaptive/blob/77a58c03fd986743811721b59e238a0a336924b1/src/parser/HLSTree.cpp#L81-L89

For D+ 

With this removed we rely on the common implementation which in this example will return avc for the codec string `CODECS="avc1.64001f,ec-3,mp4a.40.2` : https://github.com/xbmc/inputstream.adaptive/blob/2b4bc407fd3641854b9e5df2372027c515d36a91/src/Session.cpp#L949-L971

I'm not sure if the separate handling for HLS was for a particular reason or just an oversight. Rearranging the order in Session.cpp could get us the behaviour we want but I don't know if there would be unintended side effects.

**Comment by CastagnaIT** [comment] 2023-04-10 06:28
was not very clear to me, nor was it documented
but now that i understood it's just luck that it worked

i will try reimplement it by add a new "todo"
it is inappropriate to do this, CODECS attribute is optional and also dont guarantee codec order or full list
imo should be the MP4 demuxer to provide codec format

**Comment by CastagnaIT** [comment] 2023-04-10 07:50
PR's ready for nexus/omega the fix will be merged soon
ofc you will need to install nightlies until new kodi versions will be released

**Comment by MauriceW67** [comment] 2023-04-10 09:22
@CastagnaIT Thanks for fixing this and working on it even over the Easter weekend!

I assume I can just use the fixed Kodi version with the current release version of IS:A 21.1.0 without breaking anything?

**Comment by CastagnaIT** [comment] 2023-04-10 09:26
yeah i did not go on holiday
you should be able to use current ISA releases
and also this new kodi 21 ISA test build:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1219/6/artifacts

(ofc with kodi 21 test builds linked above)

**Comment by MauriceW67** [comment] 2023-04-10 10:53
@CastagnaIT I tried the IS:A from PR-1219 and although it works fine on the more recent 4K Dolby Vision titles in the Disney+ app, it shows heavy stuttering / frame skipping on older 1080p SDR titles such as Agents of SHIELD and Buffy the Vampire Slayer.

So I went back to the release version of IS:A and it solved the frame skipping. However when I resume an episode that I started watching previously, no subtitles are shown at all. Only way to fix it is to stop playing the episode and have Kodi start playing it from the beginning.

**Comment by CastagnaIT** [comment] 2023-04-10 11:15
differents problems that needs separate investigations
i have no access to d+ so i cannot test/investigate easily
but using my sample stream after resume subtitles are displayed as expected
make sure that kodi has not disabled subtitles after video resume

**Closed as completed** 2023-04-18 06:52 UTC
Labels: Resolution: Fixed

**Comment by pmsobrado** [comment] 2024-01-30 07:45
Sorry, I've been reading this issues but couldn't get it, is there a fix for this for Kodi 20?
