### ISSUE TITLE
Sky Sports Now NZ issue with playback

### ISSUE THREAD

**Issue by Sportsmaniacuk** [peak3d/inputstream.adaptive#1107] opened 2023-01-27 19:25 UTC
Using Kodi 20 with Slyguy repo. I select a channel and instead of the video coming on automatically I have to press the back key on the Nvidia Shield remote several times to get the video.

**Comment by glennguy** [comment] 2023-01-28 00:09
Duplicate of #1043

**Closed as completed** 2023-01-28 08:55 UTC
Labels: Duplicate
