### ISSUE TITLE
Fire TV 4K quits when video should play

### ISSUE THREAD

**Issue by xciser77** [peak3d/inputstream.adaptive#176] opened 2018-08-01 08:17 UTC
I was trying the netflix plugin for kodi 18. I can login and select a video, but when it shouls start Kodi quits to the main menu of the Fire TV. I posted it on the plugin page, but they mentioned its a issue of the inputstream:
I'm submitting a ...

 x   bug report

General information

I installed a clean nightly of Kodie 18 and the latest plugin version (0.13.10). I can login, can select a video, but when i supposed to start Kodi quits and I get the main screen of the amazon fire tv.
Prerequisites

Are you running the latest version? Yes

**Description**
Kodi quits when video is supposed to start
Steps to Reproduce

    Start Netflix plugin
    Select Account
    Select video to play

Expected behavior: [What you expected to happen]
I expect the video to start playing

Actual behavior: [What actually happened]
Kodi quits to the main menu of the Fire TV
Context (Environment)

Amazon Fire TV 4K, Fire OS 5.2.6.3
Kodi 18 build 30-7
Plugin 0.13.10
Installation

Did a clean install of Kodi 18 and only installed the Netflix plugin
    I´m using the Netflix Repo

Operating System
    Android

Additional information on the environment

I am using a Fire TV 4K from 2017 with the 32 bits version Kodi 18
The Inputstream version is 2.2.24
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/2248597/kodi.log)

**Comment by MRLB** [comment] 2018-08-04 19:33
No inputstream Works anymore. Dazn, ESPlayer, Telekom Sport. Every Addon which use inputstream crashed unfortunately on FireTV now

**Comment by jecaho** [comment] 2018-08-12 09:03
same issue here with amazon fire stick tv (basic edition), when i try to play a video kodi quit.
i notice that with kodi 18 alpha 1 i am able to play a video, but when i try to forward the video stop playing

**Comment by MRLB** [comment] 2018-08-18 05:33
Is there and solution?

**Comment by dontknowcris** [comment] 2018-08-27 18:45
Samsung issue with dazn addon. On Fire TV Stick, kodi 18 alpha 1 works properly, from alpha 2 ti beta 1, the program crashes wgen trying to play a content

**Comment by dontknowcris** [comment] 2018-08-27 18:46
Same issue with dazn addon. On Fire TV Stick, kodi 18 alpha 1 works properly, from alpha 2 ti beta 1, the program crashes wgen trying to play a content

**Comment by JinRonin** [comment] 2018-08-28 10:19
I think it would be good if anyone can check when exactly this issue starts and what the latest working kodi 18 nightly / inputstream adaptive version is. Please post debug and crash log aswell.

**Comment by dontknowcris** [comment] 2018-08-28 10:55
I can't post debug and crash log because I can't find them on Fire TV Stick.
Btw, the working version of kodi 18 is the alpha 1 with inputstream adaptive 2.1.13 and rtmp input 2.0.3, with all the version after first alpha the program crashes trying to open a stream

**Comment by dontknowcris** [comment] 2018-08-28 11:05
To understand if crash problems are related to versions of kodi after alpha 1 or inputstream addon, it would be good having the inputstream zip 2.2.25 to install on alpha 1

**Comment by azbesthu** [comment] 2018-08-28 22:40
java.lang.NoSuchMethodError: no non-static method "Landroid/media/MediaDrm$KeyRequest;.getRequestType()I"

Useful logs can be found here, I saw similarlog with different affected addon:
https://github.com/asciidisco/plugin.video.netflix/issues/433#issuecomment-412841695

Because it works on AndroidTv 8, and Fire Tv stick based on Android 5.x, maybe it can be reproduce with any device that have 5.x system. 

New inputstream.adaptive seems to have higher versioned dependencies that Kodi Leia Alpha1 had, so 2.2.25 seems to be incompatible with that.

**Comment by azbesthu** [comment] 2018-08-30 13:33
Is there similar check somewhere in inputstream.adaptive or in Kodi where you can select which wvdecrypter implementation to in use on Android? 

I'm asking because other addons are also trigger similar crash in Kodi and those are completly rely on inputstream.adaptive. E.g.:
https://github.com/billsuxx/plugin.video.hbogohu/blob/master/addon.py

**Comment by peak3d** [comment] 2018-08-30 13:38
It's very unlikely that other addons trigger this code place.
We're talking here about a DRM CryptoSession which uses DRM to encrypt / decrypt HTTP messages.

This path is completely separate to inputstream.adaptive, it's a direct addon <-> kodi communication.
Sure it can be checked in kodi itself (yes, its safer) but would not help for Netflix. It must be fixed there in a first place, regardless if kodi has a check included and fails creating the CryptoSession

**Comment by peak3d** [comment] 2018-08-30 13:47
Wait, just seen that getKeyRequestType is used in wvdecrypter too, but only for logging.
Sure, no problem to remove it there

**Comment by peak3d** [comment] 2018-08-30 13:51
https://github.com/peak3d/inputstream.adaptive/commit/997abf6c9d3f60a0ebcff841fd31062fb7eb02c8

**Closed** 2018-08-30 13:52 UTC

**Comment by dontknowcris** [comment] 2018-08-30 14:37
How can I check if the problem has been solved with this correction? Is there a zip that I can use to test or do I have to wait for kodi beta2?

**Comment by peak3d** [comment] 2018-08-30 14:48
You can try tommorow kodi 18 nightly from our download section

**Comment by dontknowcris** [comment] 2018-08-30 14:49
OK, thank you so much

**Comment by dontknowcris** [comment] 2018-08-31 14:04
It works with vod, kodi doesn't crash. Tonight I Will try with live events

**Comment by azbesthu** [comment] 2018-08-31 16:27
Thank you, kodi-20180830-af7276ca-master-armeabi-v7a.apk works fine with unofficial hbo go hungary addon :)

**Comment by dontknowcris** [comment] 2018-09-03 13:43
sorry if I cannot post any crash logs here, but I cannot find them on the fire tv stick
by the way, at this time, kodi crash always at the same time in some streams running on dazn addon.
when I try to watch a football match on demand, the match starts without any problem, but after some minutes there's a buffering and the video freezes. if I try to stop the playback and going back to football matches list, then kodi crashes and goes back to the home of fire tv. and if I try to play again the same vod the video always freezes at the same point then the previous one
same issue with live events (obviously in this case, the crash moment is different, depending on when I try to play a match)
