### ISSUE TITLE
Stopping playback causes crash (Mac)

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#787] opened 2021-08-31 22:51 UTC
https://forum.kodi.tv/showthread.php?tid=353316&pid=3056393#pid3056393
https://forum.kodi.tv/showthread.php?tid=353316&pid=3056919#pid3056919
https://github.com/xbmc/inputstream.adaptive/issues/783#issuecomment-909185790

it seems removing this commit: https://github.com/xbmc/inputstream.adaptive/commit/59e66aad837a07ec87ad41994121a37ce8747d55
helps it happen less often, but still does occur sometimes even with it removed

**Comment by matthuisman** [comment] 2021-08-31 22:53
@Badsheep
Does the stop bug happen on any other content or add-ons?
Or only Disney+?

**Comment by Badsheep** [comment] 2021-09-01 02:12
I noticed it happens with Netflix Addon too.

**Comment by matthuisman** [comment] 2021-09-01 06:45
do you know the last known "good version" that didn't do it?
2.4.7 ?

**Comment by Badsheep** [comment] 2021-09-01 07:00
I tried the 2.4.7 and I think if was better ! Similar to the 2.6.23 modified version you made me try.
Cf [Here](https://github.com/xbmc/inputstream.adaptive/issues/783#issuecomment-908702838).

**Comment by matthuisman** [comment] 2021-09-01 07:01
thats because 2.4.7 doesnt have the commit that my version removed.

you said that modified version didnt fix the crash on stop though...
so i assume with 2.4.7 you also get the crash on stop?

or, is 2.4.7 completely fixed with no crashes at all?

**Comment by Badsheep** [comment] 2021-09-01 07:13
No I still sometime have a crash (exactly as your 2.6.23)

**Comment by Badsheep** [comment] 2021-09-01 07:54
The last version I had working well before was the 2.4.2… if I have time I’ll test to increment versions from 2.4.2 to 2.4.8 to see at which version the problem appears. But I’m no sure the addons will support such old versions of inpustream.adaptive. I’ll try someday.

**Comment by thombet** [comment] 2021-09-01 10:18
If it helps I am almost sure I have the same problem on OSMC so I think it is not only a MacOS issue.

**Comment by Badsheep** [comment] 2021-09-01 21:08
> The last version I had working well before was the 2.4.2… if I have time I’ll test to increment versions from 2.4.2 to 2.4.8 to see at which version the problem appears. But I’m no sure the addons will support such old versions of inpustream.adaptive. I’ll try someday.

I won't be able to do this test because I can't find the binaries before 2.4.6.
But anyway I did tests with the 3 versions available, and it was interesting : 

- Mac OS, Kodi 18, input v2.4.6 > solid as rock
- Mac OS, Kodi 18, input v2.4.7 > solid as rock
- Mac OS, Kodi 18, input v2.4.8 > crashed the second time I pressed Stop.

And I don't know why but this time with  2.4.7 I wasn't able to get any crash ! Maybe the crashes I had before were rare incidents and the problem is solved with this version ?

**Comment by matthuisman** [comment] 2021-09-01 22:49
can you try this on Mac OS Kodi 18:
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-786/1/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-2.4.8.zip

That is 2.4.8 but with that seek commit removed.

**Comment by glennguy** [comment] 2021-09-01 23:10
Could you have a look for a crash file. From the Kodi wiki:
> Mac OS X
OS X will always create a Crashreporter log if any application crashes. These are found in /Users/username/Library/Logs/CrashReporter/CrashReporter.log where 'username' is the login username. For the Apple TV 1, the 'username' is 'frontrow'.

If you find this for the crash caused by this issue could you attach here?

**Comment by Badsheep** [comment] 2021-09-02 06:48
> can you try this on Mac OS Kodi 18:
> https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-786/1/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-2.4.8.zip
> 
> That is 2.4.8 but with that seek commit removed.

I crashes I'm sorry...

glennguy I didn't found your files, the directory exists but no file CrashReporter.log in it.

I searched found something else who looks similar : Kodi_2021-09-02-084011_MacBook-Pro-de-Matthieu.crash
in Logs/DiagnosticReports/

[Here it is.](https://paste.kodi.tv/totizitumi.kodi)

**Comment by matthuisman** [comment] 2021-09-02 07:04
are you able to update to at least kodi 18.9 when testing?
older versions had various issues

**Comment by Badsheep** [comment] 2021-09-02 07:07
Ok I’ll do this next time.
I’ll test that tonight, alter work.

**Comment by matthuisman** [comment] 2021-09-02 07:07
here is the next version to try please:
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-786/2/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-2.4.8.zip
(basically im just removing commits until we find the culprit)

**Comment by glennguy** [comment] 2021-09-02 07:12
Thanks @Badsheep - that is the file I was after. Could you also please attach the kodi.log that goes with the crash as well (when you test tonight)? Thanks!

**Comment by Badsheep** [comment] 2021-09-02 07:13
Ok ! Thanks guys for your help

**Comment by Badsheep** [comment] 2021-09-02 07:13
Ok ! Thanks guys for your help

**Comment by glennguy** [comment] 2021-09-02 07:19
Can't see any trace of inputstream.adaptive in the stack trace, but widevine is still loaded. Also the thread that crashed has no symbols in it, making me think that widevine is causing the crash. Looking at the log posted on the forum IA has already unloaded: `ADDON: Dll Destroyed - InputStream Adaptive`

**Comment by thombet** [comment] 2021-09-02 10:44
> here is the next version to try please:
> https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-786/2/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-2.4.8.zip
> (basically im just removing commits until we find the culprit)

Since I have Kodi 18.9 installed on MacOS I tested this version I hope you won't mind @Badsheep 😉 
Unfortunately it sill crashes...

Here are the logs:

- [kodi.log](https://paste.kodi.tv/kavezozafo.kodi)
- [crash report](https://paste.kodi.tv/ejayemimic.kodi)

**Comment by Badsheep** [comment] 2021-09-02 20:09
Good idea @thombet it's better to have different sources !
I did the upgrade to 18.9.
It has just crashed for me very quickly, at the first video I stopped.

[kodi.log](https://paste.kodi.tv/iropiqefez.kodi)
[crash report](https://paste.kodi.tv/pekadiqipo.kodi)

**Comment by matthuisman** [comment] 2021-09-02 20:10
pretty sure we figured out what commit is causing.
ill post 2x more test versions shortly

UPDATE:
Ok, try

1) https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-786/3/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-2.4.8.zip

or below if the above doesnt fix

2) https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-786/4/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-2.4.8.zip

(dont worry about new logs - just Yes / No is fine)

**Comment by Badsheep** [comment] 2021-09-02 21:53
Version 1 : NO
Version 2 : YES :)

Tested with both Kodi 18.9 Disney+ and Netflix addons...
Absolutely no crashes with Disney+ (and some bugs in Netflix addon but it may be an old version and it wasn't related to the "stop" problem)

So to me the bug seems to be fixed for Kodi 18... Bravo 👍

**Comment by Badsheep** [comment] 2021-09-02 21:54
And thank you for your amazing work @matthuisman

**Comment by matthuisman** [comment] 2021-09-02 22:23
its not fixed yet, its simply we know which commit causes it :)

ill now do a 19 version with the same commit removed, so you can test.
That previous commit we removed to fix chapter seeking may have just been a "red herring"

**OK, please try this kodi 19 build:
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-784/3/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-2.6.23.zip**

Please test seeking across chapters, stopping etc

**Comment by Badsheep** [comment] 2021-09-03 06:56
Sorry I was carried away :)

And unfortunately this test crashed...
Kodi 19.1, up to date Disney+ and Netflix addons.
It didn't crash in Disney, and crashed in Netflix

[crash report](https://paste.kodi.tv/xegimofira.kodi)
[kodi.log](https://paste.kodi.tv/sizipunoyu.kodi)

**Comment by glennguy** [comment] 2021-09-05 23:14
@thombet @Badsheep Could you please try https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-792/1/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-2.6.23.zip

If there's still a crash can you enable debug logging, reproduce and attach log?

Thanks

**Comment by Badsheep** [comment] 2021-09-06 07:09
I crashed the second time I pressed stop, in Disney addon.

[crash report](https://paste.kodi.tv/ukutesoxim.kodi)
[Kodi.log](https://paste.kodi.tv/ozavuhubis.kodi)

**Comment by glennguy** [comment] 2021-09-06 13:20
Thanks @Badsheep , obviously it didn't fix the issue... I might get a mac VM set up sometime this week so I can debug properly.

**Comment by matthuisman** [comment] 2021-09-07 03:43
So, we know this commit fixed it: https://github.com/matthuisman/inputstream.adaptive/commit/1d7b790857968866c97856476a60380ffd2307d1

Next, I'm going to try to keep the thread stuff, but just remove the calls to CheckLicenseRenewal()

@ Badsheep
Ok, please try (this is for kodi 18 - im just going to use that for now to try narrow down):
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-793/1/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-2.4.8.zip

**Comment by Badsheep** [comment] 2021-09-07 08:36
Hello,

It crashes in Disney add-on

[crash report](https://paste.kodi.tv/akemuvucit.kodi)
[kodi Log](https://paste.kodi.tv/wiqovohufi.kodi)

**Comment by matthuisman** [comment] 2021-09-09 00:11
@Badsheep 
can you try this for me.

1. Update Inputstream Adaptive back to the normal repo version 
2. Confirm you have crash in Disney+ when stopping
3. Go into Disney+ settings and disable ALL the settings under general
4. Now see if you still get crashes

**Comment by Badsheep** [comment] 2021-09-09 07:01
I tried with Kodi 19.1 : same result, it crashes.

**Comment by matthuisman** [comment] 2021-09-23 22:01
@Badsheep 
can you advise the Widevine CDM version your using?
I'm starting to think these crashes started when we went to the latest 4.10.2252.0
If you downgrade that to 4.10.1679.0 and reboot. then do you get the crash in Disney+?
Pretty sure disney+ still works with 4.10.1679.0

**Comment by Badsheep** [comment] 2021-09-24 07:14
Hello,
I'm actually using 4.10.2233.0.
I'll try to downgrade and tell you, but I don't know how do that... I'll try and ask you if I don't find the way.

Do I have to downgrade inputstream helper ? I have the 0.57 version installed actually.

**Comment by Badsheep** [comment] 2021-09-24 11:22
OK now I understand how it works...

I haven't the 4.10.1679.0, but I found an old 4.10.1582.1 in old backups.
I just replaced the "cmd" folder (is it the right method ? It seems so because inputstream helper display the right version)

And it still crashes. (with the uptodate inputstream adaptive 2.4.8).

I'll try to find a 4.10.1679.0 and I'll try too.

**Comment by Badsheep** [comment] 2021-09-24 12:02
I'm sorry I can't find a libwidevinecdm.dylib in 4.10.1679.0 version anywhere on the web...

**Comment by Badsheep** [comment] 2021-09-24 13:29
I found a link where to download versions : 
https://redirector.gvt1.com/edgedl/widevine-cdm/903-mac-x64.zip

When I replace "903" with one of this numbers of versions, I can download them : 

1.4.9.1088
4.10.1146.0
4.10.1192.0
4.10.1196.0
4.10.1440.18
4.10.1440.19
4.10.1582.1
4.10.1582.2
4.10.2209.0
4.10.2209.0
4.10.2209.1

But the version you ask is not listed.
Do you want me to try one of this versions ?


-EDIT- I did several tests : 

4.10.1582.2 : crash.
Same result with 4.10.2209.1 (which is seen as "4.10.2233.0" by inputstream helper, I don't know why)
Same result with 4.10.1440.19 (which is seen as "1.3.6.1" by inputstream helper, I don't know why)
With 4.10.1196, the video doesn't play.

**Comment by matthuisman** [comment] 2021-09-24 19:05
Thank you 
My hunch was wrong it appears.

Can you check if changing audio track during playback also causes crash?

**Comment by Badsheep** [comment] 2021-09-24 20:24
Hello,
No problem with audio switching during playback.

**Comment by Badsheep** [comment] 2021-09-24 20:32
But I just noticed that often when I hit "command q" to leave Kodi (the Mac OS shortcut to quit an application) : 

- if I'm not in Disney or Netflix addon > it quits properly
- if I'm playing a video in Disney or Netflix addon > It often crashes the same way that when I press stop

May it be interesting ?

**Comment by CastagnaIT** [comment] 2023-02-09 08:38
@Badsheep are you able to test if problem occurs on Kodi v20?

**Comment by Badsheep** [comment] 2023-02-09 13:26
Hello, this bug is quite old, I forgot it...

Since then I'm using Kodi 19,  and it crashes from time to time but not very very often.
Sorry I don't use Kodi 20 yet.

**Comment by Badsheep** [comment] 2023-02-09 13:31
In the same time, there was a bug that was corrected recently : Kodi was [crashing at almost every exit ](https://github.com/xbmc/xbmc/pull/21864)(command-q).

So I have to admit that I'm a little bit lost about the bug of this thread.
But I can do precise tests if you need.

**Comment by CastagnaIT** [comment] 2023-02-17 15:50
if in the future you will use kodi 20 and this problem continues to happen,
(when you press stop while playing crashes) so open an new Issue
for now i close it, as we no longer provide support to Kodi 19

**Closed as not planned by CastagnaIT** 2023-02-17 15:50 UTC
Labels: Issue Type: Bug, Issue Cleanup: Ask Reporter

**Comment by Badsheep** [comment] 2023-02-18 12:01
Hello, I just installed Kodi 20 (I had to update a personal service.py that was broken...).
I'll let know if everything works.

**Comment by Badsheep** [comment] 2023-03-27 15:08
Hello Castagnal.
I did upgraded to Kodi 20.

I still have crashes from time to time.
It may happen : 
- When I hit escape to quit the movie
- When I hit command q to quit Kodi

I can't really tell what is the cause...
I think it only happens with streaming movies (I use Netflix and Disney addons), but I can't really be sure.

I join a [log of the last crash I had](https://paste.kodi.tv/exiqahayep.kodi).

Thanks

**Comment by glennguy** [comment] 2023-04-01 12:53
Thanks for this @badsheep. I think I have a solution in #1203 
You could try this zip - https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-1203/2/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-21.0.3.zip
It's for Kodi 21 however at the moment it's still compatible with Kodi 20. Keep in mind if you install this version because it's a higher version number you'll lose auto updates for newer v20 releases. You can fix this by installing a 20.x release over the top (in the addon info go to 'versions'). Otherwise if this ends up looking good with other testers I'll be backporting to v20 and doing a release shortly after.

**Comment by Badsheep** [comment] 2023-04-01 15:48
Hello Glenn Guy,
I'll try that and let you know !
Thanks

**Comment by Badsheep** [comment] 2023-04-01 16:03
Sorry, the add-on doesn't install.
When I try to install it, it says (in French) : 
"La dépendance de kodi.binary.instance.videocodec version 2.0.4 n'a pas pu être satisfaite"

And it seems to be right, when I check in the log I can see that at launch I have
kodi.binary.instance.videocodec v2.0.3 installed

Is it possible to install the 2.0.4 version ?

**Comment by CastagnaIT** [comment] 2023-04-01 16:05
you cant, you need kodi 21 different api

**Comment by Badsheep** [comment] 2023-04-01 16:06
Ok...
Maybe I'll try with Kodi 21.

**Comment by glennguy** [comment] 2023-04-01 17:41
Sorry my bad, I forgot the recent API change

**Comment by Badsheep** [comment] 2023-04-01 17:54
No problem, I did installed Kodi 21 with your inputstream adaptive version, I'll let you know how it works.

**Comment by Badsheep** [comment] 2023-04-07 20:39
Hello,
Not a single crash since one week...
Seems to be working !

**Comment by Badsheep** [comment] 2023-04-21 18:09
Still no crash after 2 weeks
