### ISSUE TITLE
Bad Status permanent failure (Armhf) (raspberry pi4) 

### ISSUE THREAD

**Issue by KimiyaMorozova** [peak3d/inputstream.adaptive#866] opened 2021-12-26 19:22 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
Inputstream adaptive does not play content from Netflix or YouTube Addon "Permanent Failure" 
Getting this bug whenever i want to play something: 
```
2021-12-26 20:13:38.729 T:9197     INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=-Y6K7F58ee0
2021-12-26 20:13:38.730 T:13285    INFO <general>: Creating InputStream
2021-12-26 20:13:38.730 T:13285   ERROR <general>: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
2021-12-26 20:13:38.730 T:13285   ERROR <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.youtube/play/?video_id=-Y6K7F58ee0]
2021-12-26 20:13:38.730 T:13285    INFO <general>: CVideoPlayer::OnExit()
2021-12-26 20:13:38.860 T:9197     INFO <general>: CVideoPlayer::CloseFile()
2021-12-26 20:13:38.860 T:9197     INFO <general>: VideoPlayer: waiting for threads to exit
2021-12-26 20:13:38.861 T:9197     INFO <general>: VideoPlayer: finished waiting

```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Video/Livestream plays normally 

### Debuglog

The debuglog can be found here:

[kodi_debug.txt](https://github.com/xbmc/inputstream.adaptive/files/7777459/kodi_debug.txt)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [*] Linux 
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: RASPBERRY PI OS BULLSEYE (Raspberry Pi 4) 
 - Kodi version: 19.3 Matrix
 - inputstream.adaptive version: (19.0.0-1~bullseye) 

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by glennguy** [comment] 2021-12-26 23:38
Debug logging isn't enabled so there's possibly info missing that would help.

Best guess though would be that you've copied your entire addons folder from another kodi installation that's running on a different platform/architecture. In that case the solution would be to reinstall inputstream.adaptive from a repository or compile it yourself/install

**Comment by KimiyaMorozova** [comment] 2021-12-27 13:18
My bad, here is a working debug log:
[kodi_debug.txt](https://github.com/xbmc/inputstream.adaptive/files/7780314/kodi_debug.txt)
 Compiling and installing it from source didnt help. reinstalling plugin from GitHub itself didnt help either, error is still the same.

**Comment by glennguy** [comment] 2021-12-27 22:36
> reinstalling plugin from GitHub itself

What do you mean by this?

**Comment by KimiyaMorozova** [comment] 2021-12-28 11:47
Oh, downloading the newist plugin from netflix, YouTube etc. from thier release page of github.

**Comment by CastagnaIT** [comment] 2021-12-29 16:27
I can confirm for the cause of `Permanent Failure` i also remember the following,
wrong installed ISA binary of an architecture that not match the device architecture, then you have to install the right ISA binary,
or also you could have updated ISA binary but Kodi has never been restarted then you have to reboot the device to be sure that the new binary is loaded in right way

**Comment by KimiyaMorozova** [comment] 2021-12-30 13:28
Installed is armhf version, what is the same version for kodi and the device structure. Another binary is not avalible from the Raspberry Repo. i could try to use a older kodi version, because i knew 18.7 was working fine, but i don't know where to get a 18.7 Repo.

**Comment by CastagnaIT** [comment] 2022-02-25 14:57
as you can see on #454 the reboot usually solve this problem
but it is not something that can be fixed by our part,
since there is another same issue i close this one

**Closed as completed by CastagnaIT** 2022-02-25 14:57 UTC
Labels: Resolution: External
