### ISSUE TITLE
Use custom headers for all downloads

### ISSUE THREAD

**Issue by cache-sk** [peak3d/inputstream.adaptive#624] opened 2021-03-30 18:39 UTC
Our iptv provider starts deliberately blocking user agent Kodi.

Our addon uses inputstream.adaptive with widevine DRM, manifest type MPD.
Noticed on Kodi 19, inputstream.adaptive version 2.6.8, but same behavior is reported on Leia.

Path used in list item is with custom headers, like:
`https://..../Manifest.mpd|Origin=https%3A//....&Referer=https%3A//....&User-Agent=Mozilla..etc`

Manifest is succesfully parsed, license update successful, but then:
```
CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
CurlFile::Open(0x2d383da20d0) https://..../init.m4v
AddOnLog: inputstream.adaptive: Download https://..../init.m4v failed with error: 403
AddOnLog: inputstream.adaptive: Unable to select stream!
```
Reason is - CurlFile is not using custom headers from original path.
I have used Chrome UA Spoofer to test, that our provider explicitly search for "kodi" in User Agent and then block Manifest.mpd, init.m4v and chunks with error 403..

Please, use passed custom headers for all downloads.

**Comment by matthuisman** [comment] 2021-03-30 19:50
you need to set **stream_headers** to the headers you want used on segments.
in your case, just set them to the same as your using for the manifest.

Also, if you want the headers on the license request, you need to add | (pipe) then headers after the license url as well
So, 3x different places you can define headers
```
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.stream_headers=User-Agent=Mozilla
#KODIPROP:inputstream.adaptive.license_key=https://widevine-proxy.appspot.com/proxy|User-Agent=Mozilla|R{SSM}|
https://raw.githubusercontent.com/matthuisman/ia_tests/master/mpd_widevine_decrypt_failed/master.mpd|User-Agent=Mozilla
```
But yes, maybe stream_headers and license_key headers should default to the manifest headers if not provided.

Actually, looking at the code
stream_headers looks like it overrides the headers provided for the mainfest.
So you should just need to set stream_headers and not need to set the | headers on manifest

UPDATE:
Confirmed - stream_headers will overwrite any manifest headers (used for all requests except license_key)

Not sure if this is the best behaviour
I propose:
1) stream_headers are used for segments and manifest unless manifest provides it's own headers
2) if no stream_headers - segments uses the manifest headers
3) license_key only uses it's own headers (as its in a different format and quite a bit of code to set defaults)

I've done a PR here to implement the above behaviour: https://github.com/xbmc/inputstream.adaptive/pull/625

**Anyway, to fix your issue - just use stream_headers**

**Comment by dagwieers** [comment] 2021-03-30 21:43
The documentation probably could use some love too in this regard.
https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivestream_headers

**Comment by cache-sk** [comment] 2021-03-30 22:35
Thank you both.
It never occurred to me that there is a setting for this, I assumed that custom headers sent with a manifest should be used.
Next time I'll look at the wiki first 😖
Can i close this?

**Comment by dagwieers** [comment] 2021-03-30 23:06
@cache-sk You opened it, you can close it 😉 (We cannot)

**Closed as completed** 2021-03-31 07:43 UTC
