### ISSUE TITLE
RegioTV focus WTV channel doesnt play smoothly (buffering and losts parts) since Kodi 19. stream without DRM 

### ISSUE THREAD

**Issue by Muro1983** [peak3d/inputstream.adaptive#670] opened 2021-05-03 09:55 UTC
stream without DRM 

stream is:
https://hls-origin01-focus-wtv.cdn01.rambla.be/main/adliveorigin-focus-wtv/_definst_/ARXpX7.smil/playlist.m3u8?fbclid=IwAR3NKz4Auk4OOJpf0YMlXBM_FvXi1EfWgK--4KvQ38XfAv_go2xs5xtp7pY
http_referer:
http://player.clevercast.com/players/video-js/

**Comment by glennguy** [comment] 2021-05-03 12:49
I don't know if there's much that can be done about this.
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:171576
#EXT-X-DISCONTINUITY-SEQUENCE:0
#EXT-X-PROGRAM-DATE-TIME:2021-05-03T12:35:50.132+00:00
#EXTINF:2.0,
media-uqxs7rz0g_b3000000_171576.ts
#EXTINF:2.0,
media-uqxs7rz0g_b3000000_171577.ts
#EXTINF:2.0,
media-uqxs7rz0g_b3000000_171578.ts
```

The stream has a buffer total of 6 seconds! Never seen that before.

Kodi has an 8 second internal buffer, so the buffer will never fill, and it won't take much for Kodi to want to stop for buffering. 

Currently IA will only download a segment after the previous segment has finished downloading, effectively we have a buffer window that floats between 1 and 2 segments, so 2-4 seconds in this case. Press 'i' or info button and watch the on screen timeline beg for mercy.

I've tested and had intermittent results. Sometimes it plays fine, others it buffers lots. Also checked Kodi 18 - same issue there.

**Comment by dagwieers** [comment] 2021-05-03 14:08
What is weird is that I have never experienced this on any of my Kodi v18 systems (Raspberry Pi3 or Pi4). It always worked correctly, and still does. I don't have any Kodi v19 systems at the moment.

**Comment by Muro1983** [comment] 2021-05-03 14:17
Indeed, since the update of kodi on my chromecast with google TV, it started to stutter. Previously it went great for like 2 or 3 months. Each day i watched the local news at 12u30 so i tested it quite good ;).

**Comment by dagwieers** [comment] 2021-05-03 14:23
@Muro1983 I do not test this channel frequently (I did when developing this add-on though), but I did test today on Kodi v18 (on Raspberry Pi4) and have only once (in a few hours of repeated playback) saw it buffer. Which is pretty good and not necessarily related to the stream itself (could have been network or backend).

**Comment by Muro1983** [comment] 2021-05-03 14:39
here on kodi 19 its really not watchable. Sometimes it buffers, skips parts or fastforwards. This happens on average every 10 to 15 seconds. On kodi 18 i never had performance issues and i watched it daily. I use chromecast with google TV with an usb hub with fixed ethernet connection. I have a stable and fast internet connection to the device.

**Comment by matthuisman** [comment] 2021-05-03 23:15
have you tried playing it via ffmpeg (not inputstream adaptive) ?
i tried and ffmpeg seems to play it fine

@glennguy 
Interesting - if I set overallSeconds_ = 0; in HLSTree.cpp - seems to play better.
Almost like if we don't tell kodi the buffer length - it doesn't try to wait.
Maybe we could set overallSeconds_ to 0 if it's less than 8?
https://github.com/xbmc/inputstream.adaptive/pull/671/files
Or maybe it's just coincidence with my internet speed / their server.

@Muro1983
Could you try a build from here on Kodi 19:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-671/1/artifacts

actually, i think it was just coincidence.
seems to be working good without above change now too

**Comment by glennguy** [comment] 2021-05-04 02:29
If there is indeed a difference between Kodi 18 and 19 then I don't believe it's in inputstream.adaptive. There has been no change in the behaviour of buffering, playlist refreshing or passing the data to Kodi.

My point above was that this would be a very fragile stream to try and play. Inputstream.adaptive will only look at a 6 second window in this case. It leaves barely any wiggle room for latency/connection delays

@Muro1983 could you please provide a debug log (debug logging enabled, not component logging though) from Kodi 19 reproducing the issue?

**Comment by dagwieers** [comment] 2021-05-04 02:31
> have you tried playing it via ffmpeg (not inputstream adaptive) ?
> i tried and ffmpeg seems to play it fine

@Muro1983 You can play using ffmpeg and referer like this:

    $ ffplay -headers "referer: http://player.clevercast.com/players/video-js/" https://hls-origin01-focus-wtv.cdn01.rambla.be/in/adliveorigin-focus-wtv/_definst_/ARXpX7.smil/playlist.m3u8?fbclid=IwAR3NKz4Auk4OOJpf0YMlXBM_FvXi1EfWgK--4KvQ38XfAv_go2xs5xtp7pY

Seems to work on my laptop (CentOS 7) quite well.

**Comment by matthuisman** [comment] 2021-05-04 02:33
oh, I mean via ffmpeg in Kodi - basically just don't make it use Inputstream Adaptive.

I was testing without the referer.
What does the referer do?

**Comment by glennguy** [comment] 2021-05-04 13:42
Also @Muro1983 it would be good if you could check that Kodi 18 still plays alright for you, maybe your upgrade to 19 and the issue here are a coincidence timing-wise

**Comment by kszaq** [comment] 2021-05-04 18:54
Looking at Regio TV addon it does not seem to use inputstream.adaptive.

I tried 3 setups:
* playing without inputstream specified: buffering and lost parts
* playing with ffmpegdirect: buffering and lost parts
* playing with inputstream.adaptive: smooth playback, buffer level always >20%

You can try these 3 playlists (change extension to `m3u`):
[regio.adaptive.txt](https://github.com/xbmc/inputstream.adaptive/files/6423321/regio.adaptive.txt)
[regio.ffmpeg.txt](https://github.com/xbmc/inputstream.adaptive/files/6423322/regio.ffmpeg.txt)
[regio.no_inputstream.txt](https://github.com/xbmc/inputstream.adaptive/files/6423323/regio.no_inputstream.txt)

**Comment by matthuisman** [comment] 2021-05-04 19:01
Oh man.. If its not using IA that'll be funny and a waste of everyone's time

**Comment by matthuisman** [comment] 2021-05-04 21:01
@kszaq 
think your right.
https://github.com/add-ons/plugin.video.regiotv/blob/master/resources/lib/addon.py#L30
can't see any Inputstream adaptive properties at all....

@glennguy @phunkyfish 
I think maybe we should implement the same issues template that the main xbmc repo uses?
No debug log = no help.
A debug log provided for this would have quickly shown it wasn't using IA

**Comment by Muro1983** [comment] 2021-05-04 22:15
Dear all,

First of all thx for investigating this. Secondly i'm not Kodi expert nor do i know anything about inputstream adaptive, ffmpeg, ... . In the old days when i was younger i did some virtual dub but thats kinda it. I can record things if you want and place on google drive. I have log viewer for Kodi installed but that has alot of logging. Its a chromecast with google TV so i cant drag and drop files easly here. If i could mail them to myself i could easly include them here.

I appreciate all the effort you guys have done so far. If it doesnt get resolved i would still get you guys a beer ;). 

So not resolved = still beer

Kind regards,
PJ

**Comment by matthuisman** [comment] 2021-05-04 22:25
@Muro1983
You've opened the issue in the wrong place.
The add-on in question isn't using Inputstream Adaptive.
Please close this issue.

You'll need to open a issue here: https://github.com/xbmc/xbmc
if you think it's a kodi / kodi ffmpeg issue

Thank you

**Comment by glennguy** [comment] 2021-05-07 10:04
All good @Muro1983 , it seems that this isn't to do with inputstream.adaptive so I'll close the issue.

**Closed as completed by glennguy** 2021-05-07 10:04 UTC
